### ISSUE TITLE
有来阅文集团的吗，非996大厂，1075

### ISSUE THREAD

**Issue by zhangalonga** [996icu/996.ICU#1014]
有来阅文集团的吗，非996大厂

**Comment by JZXiang** [comment]
收Android简历么？

**Comment by zhangalonga** [comment]
北京还有安卓坑位，上海没了

**Comment by JZXiang** [comment]
就在北京，可以帮忙内推么？

**Comment by LiangLuDev** [comment]
@zhangalonga 大佬   Android坑有吗？

**Comment by zhangalonga** [comment]
可以，邮件1518381923@qq.com,@LiangLuDev 上海没安卓坑了

**Comment by LiangLuDev** [comment]
@zhangalonga 好吧   我在上海 没坑就算了。谢谢啦。有坑的话可以帮忙内推一下

**Comment by JZXiang** [comment]
@zhangalonga 已发送至邮箱，感谢大佬。

**Comment by zhangalonga** [comment]
@JZXiang 已内推

**Comment by JZXiang** [comment]
感谢！

**Comment by lovemybabyxuan** [comment]
上海有测试坑位么

**Comment by zhangalonga** [comment]
@lovemybabyxuan 有一个
招聘类别：
社会招聘
工作性质：
薪资范围：
面议
需求部门：
技术部
工作地点：
浦东新区
招聘区域：
上海
职位类型：
技术
工作职责：
主要承担二次元业务App等各类产品相关质量保证工作，包括但不限于功能测试、性能测试、兼容性测试等软件测试过程；
参与项目需求评审、设计评审等质控过程，在项目前期把控项目质量；
运用各类自动化工具实现测试自动化，提高测试效率；
配合项目团队完成相关任务，实现项目团队业务指标；
任职资格：
3年软件项目测试经验，具有移动互联网项目测试经验；
能独立完成各项测试任务，参与过中小型项目的测试工作；
计算机相关专业本科以上学历；

**Comment by Coder-liutianwei** [comment]
放屁，加班贼严重！兄弟们别信他的屁话

**Comment by zhangalonga** [comment]
@Coder-liutianwei你是东方头条的？我以前也拿过你们的offer,每个面试官都问我能不能接受加班，拿了offer之后告诉我每天要加班到10点，一个小时15块钱，好在阅文也是个上市公司，比单纯模仿今日头条的你司好吧，你们的猫扑技术部也是做小说的吧，做的怎么样啊
