### ISSUE TITLE
上海浦东央企招聘

### ISSUE THREAD

**Issue by jscrapy** [996icu/996.ICU#1017]
中国电信天翼云计算有限公司-上海研发中心招聘各类人才。

- UED
- 前端开发
- 大数据运维
- AI工程师
- java架构师
- python高级开发
- 大数据平台开发

云计算国家队，期待您的到来。互联网待遇+央企福利，不加班，弹性工作。
不来勿喷。 欢迎骚扰 球球： 328233430

**Comment by zhengzhihust** [comment]
+1

**Comment by jscrapy** [comment]
别让好贴沉了，早日脱离互联网苦海。

**Comment by shiorifujisaki** [comment]
+1 Mark

**Comment by jscrapy** [comment]
发一个高端职位，薪资不设限。好贴不要沉。。。。。。。。

## 职位描述
1、负责公司大数据相关产品的整体架构设计，结合公司实际业务情况进行技术选型及大数据战略规划（离线、实时计算）；
2、对大数据产品不断进行分析及优化，提升系统的性能及数据处理能力；
3、负责公共服务和基础组件的架构设计和开发；
4、解决高并发，高可用性等关键问题；

## 任职要求：
1、3年以上的架构设计经验，5年以上JAVA项目开发经验，985院校计算机相关专业本科以上学历。
2、对基于Hadoop的大数据体系有深入认识，具备相关产品（Hadoop、Hive、HBase、Pig、Sqoop、Spark、storm等）项目应用研发经验;
3、熟悉整个大数据的完整处理流程，包括各种数据源的数据的采集、清洗、预处理、存储、分析挖据、机器学习和数据可视化;
4、从事过用户日志挖掘分析、用户画像、反欺诈交易、风控模型等大数据应用产品架构设计和研发经验优先考虑;
5、精通并熟练使用多种JAVA开源框架，如Spring、SpringBoot、Spring MVC 、SpringCloud、MyBatis等；
6、熟悉Linux开发环境，对代码有强烈质量意识。研究过JVM调优、缓存、分布式系统、消息队列等技术。视野开阔，对前沿技术有持续跟踪；
7、责任心强，具备独立分析和解决问题的能力，做事有条理，有较好的组织、协调能力及团队合作意识，具备优秀的沟通能力；
8、有大型互联网项目架构、优化经验优先；
9、有产品思维；

**Comment by 942bc** [comment]
什么？不加班？？？不加班可能吗

**Comment by jscrapy** [comment]
@942bc

> 什么？不加班？？？不加班可能吗

国企不加班，加班出人命是政治问题。

**Comment by Gan-Jason** [comment]
> 中国电信天翼云计算有限公司-上海研发中心招聘各类人才。
> 
> * UED
> * 前端开发
> * 大数据运维
> * AI工程师
> * java架构师
> * python高级开发
> * 大数据平台开发
> 
> 云计算国家队，期待您的到来。互联网待遇+央企福利，不加班，弹性工作。
> 不来勿喷。 欢迎骚扰 球球： 328233430

请问收应届生吗？

**Comment by jscrapy** [comment]
@Gan-Jason  应届生是每年10月左右统一招聘的。所以现在不招收应届生。

**Comment by shiorifujisaki** [comment]
> @942bc
> 
> > 什么？不加班？？？不加班可能吗
> 
> 国企不加班，加班出人命是政治问题。

加个wx呗？ MTc3MjEzNDkzNjM=

**Comment by jscrapy** [comment]
@shiorifujisaki 177***4**63  没搜到这个人啊

**Comment by shiorifujisaki** [comment]
> @shiorifujisaki 177* * *4 * * 63 没搜到这个人啊

卧槽，我自己也搜不到了.....

**Comment by LRL-A** [comment]
【外企CTO 岗位】澳大利亚科技独角兽！十亿美金市值，中国区急招CTO，全球1000人，目前北京团队30+人，预计年底100人。
需求：
1.技术语言不限，CTO 可以是后台开发也可以是前端开发，目前后端主要java
2.coding能力强，面试有上机测试（大部分google，facebook背景）
 3.英文无障碍沟通，cto需要统筹协调北京悉尼工作
职级对应阿里p8，技术比例大于管理比例
👏欢迎自荐推荐，加微信13501125963详聊

**Comment by jscrapy** [comment]
@LRL-A 大哥为了国家，请把人才留给我。
