### ISSUE TITLE
996，工资到位，不会抱怨。

### ISSUE THREAD

**Issue by quan01994** [996icu/996.ICU#105]
````
工作只是为了钱，钱到位，一切都好说。
````

**Comment by SongJeen** [comment]
当你生病了，你就知道钱也不是万能的

**Comment by fuhuoyeyou** [comment]
兄弟，身体是革命的本钱啊，钱再到位都来不及

**Comment by Sakuraezra** [comment]
那你觉得开多少

**Comment by YuHang0121151624** [comment]
生活不是只有钱和工作啊

**Comment by xieao100** [comment]
钱给多少算是到位？北京一个月给我5w 我就可以接受996

**Comment by Sakuraezra** [comment]
你什么岗位 ，工作时间，一个月5W

**Comment by mela93** [comment]
给你10个亿买你一条命你愿意吗？不愿意？是钱没到位吗？

> 生活不是只有钱和工作啊

赞同这位老哥的，生活不是只有钱和工作啊

**Comment by quan01994** [comment]
@mela93  确实愿意啊。现在谁能一生打工能赚到10亿？现在阶级固化越来越严重。如果家族没爬上去，就只能吃屁。

**Comment by quan01994** [comment]
我打工，只是为了活着。
996，我不反对，只要付出能得到应有的回报。
也不必说什么健康，诗和远方。
我已经淡了。

如果有人抬杠说开出10亿买我去死，
可以啊。我唯一的要求就是安乐死，
我相信我的家庭如果拥有了这10亿能过得比现在好的多。
至少财务自由了。
