### ISSUE TITLE
替一个朋友找一个程序员男朋友，不要求有车有房，活好就行

### ISSUE THREAD

**Issue by zhengzhihust** [996icu/996.ICU#1086]
1、本科及以上学历，计算机、软件等相关专业，年龄25-30岁之间，5年以上Java开发经验；

2、Java基础扎实，熟练掌握SpringMVC、SringBoot、MyBatis、Shiro、Thymeleaf等常用开发技术；

3、精通主流数据（MySQL、SQL  Server、Oracle等），对SQL优化有丰富的经验；

4、有Java串口编程经验，具备网络通信接口编程经验；

5、能独立搭建前后端开发框架，有能力独立主导项目的技术开发工作；

6、掌握Linux操作系统，熟悉shell的使用；

7、熟悉软件技术文档的编写，具备良好的文档编辑习惯和代码书写规范，具有良好的沟通与表达力；

8、有良好的编码风格，具备良好的团队精神和责任心；

9、有大数据开发经验优先。

**Comment by wangont** [comment]
点进来真的是信了你的邪

**Comment by baymaxLove** [comment]
JD 写的可以 兄弟

**Comment by ZUOXIANGE** [comment]
虽然我已经猜到了,但还是忍不住点了进来

**Comment by shiorifujisaki** [comment]
我其实想来吐槽找996之后怎么谈的问题.....世界套路深

**Comment by jaddqiu** [comment]
套路太深，不得人心

**Comment by 21cm** [comment]
wechat : czy1518025518
location ：jiangxi ganzhou
age ：22
