### ISSUE TITLE
你觉得晚上加班效率高么

### ISSUE THREAD

**Issue by LeoWang1991** [996icu/996.ICU#1180]
emmm...如果是临时上线，加需求修bug，那另说。
如果是这种氛围，哎。。。觉得晚上效率特别低，不太想写代码的节奏
虽然现在上班晚十点半样子，基本上早上到公司稍微弄点东西就中午了。然后午休差不多到一点半两点开始正式上班。
挺怀念以前朝九晚六打卡了，东西内容工作量虽然差也不多，每天晚上九点下班十点到家超级影响生活质量。吐槽下

**Comment by babyshen** [comment]
晚上效率比白天高

**Comment by yunshuipiao** [comment]
@babyshen  那是因为白天被各种事情打扰了

**Comment by Cuihongsen** [comment]
过了9点，特别容易犯低级错误

**Comment by okou19900722** [comment]
高啊，反正晚上要搞，白天就打了一天的鱼

**Comment by yunshuipiao** [comment]
对，晚上写bug
