### ISSUE TITLE
软件行业从创意型产业变成了劳动密集型产业了吗

### ISSUE THREAD

**Issue by 845629143** [996icu/996.ICU#1181]
怎么感觉都是大环境的问题
大环境导致国内无论BAT这些顶级公司又或者京东美团网易这些二线公司，大家做的主要都是针对国内市场的业务。几乎每家都是垄断最少一个行业，或在一个行业内有顶级话语权。
缺乏国际竞争力，大家就在一个水池子里折腾，折腾久了难免会起一些幺蛾子。
慢慢的，就会忽略企业的本质。反正垄断行业也不需要啥竞争力，谁起来灭谁。 也不会让小公司去颠覆了自己的存在，能打压就打压，能挖就挖，能拆就拆。实在不行的话，做你们的投资人。反正无论如何不能让可以威胁到自己的存在长久的生存下去。
这样慢慢的，可以把控国家社会整体命脉的企业越来越多，垄断的企业越来越多。那么他们就可以为了利润而忽视一切人间的法律法规道德伦理，成为了社会主义制度最憎恨的资本家。

推翻996，反对万恶资本家。

**Comment by xiaofei-dev** [comment]
其实很多加班是加给上司看的而已！

**Comment by Hanggi** [comment]
其实主要是因为过去需要门槛的软件服务，现在变得门槛低了很多，有更多新人涌入了这个行业，而这些人又往往缺少扎实的理论基础，所以慢慢的就会给人一种劳动密集的感觉了。
