### ISSUE TITLE
未执行996 但是拖欠工资让人想杀人

### ISSUE THREAD

**Issue by CatyVon** [996icu/996.ICU#12006]
之前待的公司  虽然人少  但是公司部门  领导管理  以及所有的福利啥的都没得说  地方也是办公楼  硬件软件都不差  因为个人结婚生子一些原因没办法就离职了  而现在所在的公司  说是公司简直是抬举太多  小作坊一个  领导层鸡毛都不懂  啥都敢接  啥都敢答应   签了合同想起找开发问   石油公司的气体检测自动化设备能做么  得多钱  得多久  还有不借助第三方自行做一个直播出来能做么  得多钱  得多久  我做尼玛呀  都没看看自己的实力  居民小区租的房  工资还特么隔月发  现在都3月快4月了  才特么把1月的结清  我才来半年不到  麻痹的人事换了4个  哪一个不是知道这破公司的老底儿就闪人的  老子没走人都算给你脸了  现在在外面扯了虎皮装了逼  接着懵逼了  知道谁才是具体执行人了   客气的给你说  咱没那实力做不了  还不信  爱咋咋地   现在我就是磨洋工   看你啥时候完蛋  好了  吐槽结束  也祝愿各位同行工作都能顺顺心心   少些傻逼挡路  生活美满  家庭幸福

**Comment by busclass** [comment]
+1
