### ISSUE TITLE
我叫云天风，是一名浙江大学计算机系的博士，曾就职于阿里巴巴淘宝事业部……

### ISSUE THREAD

**Issue by itdakashuo** [996icu/996.ICU#12210]
我叫云天风，

是一名浙江大学计算机系的博士，

曾就职于阿里巴巴淘宝事业部。

2019年希望组建这样一个公益性社群方便我们在这样一群在科技领域探索前行的人们更好的交流。

《零一公社》用跳跃的字符表达梦想。

用技术构建未来，我们的梦想是星辰大海，欢迎加入！

加助理妹子v~x：ITDKS5，拉你进《零一公社》

**Comment by Chowing** [comment]
本科生不敢说话。。。

**Comment by itdakashuo** [comment]
> 本科生不敢说话。。。

本科生才是技术人才
