### ISSUE TITLE
我一直思考，为什么很多人不敢离开不公平待遇的公司，个人总结以下几点

### ISSUE THREAD

**Issue by cq0206** [996icu/996.ICU#12250]
我一直思考，为什么很多人不敢离开不公平待遇的公司，个人总结以下几点
1、贷款债务：房贷、车贷、家庭，这是很多人透支明天的代价。多少车奴卡奴房奴，为了赎身所以被迫接受老板的压迫。
2、健康：我前公司有个同事，他有拼搏的心，但是腰不行，所以他不敢外出太远，怕的是对身体造成更加严重的伤害。
这是我目前看到的，也是我的个人观念
补充一下，我已经换了公司了，虽然还在试用期，但感觉不错。
新公司的好不好以后再说。
但在此我想给需要挣脱996的朋友们一句话

跳槽吧，多少钱都买不回你的健康！
对害怕996的朋友们说：争取多点经济自由吧，不需要的请放手!

我的公众号，分享技术知识
![image](https://user-images.githubusercontent.com/40629147/55142357-5f19df80-5177-11e9-9fc7-ef27c42a7490.png)

**Comment by inlics** [comment]
补充一个前同事没离开公司的理由：跟着老板干了一两年干出感情来了（PS：他是男的，老板也是男的）

**Comment by cq0206** [comment]
学好

**Comment by cq0206** [comment]
技术要好
