### ISSUE TITLE
进来打卡，紧急集合！紧急集合！

### ISSUE THREAD

**Issue by Renfrs** [996icu/996.ICU#12302]
![image](https://user-images.githubusercontent.com/24970949/55142443-9ab4a980-5177-11e9-9620-f9e16e504664.png)

**Comment by Renfrs** [comment]
入群签到。

**Comment by Renfrs** [comment]
技术大佬群

**Comment by Renfrs** [comment]
无广告，纯技术讨论！

**Comment by xianfengoby** [comment]
大佬们 ，我来打卡了。
