### ISSUE TITLE
海淀某公司上睡眠仓了，通宵加班指日可待

### ISSUE THREAD

**Issue by zhengzhihust** [996icu/996.ICU#1244]
![WechatIMG18](https://user-images.githubusercontent.com/8281234/55075144-23c2d680-50cd-11e9-9aa7-1321cbc57168.jpeg)

**Comment by zsb19920222** [comment]
666666666

**Comment by iamflowerdog** [comment]
昨天加班到9点半，领导来了句今天别走了吧，公司有睡袋
