### ISSUE TITLE
打广告的亲🐴今晚biss 傻逼培训班广告

### ISSUE THREAD

**Issue by Liumxv** [996icu/996.ICU#12729]
NM$L

**Comment by ev01ing** [comment]
应该这样，我们去他们的博客骂死他们，反正有他们的github的地址

**Comment by Liumxv** [comment]
> 应该这样，我们去他们的博客骂死他们，反正有他们的github的地址

妈了个逼的看到这群培训班广告就来气

嗨呀 越看越气
