### ISSUE TITLE
打广告的有病吧

### ISSUE THREAD

**Issue by keepongjl** [996icu/996.ICU#13194]
看到你们这群丧心病狂打广告的，国内这乌烟瘴气的环境真的可以理解了，本以为程序员文化智商水平高了，还是有那么多智障，真是服了

**Comment by Liumxv** [comment]
都是傻批培训班 

新注册的号来发的  

亲🐴biss

**Comment by lixiaoqiang** [comment]
细心留意一下打广告的都是什么就了解了
什么Go语言，什么Python,什么Tensorflow
一看就是踩风头做培训的

**Comment by luckyuns** [comment]
乌烟瘴气,很贴切。
