### ISSUE TITLE
996就觉得累，我们创业的哪个不是997！？

### ISSUE THREAD

**Issue by synwith** [996icu/996.ICU#1343]
我看你在工作时间在QQ技术群聊得欢呀~

**Comment by NooooWorries** [comment]
创业997是你自愿的，程序员996并非自愿，而是集体无意识以及KPI威胁。

**Comment by shiorifujisaki** [comment]
创业有各种小钱钱

**Comment by baymaxLove** [comment]
get out

**Comment by T-mans** [comment]
创业为了自己的,我创业的时候也没说啥啊,但是的确是拼上性命了啊,对身体并不好

**Comment by codeliu6572** [comment]
你创业成功和员工关系不大吧，你又不舍得分钱，不要急着否认。

**Comment by likecreep** [comment]
创业的逻辑就这个水平？

**Comment by synwith** [comment]
都是吃不了苦，活该打工一辈子。

**Comment by nfanaa19940122** [comment]
不是累不累的问题，创业是自愿的，不违反中华人民共和国劳动法

**Comment by NooooWorries** [comment]
> 都是吃不了苦，活该打工一辈子。

我吃的了为自己的苦，我吃不了牺牲自己给老板赚钱还被老板压榨的苦

**Comment by LanWH** [comment]
自愿和强奸了解一下

**Comment by codeliu6572** [comment]
> 都是吃不了苦，活该打工一辈子。

老哥你这逻辑神了，你只要钱管够，豁出命跟你一起创业的都有，或者说创业成功，你分多少红给跟着你的人，有几个做到的，你只要做到一样，大把的人9127的干

**Comment by eacryo** [comment]
你他妈少在这里妖言惑众

**Comment by Reisenudong** [comment]
> 你他妈少在这里妖言惑众

我已经联系微软总部，走着瞧

**Comment by mzc532** [comment]
滚你🐎的

**Comment by Codekiller-Li** [comment]
资本家：加点班怎么了，我们都是997
劳动者：g u n

**Comment by yuejinzhao** [comment]
你🐴死了 资本家gck

**Comment by jackzhangzedong** [comment]
这么说吧 我家里父母是茶农，去年的三月底到清明前采茶季，我在家里帮忙 ，差不多半个月的时间里 ，我每天只睡三个小时，那段时间瘦了将近20斤，但是我没抱怨，因为我知道，这一季茶叶行情好的话，家里下半年日子就会过得很舒服，我爸妈天天在家里玩就可以了。

**Comment by PeterLees** [comment]
不要绑架所有人，我们在国外工作，公司就得照这法律办事，我们老外同事的说法就很有道理，你奋斗是为了你自己，为什么要别人像你们一样，大家都是打工赚钱的，你的理想和我们真的没多大关系！
不要用吃不了苦来作为理由dis大家，不然要法律干什么？国家规定几小时工作制你就得执行，你们的理想也不是法外之地！ok？
