### ISSUE TITLE
 【Go语言学习交流群】微信群 高素质学习交流群 喷子勿扰 纯技术交流学习  不收费 不收费 不收费<br/>  【全国程序员联盟三群】微信群 高素质交流群 纯技术交流  不存在收费 也不赚钱 快来快来！！！<br/>  【前端开发联盟】微信群 前端开发的小伙伴儿一起来 纯技术交流 不存在收费 有前端小姐姐<br/>  【免费资源分享群】QQ群 各种免费技术资源分享 高素质交流群 可以扫码收藏啊

### ISSUE THREAD

**Issue by kuaidjun** [996icu/996.ICU#13654]
![image](https://user-images.githubusercontent.com/28185258/55145428-a2774c80-517d-11e9-9510-3f7365346b7e.png)
![image](https://user-images.githubusercontent.com/28185258/55145431-a4d9a680-517d-11e9-8eb4-5d778f676f59.png)
![image](https://user-images.githubusercontent.com/28185258/55145433-a60ad380-517d-11e9-9351-35ab6b362a15.png)
![image](https://user-images.githubusercontent.com/28185258/55145444-a86d2d80-517d-11e9-81ed-14dd7b128706.png)
![image](https://user-images.githubusercontent.com/28185258/55145452-aacf8780-517d-11e9-92ee-a64784c1c736.png)

**Comment by zhiyangdata** [comment]
你妈都出殡了还有心思发广告

**Comment by zhiyangdata** [comment]
你妈都出殡了还有心思发广告
