### ISSUE TITLE
【天猫前端团队招聘】绝无仅有，拒绝996 

### ISSUE THREAD

**Issue by MercyLong** [996icu/996.ICU#13657]
专业招聘辅导，天猫直通车，带你走向人生巅峰。

招聘邮箱：jacky.lx@alibaba-inc.com
招聘微信：woaiymmdl

团队介绍
1.业务领域 —— 建设天猫从消费者导购到品牌商家系统全链路各类产品，体验每年全球瞩目双11狂欢节，加入尽情施展才华的舞台；

2.技术驱动 —— 从极致的Mobile体验、前端工程化开发、企业级中台应用、可视化编程、3D/AR创新交互，到大规模NodeJS应用等等，拥有足够的挑战及机遇；

职位描述
1.精通各种前端技术（包括HTML/CSS/JavaScript等），熟悉ES6语法，具备跨终端（Mobile+PC）的前端开发能力，熟悉网络协议（HTTP/SSL），熟悉常见安全问题和对策；

2.熟悉前端工程化与模块化开发，并有实践经验（如gulp/webpack、VueJS/React等）；

3.至少熟悉一门非前端的语言（如NodeJS/Java/PHP/C/C++/Python/Ruby等），并有实践经验；

4.对前端技术有持续的热情，良好的团队协作能力，提升团队研发效率，实现极致性能，通过创新交互优化产品体验；

5.加分项（满足其一即可）：具备客户端能力或者Native&Web技术融合经验；熟悉Canvas动效&WebGL3D以及各种传感器技术；复杂企业后台应用开发经验；数据可视化产品设计开发经验；大规模/高负载场景下NodeJS应用开发、运维经验；良好的算法背景，对机器学习有研究和项目实施经验；有独立的开源项目或者参与知名开源项目经验；团队管理能力；英语沟通能力；

**Comment by 287232202** [comment]
信了你的邪，你个糟老头，坏的狠~~~

**Comment by xue8710** [comment]
我信你个鬼

**Comment by fh332393900** [comment]
```
信你个锤子
```

**Comment by zhangsx123** [comment]
我八信

**Comment by wonderfulMan** [comment]
信你个鬼，去了阿里有休息？
