### ISSUE TITLE
一群二货真的丢人丢到国外了。还不知所措！还在这起哄

### ISSUE THREAD

**Issue by nligo** [996icu/996.ICU#13920]

**Comment by Zhao-Jie-honour** [comment]
没懂标题的意思?是说996不该反抗  还是说只是在网上聊这个事情没有意义?

**Comment by nligo** [comment]
> 没懂标题的意思?是说996不该反抗 还是说只是在网上聊这个事情没有意义?

在网上谈论这个事并没有意义。更何况还是在github中？？？外人怎么看？这么多星星只是为了说自己国家的996制度？如果有怨言可以去走法律途径竟在这里瞎胡闹。早上居然还贴出二维码拉赞助？？？
