### ISSUE TITLE
【技术人成长】公众号，分享技术人成长的技法、心法，在智能时代不忘思考！

### ISSUE THREAD

**Issue by flyforfreedom** [996icu/996.ICU#13960]
![qrcode_for_techmangrow](https://user-images.githubusercontent.com/3615229/55146500-ac01b400-517f-11e9-87f5-80b1f430bd10.jpg)

**Comment by future-c** [comment]
你妈都出殡了还有心思发广告

**Comment by zackOta** [comment]
你妈都出殡了还有心思发广告

**Comment by CaffreySun** [comment]
你妈都出殡了还有心思发广告
