### ISSUE TITLE
我们公司招人，招人，招人，不推崇加班，不是 996，欢迎来简历。

### ISSUE THREAD

**Issue by phodal** [996icu/996.ICU#144]
如题。

欢迎来简历：h@phodal.com

**不缺钱的，欢迎来简历。你们不就是为了钱去 996 吗，哈哈**

**不缺钱的，欢迎来简历。你们不就是为了钱去 996 吗，哈哈**

**不缺钱的，欢迎来简历。你们不就是为了钱去 996 吗，哈哈**

**Comment by LordwithGlory** [comment]
大哥打的一手好广告~

**Comment by Thekingofweb** [comment]
然后入职发现真的不是996，因为是997

**Comment by cocos3ds** [comment]
有啥要求

**Comment by LordwithGlory** [comment]
https://www.thoughtworks.com/cn/careers/seniordev#open-roles 放个这个公司招聘链接

**Comment by ivanberry** [comment]
大P，这个项目都有招聘啊

**Comment by HCH2CHO** [comment]
ThoughtWorks啊

**Comment by simpletrain** [comment]
峰达打得一手好广告

**Comment by xbini** [comment]
ThoughtWorks啊

**Comment by YuanQGit** [comment]
不会是007吧

**Comment by jiaen188** [comment]
优秀啊

**Comment by shenliuming** [comment]
你牛逼，这个热度都可以蹭

**Comment by kuangzhongwei** [comment]
坐标长沙，欢迎来撩
 https://www.lagou.com/jobs/5741291.html?source=pl&i=pl-0

**Comment by GhostRiderLi** [comment]
不是996 而是007么(手动滑稽)？

**Comment by noyidoit** [comment]
人才啊

**Comment by ALEXKINGS** [comment]
...
