### ISSUE TITLE
这只是程序员们徒劳的泄愤

### ISSUE THREAD

**Issue by xumengxuan** [996icu/996.ICU#14571]
这是程序员们徒劳的泄愤，不敢和公司争取也不敢离职，只敢当屏幕后点赞的键盘侠。

个人的 Star 按钮令人跃跃欲试，仿佛按下鼠标的那一刻你就夺回了人生的控制权。

然而都是假象，明天他们还是一个秃头的996程序员。

-- 鲁迅

来自某群！

**Comment by 303snowing** [comment]
# 已提交离职申请

**Comment by qq1012827513** [comment]
笑死 自己选的996上网上抱怨 我是先下班了 ~

**Comment by muyiyjm** [comment]
下周离职申请
