### ISSUE TITLE
GitHub WebHook 自动脚本:https://github.com/ser163/hubbot 大家来个star

### ISSUE THREAD

**Issue by ser163** [996icu/996.ICU#14688]
GitHub WebHook 自动脚本:https://github.com/ser163/hubbot 大家来个star

**Comment by nongshanie** [comment]
来了老弟

**Comment by Magnesium2015** [comment]
广告发一次 妈被轮一次

**Comment by ser163** [comment]
> 广告发一次 妈被轮一次

当然要用自己的方式来抵制.issues灌水就是最好的抵制.这是在刷量.不能让热度降低,你懂吗?
