### ISSUE TITLE
生而为人，不是机器，希望能重视工作和生活平衡，工作是为了更好的生活！

### ISSUE THREAD

**Issue by MisssssCathy** [996icu/996.ICU#1483]
专业猎头     突破职业瓶颈       规划职业生涯 
专注于互联网中高端技术（iOS&Android&Java&PHP&Python&Ruby&node.js&前端&算法&大数据）等职位招聘 
地点：硅谷 纽约 阿姆斯特丹 杭州 北京 上海 广州 深圳等 
有多年工程师背景的猎头，更懂候选人，服务Snapchat，Farfetch，BAT阿里巴巴，腾讯等，负责网易，今日头条等行业巨头企业招聘。同时筛选一些发展迅速，优质靠谱的创业公司，为如Agora，流利说等人才猎寻。和PE/VC（IDG/经纬/GGV等）合作密切，在招聘投资人/分析师同时，帮助他们Portfolio的一些项目独家招聘。　　
微信：Cathy-LYY  电话：13621911598  Mail: cathy.liu@gitalent.cn

**Comment by Opdoop** [comment]
活捉一名真实猎头 ，这位猎头会收到怎样的 comment 呢？

**Comment by MisssssCathy** [comment]
> 活捉一名真实猎头 ，这位猎头会收到怎样的 comment 呢？

嘻嘻，欢迎找我聊天呀~
