### ISSUE TITLE
【百度招聘】移动客户端部_NLP高级工程师

### ISSUE THREAD

**Issue by yilustrater** [996icu/996.ICU#1490]
工作地点：上海-百度研发中心

工作职责

-参与输入法产品核心算法的研发 

-对中文语言模型及相关算法进行优化改进 

-根据业务需求，给出有效的优化解决方案 

-研发和改进算法，并用于解决实际问题

任职资格

-在工程领域至少2年以上C/C++经验 

-对数据结构与算法有较深刻的理解 

-熟练掌握自然语言处理领域的基础理论和方法，并有一定的相关研究或项目经验 

-熟悉NLP领域当前热点和前沿技术，对NLP有完整的、系统的认识 

-优秀的分析问题和解决问题的能力，对解决具有挑战性问题充满激情

简历投递：lishuwen@baidu.com

**Comment by zzjian** [comment]
666

**Comment by liweiDiao** [comment]
666

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ChrisChou2018** [comment]
996吗996滚

**Comment by tanqizhi** [comment]
绝了

**Comment by TommyZJL** [comment]
大家都给我让开。

**Comment by liuruogu** [comment]
niu B

**Comment by JoeCqupt** [comment]
斯~~  绝了

**Comment by Cheng-Lun** [comment]
556

**Comment by yilustrater** [comment]
> 996吗996滚

**Comment by shliang0603** [comment]
是996吗

**Comment by shliang0603** [comment]
如果是996.ICU ,请通知我

**Comment by shliang0603** [comment]
如果是996.ICU ,请通知我
