### ISSUE TITLE
强烈吐槽【【喜马拉雅FM】】这家公司！！！

### ISSUE THREAD

**Issue by dannyhuhu** [996icu/996.ICU#14956]
喜马拉雅坐标在浦东张江高科，对外宣传是4.7亿用户，目前是音频独角兽的地位，但是实际上~~！！！
不仅可以让你操刀4.7亿用户独角兽平台核心业务模块建设；
还有屡获殊荣的精英团队，可以与最聪明的小伙伴为伍；
优秀的晋升机制，指数型的业务增长；
相比于上面几点，顶配的设备、好吃到爆的下午茶、免费的员工餐、定期奢华出游以及节假日福利等等都只能算基本配置~~
996??? 那是不可能的！！
想加入吗？
danny.hu@ximalaya.com
【技术招聘，欢迎投递】
><  ><  ><  ><  ><  ><  ><  
Java/iOS/前端/Android/算法/NLP都有坑~~

**Comment by xlhandsome** [comment]
吐槽的太好了，有招前端吗，

**Comment by DenisWW** [comment]
招什么岗位啊

**Comment by dannyhuhu** [comment]
> 吐槽的太好了，有招前端吗，

有呀~~

**Comment by dannyhuhu** [comment]
> 招什么岗位啊

Java/iOS/前端/Android/算法/NLP都有坑~~
