### ISSUE TITLE
【百度招聘】移动客户端部_Android高级研发工程师

### ISSUE THREAD

**Issue by yilustrater** [996icu/996.ICU#1497]
工作地点：上海-百度研发中心

工作职责
- 负责输入法、语音等产品的Android客户端研发
- 负责新产品的可行性研究
- 负责新产品相关技术方案的研究和技术选型
- 研究新兴技术，满足产品需求

任职资格
-本科或以上学历，计算机软件、通讯相关专业优先
-2年以上Android开发经验
-有良好的架构设计能力，熟练运用设计模式，熟悉常见的网络协议
-熟练掌握 java 语法 ，理解Java线程模型
-对移动产品有较强的敏感度和热情

简历投递邮箱：lishuwen@baidu.com

**Comment by linuxwind** [comment]
....

**Comment by Cheng-Lun** [comment]
。。。

**Comment by ifgyong** [comment]
招聘都过来了，最近iOS有坑吗？

**Comment by yilustrater** [comment]
> 招聘都过来了，最近的iOS有坑吗？

安卓上海的坑，了解一下

**Comment by suxingdian1992** [comment]
嘻嘻，996么?

**Comment by LoadingZhang** [comment]
不是996不去

**Comment by ifgyong** [comment]
不是 9 12 7 不去。
