### ISSUE TITLE
澳洲程序员每周工作38小时 每年20天年假 + 所有公休假不和周末重叠

### ISSUE THREAD

**Issue by johnniu1** [996icu/996.ICU#14973]

**Comment by chenlei2014** [comment]
万恶的资本主义社会

**Comment by GitHeP** [comment]
那么问题来了我怎么才能去呢

**Comment by JasonSpeak** [comment]
那么请问在哪里可以申请到呢？

**Comment by xlhandsome** [comment]
严重挑衅

**Comment by johnniu1** [comment]
> 那么问题来了我怎么才能去呢

https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189

**Comment by johnniu1** [comment]
> 那么请问在哪里可以申请到呢？

https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-regional-provisional-489

和上面的都可以

**Comment by johnniu1** [comment]
> 万恶的资本主义社会

资本主义真香
