### ISSUE TITLE
拒绝996，魔都程序猿和程序媛看过来，上市外企10-7准点走，一点不加班

### ISSUE THREAD

**Issue by nancy1222** [996icu/996.ICU#14992]
上市外企freewheel：
招聘职位：Java，PHP，C++         level：资深和leader职级。现金+期权，绝对不加班
准上市外企grab：
招聘职位：技术栈不限，后期可以转go即可。level：资深和leader职级
因为是外企，所以对leader职级会有口语要求。其他直接看懂文档即可。
PS：不想996的魔都筒子们看过来，请来电来函垂询查询问询。
企鹅号：851588121

**Comment by nancy1222** [comment]
欢迎qiuqiu一下。

**Comment by luoyueming** [comment]
程序员太惨了 写了篇关于前端技术的文章 都没有人点赞 看见的朋友去给点个赞吧 https://www.kancloud.cn/lemon-m/js-html-css

**Comment by cobola** [comment]
搭车 国企 9点上班 5点下班   招前端
