### ISSUE TITLE
上海招商银行信用卡中心绝对良心招聘

### ISSUE THREAD

**Issue by zhangsx123** [996icu/996.ICU#15065]
上海招商银行信用卡中心没有996，只有955，附内推链接
https://cmbjob.ccc.cmbchina.com/positionclass.html?refereeId=6839c4a4-2182-40bc-bae3-898a7d343fa9&refereeCode=674441&deptId=003&recruitType=1

**Comment by mingen-pan** [comment]
那你怎么还在公司发帖？

**Comment by De-Light** [comment]
哈哈哈哈哈哈哈太真实了
