### ISSUE TITLE
引用《毛泽东选集》第二卷，学习一下毛泽东对斗争的看法

### ISSUE THREAD

**Issue by NewConn** [996icu/996.ICU#15061]
咱们学习一下毛泽东对斗争的看法
以下节选自《毛泽东选集》第二卷
> （一）目前的政治形势是：（1）日本帝国主义受了中国抗日战争的严重打击，已经无力再作大规模的军事进攻，因而敌我形势已处在战略相持阶段中；但敌人仍然坚持其灭亡中国的基本政策，并用破坏抗日统一战线、加紧敌后“扫荡”、加紧经济侵略等方法，实行这种政策。（2）英法在东方的地位因欧战削弱，美国则继续采取坐山观虎斗的政策，故东方慕尼黑会议暂时无召集的可能。（3）苏联的对外政策取得了新的胜利，对中国抗战依然取积极援助政策。（4）亲日派大资产阶级早已彻底投降日本，准备傀儡登场。欧美派大资产阶级则尚能继续抗日，但其妥协倾向依然严重存在。他们采取两面政策，一面还要团结国民党以外的各派势力对付日本，一面却极力摧残各派势力，尤其尽力摧残共产党和进步势力。他们是抗日统一战线中的顽固派。（5）中间力量，包括中等资产阶级、开明绅士和地方实力派，因为他们和大地主大资产阶级的主要统治力量之间有矛盾，同时和工农阶级有矛盾，所以往往站在进步势力和顽固势力之间的中间立场。他们是抗日统一战线中的中间派。（6）共产党领导之下的无产阶级、农民和城市小资产阶级的进步力量，最近时期有一个大的发展，基本上已经奠定了抗日民主政权的根据地。他们在全国工人、农民和城市小资产阶级中的影响是很大的，在中间势力中亦有相当影响。在抗日战场上，共产党所抗击的日寇兵力，同国民党比较起来，几乎占到了同等的地位。他们是抗日统一战线中的进步派。　
> 　　以上就是目前中国的政治形势。在这种形势下，争取时局好转，克服时局逆转的可能性，还是存在的，中央二月一日的决定⑴是完全正确的。　
> 　　（二）抗日战争胜利的基本条件，是抗日统一战线的扩大和巩固。而要达此目的，必须采取发展进步势力、争取中间势力、反对顽固势力的策略，这是不可分离的三个环节，而以斗争为达到团结一切抗日势力的手段。在抗日统一战线时期中，斗争是团结的手段，团结是斗争的目的。以斗争求团结则团结存，以退让求团结则团结亡，这一真理，已经逐渐为党内同志们所了解。但不了解的依然还多，他们或者认为斗争会破裂统一战线，或者认为斗争可以无限制地使用，或者对于中间势力采取不正确的策略，或者对顽固势力有错误的认识，这些都是必须纠正的。　
> 　　（三）发展进步势力，就是发展无产阶级、农民阶级和城市小资产阶级的力量，就是放手扩大八路军新四军，就是广泛地创立抗日民主根据地，就是发展共产党的组织到全国，就是发展全国工人、农民、青年、妇女、儿童等等的民众运动，就是争取全国的知识分子，就是扩大争民主的宪政运动到广大人民中间去。只有一步一步地发展进步势力，才能阻止时局逆转，阻止投降和分裂，而为抗日胜利树立坚固不拔的基础。但是发展进步势力，是一个严重的斗争过程，不但须同日本帝国主义和汉奸作残酷的斗争，而且须同顽固派作残酷的斗争。因为对于发展进步势力，顽固派是反对的，中间派是怀疑的。如不同顽固派作坚决的斗争，并收到确实的成效，就不能抵抗顽固派的压迫，也不能消释中间派的怀疑，进步势力就无从发展。　
> 　　（四）争取中间势力，就是争取中等资产阶级，争取开明绅士，争取地方实力派。这是不同的三部分人，但都是目前时局中的中间派。中等资产阶级就是除了买办阶级即大资产阶级以外的民族资产阶级。他们虽然同工人有阶级矛盾，不赞成工人阶级的独立性；但他们在沦陷区受到日本帝国主义的压迫，在国民党统治下则受大地主大资产阶级的限制，因此他们还要抗日，并要争取自己的政治权力。在抗日问题上，他们赞成团结抗战；在争取政治权力问题上，他们赞成宪政运动，并企图利用进步派和顽固派之间的矛盾以达其目的。这一阶层，我们是必须争取的。开明绅士是地主阶级的左翼，即一部分带有资产阶级色彩的地主，他们的政治态度同中等资产阶级大略相同。他们虽然同农民有阶级矛盾，但他们同大地主大资产阶级亦有矛盾。他们不赞成顽固派，他们也想利用我们同顽固派的矛盾以达其政治上的目的。这一部分人，我们也决不可忽视，必须采取争取政策。地方实力派，包括有地盘的实力派和无地盘的杂牌军两种力量在内。他们虽然同进步势力有矛盾，但他们同现在国民党中央政府的损人利己的政策亦有矛盾，并想利用我们同顽固派的矛盾以达其政治上的目的。地方实力派的领导成分也多属大地主大资产阶级，因此他们在抗日战争中虽然有时表现进步，不久仍然反动起来；但又因为他们同国民党中央势力有矛盾，所以只要我们有正确的政策，他们是可能在我们同顽固派斗争时采取中立态度的。上述三部分中间势力，我们的政策都是争取他们。但这种争取政策，不但同争取农民和城市小资产阶级有区别，而且对于各部分中间势力也有区别。对于农民和城市小资产阶级，是当作基本同盟者去争取的；对于中间势力，则是当作反帝国主义的同盟者去争取的。中间势力中的中等资产阶级和开明绅士，可以同我们共同抗日，也可以同我们一道共同建立抗日民主政权，但他们害怕土地革命。在对顽固派的斗争中，其中有些人还可以在一定限度内参加，有些则可以保持善意的中立，有些则可以表示勉强的中立。地方实力派，则除共同抗日外，只能在对顽固派斗争时采取暂时的中立立场；他们是不愿同我们一道建立民主政权的，因为他们也是大地主大资产阶级。中间派的态度是容易动摇的，并且不可避免地要发生分化；我们应当针对着他们的动摇态度，向他们进行适当的说服和批评。　
> 　　争取中间势力是我们在抗日统一战线时期的极严重的任务，但是必须在一定条件下才可能完成这个任务。这些条件是：（1）我们有充足的力量；（2）尊重他们的利益；（3）我们对顽固派作坚决的斗争，并能一步一步地取得胜利。没有这些条件，中间势力就会动摇起来，或竟变为顽固派向我进攻的同盟军；因为顽固派也正在极力争取中间派，以便使我们陷于孤立。在中国，这种中间势力有很大的力量，往往可以成为我们同顽固派斗争时决定胜负的因素，因此，必须对他们采取十分慎重的态度。
> （五）顽固势力，目前就是大地主大资产阶级的势力。这些阶级，现在分为降日派和抗日派，以后还要逐渐分化。目前的大资产阶级抗日派，是和降日派有区别的。他们采取两面政策，一面尚在主张团结抗日，一面又执行摧残进步势力的极端反动政策，作为准备将来投降的步骤。因为他们还愿团结抗日，所以我们还有可能争取他们留在抗日统一战线里面，这种时间越长久越好。忽视这种争取政策，忽视同他们合作的政策，认为他们已经是事实上的投降派，已经就要举行反共战争了，这种意见是错误的。但又因为他们在全国普遍地执行摧残进步势力的反动政策，不实行革命三民主义这个共同纲领，还坚决反对我们实行这个纲领，坚决反对我们超越他们所许可的范围，即只让我们同他们一样实行消极抗战，并且企图同化我们，否则就加以思想上政治上军事上的压迫，所以我们又必须采取反抗他们这种反动政策的斗争策略，同他们作思想上政治上军事上的坚决斗争。这就是我们对付顽固派两面政策的革命的两面政策，这就是以斗争求团结的政策。如果我们能够在思想上提出正确的革命理论，对于他们的反革命理论给以坚决的打击；如果我们在政治上采取适合时宜的策略步骤，对于他们的反共反进步政策给以坚决的打击；如果我们采取适当的军事步骤，对于他们的军事进攻给以坚决的打击；那末，就有可能限制他们实施反动政策的范围，就有可能逼迫他们承认进步势力的地位，就有可能发展进步势力，争取中间势力，而使他们陷于孤立。同时，也就有可能争取还愿抗日的顽固派，延长其留在抗日统一战线中的时间，就有可能避免如同过去那样的大内战。所以，在抗日统一战线时期中，同顽固派的斗争，不但是为了防御他们的进攻，以便保护进步势力不受损失，并使进步势力继续发展；同时，还为了延长他们抗日的时间，并保持我们同他们的合作，避免大内战的发生。如果没有斗争，进步势力就会被顽固势力消灭，统一战线就不能存在，顽固派对敌投降就会没有阻力，内战也就会发生了。所以，同顽固派斗争，是团结一切抗日力量、争取时局好转、避免大规模内战的不可缺少的手段，这一真理，已被一切经验证明了。　
> 　　但在抗日统一战线时期，同顽固派斗争，必须注意下列几项原则。第一是自卫原则。人不犯我，我不犯人，人若犯我，我必犯人。这就是说，决不可无故进攻人家，也决不可在被人家攻击时不予还击。这就是斗争的防御性。对于顽固派的军事进攻，必须坚决、彻底、干净、全部地消灭之。第二是胜利原则。不斗则已，斗则必胜，决不可举行无计划无准备无把握的斗争。应懂得利用顽固派的矛盾，决不可同时打击许多顽固派，应择其最反动者首先打击之。这就是斗争的局部性。第三是休战原则。在一个时期内把顽固派的进攻打退之后，在他们没有举行新的进攻之前，我们应该适可而止，使这一斗争告一段落。在接着的一个时期中，双方实行休战。这时，我们应该主动地又同顽固派讲团结，在对方同意之下，和他们订立和平协定。决不可无止境地每日每时地斗下去，决不可被胜利冲昏自己的头脑。这就是每一斗争的暂时性。在他们举行新的进攻之时，我们才又用新的斗争对待之。这三个原则，换一句话来讲，就是“有理”，“有利”，“有节”。坚持这种有理、有利、有节的斗争，就能发展进步势力，争取中间势力，孤立顽固派，并使顽固派尔后不敢轻易向我们进攻，不敢轻易同敌人妥协，不敢轻易举行大内战。这样，就有争取时局走向好转的可能。　
> 　　（六）国民党是一个由复杂成分组成的党，其中有顽固派，也有中间派，也有进步派，整个国民党并不就等于顽固派。因为国民党中央颁布《限制异党活动办法》⑵等等反革命磨擦法令，并实行动员他们一切力量进行普遍全国的思想上政治上军事上的反革命磨擦，有些人就以为整个国民党都是顽固派，这种看法是错误的。现在的国民党中，顽固派还站在支配其党的政策的地位，但在数量上只占少数，它的大多数党员（很多是挂名党员）并不一定是顽固派。这一点必须认识清楚，才能利用他们的矛盾，采取分别对待的政策，用极大力量去团结国民党中的中间派和进步派。　
> 　　（七）在抗日根据地内建立政权的问题上，必须确定这种政权是抗日民族统一战线的政权。在国民党统治区域，则还没有这种政权。这种政权，即是一切赞成抗日又赞成民主的人们的政权；即是几个革命阶级联合起来对于汉奸和反动派的民主专政。它是和地主资产阶级专政相区别的，也和严格的工农民主专政有一些区别。在政权的人员分配上，应该是：共产党员占三分之一，他们代表无产阶级和贫农；左派进步分子占三分之一，他们代表小资产阶级；中间分子及其他分子占三分之一，他们代表中等资产阶级和开明绅士。只有汉奸和反共分子才没有资格参加这种政权。这种人数的大体上的规定是必要的，否则就不能保证抗日民族统一战线政权的原则。这种人员分配的政策是我们党的真实政策，必须认真实行，不能敷衍塞责。这是大体的规定，应依具体情况适当地施行，不能机械地求凑数目字。这种规定，在最下级政权中可能须作某种变动，以防豪绅地主把持政权，但基本精神是不能违背的。在抗日统一战线政权中，对于共产党员以外的人员，应该不问他们有无党派关系及属于何种党派。在抗日统一战线政权统治的区域，只要是不反对共产党并和共产党合作的党派，不问他们是国民党，还是别的党，应该允许他们有合法存在的权利。抗日统一战线政权的选举政策，应该是凡满十八岁的赞成抗日和民主的中国人，不分阶级、民族、党派、男女、信仰和文化程度，均有选举权和被选举权。抗日统一战线政权的产生应该由人民选举，然后陈请国民政府加委。其组织形式，应该是民主集中制。抗日统一战线政权的施政方针，应该以反对日本帝国主义，反对真正的汉奸和反动派，保护抗日人民，调节各抗日阶层的利益，改良工农生活，为基本出发点。这种抗日统一战线政权的建立，将给全国以很大的影响，给全国抗日统一战线政权树立一个模型，因此应为全党同志所深刻了解并坚决执行。　　（八）在发展进步势力，争取中间势力，孤立顽固势力的斗争中，知识分子的作用是不可忽视的，顽固派又正在极力争取知识分子，因此，争取一切进步的知识分子于我们党的影响之下，是一个必要的重大的政策。　
> 　　（九）在宣传问题上，应该掌握下列的纲领：（1）实行《总理遗嘱》，唤起民众，一致抗日。（2）实行民族主义，坚决反抗日本帝国主义，对外求中华民族的彻底解放，对内求国内各民族之间的平等。（3）实行民权主义，人民有抗日救国的绝对自由，民选各级政府，建立抗日民族统一战线的革命民主政权。（4）实行民生主义，废除苛捐杂税，减租减息，实行八小时工作制，发展农工商业，改良人民生活。（5）实行蒋介石的“地无分南北，人无分老幼，无论何人皆有守土抗战之责任”的宣言。这些都是国民党自己宣布的纲领，也是国共两党的共同纲领。但是除了抗日一点外，现在的国民党都不能实行，只有共产党和进步派才能实行。这些是已经普及于人民中的最简单的纲领，但是许多共产党员还不知利用它们作为动员民众孤立顽固派的武器。今后应该随时把握这五条纲领，用布告、宣言、传单、论文、演说、谈话等等形式发布之。这在国民党区域还是宣传纲领，但在八路军新四军所到之地则是行动的纲领。根据这些纲领去做，我们是合法的，顽固派反对我们实行这些纲领，他们就是非法的了。在资产阶级民主革命阶段上，国民党的这些纲领，同我们的纲领是基本上相同的；但国民党的思想体系，则和共产党的思想体系绝不相同。我们所应该实行的，仅仅是这些民主革命的共同纲领，而绝不是国民党的思想体系。

**Comment by xuange306** [comment]
666

**Comment by iOSxiaoxian** [comment]
6666

**Comment by Pactortester** [comment]
666

**Comment by VulperVoid** [comment]
天秀

**Comment by northlion** [comment]
对于斗争，可以多看看毛选第五卷，这里面的才是真的屠龙术。可惜现在不出了，只能买到前四卷

**Comment by MiterV1** [comment]
秀儿

**Comment by Mohaiyo** [comment]
天秀

**Comment by dragonflys** [comment]
厉害了啊

**Comment by MoPei** [comment]
把朕的尚方宝剑拿来，给秀削个苹果

**Comment by WillYan881118** [comment]
天秀

**Comment by crykid** [comment]
朋友，你不怕有人请你喝茶吗？

**Comment by VicQwz** [comment]
老乡开门，送温暖！
