### ISSUE TITLE
习惯了才是最可怕的

### ISSUE THREAD

**Issue by hby07** [996icu/996.ICU#15132]
为什么996会这么普遍？因为最开始的卑躬屈膝，因为最开始的敢怒不敢言，这让管理层觉得压榨就对了。而跪的时间久了再站起来就难了！
更别说来自车、房、孩的压力了。
当付出与收入偏差过大时，必然会引发变革。
此刻，是沉默还是反抗？

**Comment by tinshee** [comment]
是的  ，身边很多人 感觉都麻木了

**Comment by JackNie** [comment]
起来吧，不愿做奴隶的人民

**Comment by hby07** [comment]
> 是的 ，身边很多人 感觉都麻木了
