### ISSUE TITLE
提议在五月一日发起罢工游街活动，并将所有996公司名单写入公链。

### ISSUE THREAD

**Issue by zhayujie** [996icu/996.ICU#15138]
可以从北京中关村， 软件园等地开始，有支持的人吗？

**Comment by BugZuo** [comment]
小伙子 冷静 这是犯法的

**Comment by xiaowei888** [comment]
这算维护合法权益

**Comment by bichaorui** [comment]
朋友，你需要一个理智方法，先了解一些游行法。
首先，你需要去公安局备案，
通过后，要在规定的时间，规定的地点，适当的人数。
有一点不符合，你这次游行就是非法的，我们要用武器
不能蛮干。
We are code people, not thugs！！！

**Comment by SoSkyrim** [comment]
试试就逝世

**Comment by zhayujie** [comment]
> Friends, you need a rational approach, first understand some parade methods.
> First of all, you need to go to the Public Security Bureau for the record.
> After passing, it is necessary to set the appropriate number of people at the specified time.
> There is something wrong with it. Your parade is illegal. We have to use weapons.
> Can't do it.
> 
> We are code people, not thugs！！！

我不管你是谁，我抵制996无罪，而且再说了，如果是另一个国家的人来说我抵制996有罪的话，这是否有点... 我是中国人!

ps： 我会严格遵守法律法规，在国家允许的条件下维护我们程序员的权益。
2015年2月28日，九届人大常委会第二十次会议正式批准我国加入《经济、社会、文化权利国际公约》。该公约第8条规定了工会组织的一项权利——“有权罢工，但应按照各个国家的法律行使此项权利”。

**Comment by Alan110** [comment]
https://github.com/996icu/996.ICU/issues/15612 可以先成立信息透明化的平台，团结其他职业的力量

**Comment by shenyunlong** [comment]
I AGREE WITH U !!!
