### ISSUE TITLE
不成立中央组织，这只会是一场闹剧

### ISSUE THREAD

**Issue by StarRabbit** [996icu/996.ICU#15288]
看看这issue区，群魔乱舞，发广告的，瞎JB交友的，就是群乌合之众。
这么好的trigger，这么好的天时地利人和，需要有人站起来，把996.icu主页换成组织章程，选合适的人成立中央组织，发展组织成员，组织罢工活动。成立工人纠察队打击工贼，维护组织成员合理的诉求权益，甚至将来成为改变中国的重要力量。
想想当年太祖们在那种条件下都能组织起来，真是天神下凡

**Comment by gugupluto** [comment]
组织不一定需要中央型的，法国的黄马甲运动也没有中央型组织。

**Comment by gugupluto** [comment]
组织不一定需要中央型的，法国的黄马甲运动也没有中央型组织。

**Comment by StarRabbit** [comment]
中国这样强中央强资本强控言的社会你想以自组织形式去斗争？怕不是失了心

**Comment by StarRabbit** [comment]
唉，太祖诚不我欺，小资产阶级的软弱性，迷乱性，妥协性是最无解bug。项目再大也跑不起来。
