### ISSUE TITLE
💋💋💋💋抵制996，女程序员发起抗议，抱团取暖 💋💋💋💋

### ISSUE THREAD

**Issue by kdzdaa** [996icu/996.ICU#15295]
抵制，996女程序员，微信交流群
![image](https://user-images.githubusercontent.com/49024257/55153412-5a602600-518d-11e9-8f5b-fb918b81a3d8.png)

**Comment by heavyrain2012** [comment]
男程序员路过

**Comment by yuanzui** [comment]
虽然我没进群  我敢打赌 三分之二往上都是男的

**Comment by toeii** [comment]
一大群男程序员即将到来

**Comment by tomorrow-alibaba** [comment]
应该发个男程序员交流群的，这样加群的女生就多了
