### ISSUE TITLE
996.ICU的同志们，进来看看小姐姐再走啊，微信投票链接，全是小姐姐

### ISSUE THREAD

**Issue by DemyLi** [996icu/996.ICU#15589]
投票王婷，投票王婷，投票王婷，最后评定第一爆照。有意思的还可以索要联系方式哦。31号结束，关注的可以到时候看看。没准小姐姐同意你哦。【手动滑稽】
![image](https://user-images.githubusercontent.com/17581906/55154657-5255b580-5190-11e9-99ed-588d1104a6ee.png)

**Comment by sookiezhu** [comment]
有没有道德了哇

**Comment by DemyLi** [comment]
> 有没有道德了哇

那你投票了没哇
