### ISSUE TITLE
阿里供应链实习生招聘，我们没有996，我们遍布下去了，总之发简历就是了。。。

### ISSUE THREAD

**Issue by tianxuzhang** [996icu/996.ICU#15606]
![image](https://user-images.githubusercontent.com/4149550/55154827-c1330e80-5190-11e9-9ef0-c958ac5f4130.png)

**Comment by monkindey** [comment]
+1  kaihao.zkh@alibaba-inc.com

**Comment by Patrick-Jun** [comment]
想来阿里，感觉什么都不会，都不精。

**Comment by njusq** [comment]
那么阿里的工作时间是？

**Comment by monkindey** [comment]
> 想来阿里，感觉什么都不会，都不精。

要不简历来一发?

**Comment by tianxuzhang** [comment]
> 那么阿里的工作时间是？

来了才知道，哈哈。啥时候毕业啊

**Comment by XuejuHuang** [comment]
给你点赞
