### ISSUE TITLE
欢迎换工作的朋友加入内推群

### ISSUE THREAD

**Issue by jiangtao** [996icu/996.ICU#15619]
这个repo厉害了，希望大家身体健康，生活美满，工作顺利。换工作的可以来内推群啊，加群渠道，由于群成员过多，加之前请自己做好做题的准备。

详情请查看 [neitui jobs](https://github.com/neitui/jobs)

**Comment by zl0711** [comment]
![image](https://user-images.githubusercontent.com/29787870/55155065-63eb8d00-5191-11e9-9cf3-e17e13b0a4c8.png)
