### ISSUE TITLE
关于 反996制度运动 的一些实际性建议

### ISSUE THREAD

**Issue by Rominez** [996icu/996.ICU#15612]
各位大佬，看到这个标题还点进来的，多半是真心想要付出行动了。注册个网址把劳动法搬出来，明眼人谁看不出来这不过是个网络游行运动？能有几个看完了拿着劳动法就去找老板说道说道的二愣子？看个乐呵点个Star完了，还不是地主家老实干活的乖宝宝？鄙人幸运，没经历过996的制度，却也深知其害。若是只有自己，那也是绝不会做出什么实际行动来的。反996绝非易事，鲁迅先生说的的奴性二字哪怕放在今天也一样适用。我不是键盘侠，说这么多不过刺激一下各位同行大佬们的血性，以下是实际建议：

1. 不管是996，还是997，各位珍惜手中的工作，不要在没有任何准备的情况下，一时热血贸然拿着劳动法索赔！
2. 建立专属我们开发人员的招聘信息分享平台。这个网站需要由我们每一位同志共同出手，提供自己的公司的信息，招聘岗位之类的数据，当然也必须要有福利待遇，工资结构以及加班制度等相关信息。在每条公司信息之下要有公开的评论系统，打分制度，参考一波淘宝买家评论，大众点评。发布信息的同志们更是可以用自己的语言方式详细描述对新同事能力方面的需求，对于求职者可有选择的进行直接沟通。这个平台定位在程序员圈内，旨在帮助求职者先看清公司和岗位的情况，并有一个规避hr非专业性筛选，与技术人员直接沟通的可能性。作为信息分享平台前期也不用纠结于信息真实性的审核，求职者完全可以在其他招聘网站上找到相同信息以验证真实性。
3. 有了这个平台，996制度下受苦受难的同志们可以开始寻求新机会了！拥有996制度的公司技术岗位离职率也会升高，招聘难度也会增大。这也是我的目的，让996公司在没有技术人员的情况下自我反省！从而消除996！

此事绝非一己之力能够实现，望有志之士揭竿而起，共同建立中国程序开发人员的大联盟！

**Comment by ty850454** [comment]
相当于建一个企业信息网

**Comment by shifefiei** [comment]
想法很不错

**Comment by Rominez** [comment]
> 
> 
> 相当于建一个企业信息网

接着这次行动之势，建一个知名于圈内的企业信息网！

**Comment by sagiwei** [comment]
先不论可行性，相比那些蹭热度的内推和拉帮结伙建群的，这种务实的建议不要沉下去。

**Comment by 0offer** [comment]
这个好，兹磁

**Comment by Rominez** [comment]
但若是没人响应起来就凉凉了。若是响应者众，我今晚会开始写这个项目的第一行代码。

**Comment by young40** [comment]
建议每月选一天, 至少每年选一天, 全国程序员不加班日

**Comment by shifefiei** [comment]
> 但若是没人响应起来就凉凉了。若是响应者众，我今晚会开始写这个项目的第一行代码。

咋们建个群

**Comment by zhayujie** [comment]
全栈独立开发者 一名报道，愿意贡献一份力量。楼主直接把开源项目建起来，工作流啥的弄规范点，咱们就可以开始整了

**Comment by LalMeng** [comment]
是个好建议 别沉下去
iOS开发报名

**Comment by duxiaofeng-github** [comment]
建个白名单，黑名单你列得完么？

**Comment by Justontheway** [comment]
要不要把国家企业信用信息网上的所有企业筛选后都拉进来

**Comment by luneshao** [comment]
> 但若是没人响应起来就凉凉了。若是响应者众，我今晚会开始写这个项目的第一行代码。

需不需要先设计一下功能，再动手。  (｡･ω･｡)

**Comment by luneshao** [comment]
> 建议每月选一天, 至少每年选一天, 全国程序员不加班日

大概会是996项目创建的那天 :D

**Comment by duxiaofeng-github** [comment]
https://feathub.com/LinXueyuanStdio/996.ICU

**Comment by Alan110** [comment]
信息透明化的交流平台，想法很好，希望能出一份力

**Comment by Rominez** [comment]
> 
> 
> > 但若是没人响应起来就凉凉了。若是响应者众，我今晚会开始写这个项目的第一行代码。
> 
> 需不需要先设计一下功能，再动手。 (｡･ω･｡)

晚上下班后先建个空项目，把设计群建起来，加入方式放 readme 里，讨论下怎么弄

**Comment by Rominez** [comment]
我的想法不是建立黑白名单，是这样：求职者可以先在拉钩，boss之类看到一个公司的招聘信息，验证公司真实性，了解公司的基本情况，然后有个程序员圈内的地方，从在岗人员的角度进一步了解这个公司，从而规避996之类的坑，以对不合理制度进行一定程度的打击。

**Comment by Rominez** [comment]
> 
> 
> https://feathub.com/LinXueyuanStdio/996.ICU

一定程度上的类似吧，我提出的是公司在职人员对自己公司信息的发布和评价，借助github的话看的还是有点杂乱，定向搜索和筛选之类的功能也不是很方便

**Comment by Rominez** [comment]
> 
> 
> 要不要把国家企业信用信息网上的所有企业筛选后都拉进来

实现细节慢慢讨论，我们需要更多的响应者。我正着手初步设计需求，会考虑你的建议，感谢。

**Comment by Rominez** [comment]
来吧
https://github.com/Rominez/league-of-Chinese-programmers.git

**Comment by heianxing** [comment]
几乎所有IT公司都是995、996、997的，有人说不去996的公司就行了，这行不通的。
除非不干IT，否则只能诉诸法律，或者大罢工了。

**Comment by timothyshen** [comment]
我记得有个关掉的issue已经写好需求并着手开发了

**Comment by Rominez** [comment]
> 
> 
> 我记得有个关掉的issue已经写好需求并着手开发了

我刚下班，正准备写需求，你说的在哪？

**Comment by zhayujie** [comment]
全栈独立开发者一名报道

**Comment by Rominez** [comment]
各位，我正在写初步的需求文档，大家先加群讨论，并帮忙召集小伙伴，企鹅群号 869698298

**Comment by timothyshen** [comment]
@Rominez https://docs.google.com/document/d/1O7Ybu8HzGbZYKZbB_gOgPGm7VDCvi8UIsy07SzpC7Bg/mobilebasic?pli=1#heading=h.gzlalst914vp 在这里

**Comment by Rominez** [comment]
> 
> 
> @Rominez https://docs.google.com/document/d/1O7Ybu8HzGbZYKZbB_gOgPGm7VDCvi8UIsy07SzpC7Bg/mobilebasic?pli=1#heading=h.gzlalst914vp 在这里

不翻墙打不开！？

**Comment by DongFangWuShuang** [comment]
懂点设计,会点前端,写过接口,我愿意出一份力

**Comment by timothyshen** [comment]
> > @Rominez https://docs.google.com/document/d/1O7Ybu8HzGbZYKZbB_gOgPGm7VDCvi8UIsy07SzpC7Bg/mobilebasic?pli=1#heading=h.gzlalst914vp 在这里
> 
> 不翻墙打不开！？
[#642](https://github.com/996icu/996.ICU/issues/642)
最早的开发想法

**Comment by Rominez** [comment]
> 
> 
> > > @Rominez https://docs.google.com/document/d/1O7Ybu8HzGbZYKZbB_gOgPGm7VDCvi8UIsy07SzpC7Bg/mobilebasic?pli=1#heading=h.gzlalst914vp 在这里
> > 
> > 
> > 不翻墙打不开！？
> > [#642](https://github.com/996icu/996.ICU/issues/642)
> > 最早的开发想法

好项目，设计的小巧又实用。我这边打算做更大的东西，以公司为点进行话题论坛，公司的评价由用户提供与其相同，另外还有更多实用的想法，也需要更多人的帮助。

**Comment by Rominez** [comment]
您好，我这样一个初步的想法能被关注实在倍感荣幸。我是一名开发者，对项目设计和工作流啥的没什么经验，急需帮助。目前只是写了初步的需求文档。希望能够进行进一步沟通。

项目地址 https://github.com/Rominez/league-of-Chinese-programmers.git

企鹅群号 869698298
----- 原始邮件 -----
发件人：zhayujie <notifications@github.com>
收件人："996icu/996.ICU" <996.ICU@noreply.github.com>
抄送人：Rominez <13034039585m0@sina.cn>,  Author <author@noreply.github.com>
主题：Re:_[996icu/996.ICU]_关于_反996制度运动_的一些实际性建议_(#15612)
日期：2019年03月28日 22点06分

全栈独立开发者 一名报道，愿意贡献一份力量。楼主直接把开源项目建起来，工作流啥的弄规范点，咱们就可以开始整了



&mdash;

**Comment by timothyshen** [comment]
身在国外的我，虽然并不可能会接触996，但终究感到十分伤感，我一个在读大学生不做996都能年薪近20万，反观国内却是如此之混乱。如果可以我也希望能尽些微薄之力，虽然技术不是很好。

**Comment by Rominez** [comment]
> 
> 
> 身在国外的我，虽然并不可能会接触996，但终究感到十分伤感，我一个在读大学生不做996都能年薪近20万，反观国内却是如此之混乱。如果可以我也希望能尽些微薄之力，虽然技术不是很好。

随时欢迎你的加入

**Comment by Alan110** [comment]
平台名字可以叫   公司信息透明化交流平台 CITC ( Company information transparency communication platform) ,

**Comment by hsztshlz** [comment]
可以出个 roadmap 或者搭个框架，现在杂音太多了，需要有实质的东西可以把大家组织起来

**Comment by duxiaofeng-github** [comment]
block chain 这时不就可以派上用场嘛？不可篡改，公开透明。

如果真的想搭建一个公开透明的平台，这里面就有很多问题。

1. 如何验证信息的真伪，是否匿名。具名怕被干，匿名变谣言。

2. 然后如何防止不被篡改，给钱展示一些信息，或者抹掉一些信息，甚至水军给刷一刷，就不可信了。

如何设计一个code as law的机制更重要，不然和其他招聘网有何区别？

**Comment by zpole** [comment]
一个问题，如何防止水军？一点想法是验证github账号，没有自己的repository的用户（不包括fork的和纯文档的repository）或一年内没有n天以上commit的用户不能参与打分（但可以查看结果）。

**Comment by guoliu** [comment]
> @Rominez https://docs.google.com/document/d/1O7Ybu8HzGbZYKZbB_gOgPGm7VDCvi8UIsy07SzpC7Bg/mobilebasic?pli=1#heading=h.gzlalst914vp 在这里

@Rominez @timothyshen 看了下需求文档👍，是不是可以可以仿照glassdoor进行资讯汇集？同时可以汇聚薪资、公司文化等状况，避免发泄性评论。

**Comment by duxiaofeng-github** [comment]
https://github.com/996icu/996.ICU/issues/16902

**Comment by duxiaofeng-github** [comment]
https://github.com/shengxinjing/programmer-job-blacklist

**Comment by duxiaofeng-github** [comment]
#16688

**Comment by timothyshen** [comment]
现在好多蹭热度的，glassdoor 确实是个很好的参照。我自己也深有体会。

> > @Rominez https://docs.google.com/document/d/1O7Ybu8HzGbZYKZbB_gOgPGm7VDCvi8UIsy07SzpC7Bg/mobilebasic?pli=1#heading=h.gzlalst914vp 在这里
> 
> @Rominez @timothyshen 看了下需求文档👍，是不是可以可以仿照glassdoor进行资讯汇集？同时可以汇聚薪资、公司文化等状况，避免发泄性评论。
> 
> 这个thead可以先讨论下web版技术栈？这样方便大家贡献

现在好多蹭热度的，glassdoor 确实是个很好的参照。我自己也深有体会。

**Comment by timothyshen** [comment]
> 一个问题，如何防止水军？一点想法是验证github账号，没有自己的repository的用户（不包括fork的和纯文档的repository）或一年内没有n天以上commit的用户不能参与打分（但可以查看结果）。

同时可以使用匿名制以保障程序员的工作。

**Comment by wln518720** [comment]
进群了，发现只有四个人。
尽快出个roadmap吧，不然都是空话。
另外，建议数据上链防马甲刷评论。

**Comment by CooperCao** [comment]
区块链

**Comment by netsman1030** [comment]
首先@Romiez 
你如果要写需求。我个人认为不应该在qq等国内监控的平台上带动
我们需要的是绕过国内监控和企业管制的独立平台。假如有关部门要整你。分分钟就能抄你水表
建议是通过discord这类不需要实名验证的渠道。一方面比较安全。另一方面他是模仿slack管理比较方便。也能通过bot收集讯息

**Comment by Rominez** [comment]
早上好各位。实不相瞒，我是做java开发工作的，目前状态997。仅凭一个想法支撑起来这个项目有点难度。我再过大概一个月左右就能有周末双休了，然后我能做到每周两天全面投入这个项目的开发。这个项目首先**很需要**一个有经验又有热情的**产品同学**带动起来，我不知道能不能在这里找到。目前加群的人也很少，远比不过其他issue里随便发个二维码拉帮结派的群人数多。我抛出这块砖，希望能有更多人参与进来，若是能招来大佬带着做就更好不过了。若是没有，我只能在这里感谢大家对我这个想法的支持。谢谢。

**Comment by laomao11235** [comment]
应该创建一个电报群，微信QQ监控太厉害

**Comment by WangTaoSpace** [comment]
> block chain 这时不就可以派上用场吗？不可篡改，公开透明。
> 
> 如果真的想搭建一个公开透明的平台，这里面就有很多问题。
> 
> 1. 如何验证信息的真伪？是否匿名？具名怕被干，匿名变谣言。
> 2. 然后如何防止不被篡改，给钱展示一些信息，或者抹掉一些信息，甚至水军给刷一刷，就不可信了。
> 
> 如何设计一个公平的机制更重要，不然和其他招聘网和企业信息网有何区别？

可以针对不同领域的程序员随机生成考卷，符合要求的程序员才能加入。杜绝广告商的加入。

**Comment by jsenss** [comment]
兄弟们，搭平台也是需要好域名的。[分享给大家](https://mi.aliyun.com/shop/35459)

**Comment by wienne0417** [comment]
已加群，群号有点隐蔽，建议把群号放在正文

**Comment by Rominez** [comment]
> 
> 
> 应该创建一个电报群，微信QQ监控太厉害

又不是啥非法运动，只是讨论项目都会被搞？

**Comment by breeze12** [comment]
好建议，支持。

**Comment by Xihuyouyu** [comment]
别沉

**Comment by dreamzeng** [comment]
老板说公司没有996，都是员工自愿加班的，WTF！！！

**Comment by netsman1030** [comment]
> > 应该创建一个电报群，微信QQ监控太厉害
> 
> 又不是啥非法运动，只是讨论项目都会被搞？

反抗就是非法的，大陆法系只看结果，不看原因和过程，而且一个案一个案例不互相参考
我们的行为已经属于寻衅滋事的范畴了。

**Comment by netsman1030** [comment]
@Rominez   996.ICU的朋友建了个 discord群，希望一起讨论下

https://discord.gg/stSSHgY
群里几百人了

**Comment by jinzhongjian** [comment]
捞一把，别沉

**Comment by yowhat** [comment]
声援一下

**Comment by netsman1030** [comment]
> 建个白名单，黑名单你列得完么？

这个东西是帮助大家规避陷阱的，而不是一窝蜂的去好企业。。
这不是防火墙配置啊。。

**Comment by shifefiei** [comment]
我报名了

**Comment by tangzhe7** [comment]
我们需要官方协会来统筹，各位，组中国程序员协会吧

**Comment by Relish123** [comment]
前两天看新闻，东莞松山湖就有个进ICU的，不说也能知道是哪个公司。
http://kb.southcn.com/content/2019-03/27/content_186353833.htm

**Comment by sky068** [comment]
> 兄弟们，搭平台也是需要好域名的。[分享给大家](https://mi.aliyun.com/shop/35459)

啥啊，阿里就是996的代表，还用阿里的域名？不知道要备案啊。用namesilo.com域名多好，便宜又不用备案。

**Comment by sky068** [comment]
> 我们需要官方协会来统筹，各位，组中国程序员协会吧

好像中国有规定，组建协会是需要政府批准的，目前国家都是和企业站在一排的，恐怕不会批准我们。

**Comment by netsman1030** [comment]
我个人觉得吧。写个APP发到谷歌市场，可能好一些

**Comment by sky068** [comment]
个人觉得服务一定不能放在国内，国内政府都是和996企业站在一队的。

**Comment by Echoban** [comment]
> > block chain 这时不就可以派上用场吗？不可篡改，公开透明。
> > 如果真的想搭建一个公开透明的平台，这里面就有很多问题。
> > 
> > 1. 如何验证信息的真伪？是否匿名？具名怕被干，匿名变谣言。
> > 2. 然后如何防止不被篡改，给钱展示一些信息，或者抹掉一些信息，甚至水军给刷一刷，就不可信了。
> > 
> > 如何设计一个公平的机制更重要，不然和其他招聘网和企业信息网有何区别？
> 
> 可以针对不同领域的程序员随机生成考卷，符合要求的程序员才能加入。杜绝广告商的加入。

这个机制还是不行，叫公司程序员做一下不是分分钟的事吗，无良公司照样可以混进来

**Comment by sueysok** [comment]
搞一批文化衫吧

**Comment by sky068** [comment]
> > > block chain 这时不就可以派上用场吗？不可篡改，公开透明。
> > > 如果真的想搭建一个公开透明的平台，这里面就有很多问题。
> > > 
> > > 1. 如何验证信息的真伪？是否匿名？具名怕被干，匿名变谣言。
> > > 2. 然后如何防止不被篡改，给钱展示一些信息，或者抹掉一些信息，甚至水军给刷一刷，就不可信了。
> > > 
> > > 如何设计一个公平的机制更重要，不然和其他招聘网和企业信息网有何区别？
> > 
> > 
> > 可以针对不同领域的程序员随机生成考卷，符合要求的程序员才能加入。杜绝广告商的加入。
> 
> 这个机制还是不行，叫公司程序员做一下不是分分钟的事吗，无良公司照样可以混进来

验证github resp，有实际项目的才行。

**Comment by yhqqhh** [comment]
还可以收集一些公司制度,除了996,还有不涨薪,有无福利等,方便选择.还有一些拖欠工资等行为

**Comment by tangzhe7** [comment]
> > 我们需要官方协会来统筹，各位，组中国程序员协会吧
> 
> 好像中国有规定，组建协会是需要政府批准的，目前国家都是和企业站在一排的，恐怕不会批准我们。

国家不是和政府站一队，是因为政府里都是企业管理层的，但是没有政府认可的行动都是反动，让他们知道，不可为

**Comment by tangzhe7** [comment]
> > 我们需要官方协会来统筹，各位，组中国程序员协会吧
> 
> 好像中国有规定，组建协会是需要政府批准的，目前国家都是和企业站在一排的，恐怕不会批准我们。

看看九三学社这些社团，和政府站在一起，这是最基本的

**Comment by fakerLinXiao** [comment]
天下苦“996”久矣！

**Comment by Warmriver** [comment]
期待

**Comment by liangjiaying** [comment]
地址呢

**Comment by scarsu** [comment]
shengyuan

**Comment by sylviatanggit** [comment]
啥也不说，反手就给你一个支持! 暂时功能可以不需要太多，简单高效~

**Comment by duxiaofeng-github** [comment]
https://www.jianshu.com/p/a24c1a8fe25e

> Memo这套协议一经发布，就再也无法撤消了，哪怕是把Memo的作者抓起来枪毙掉，把memo.cash这个网站关了，那这个去中心化的微博系统也还是存在的。

> Memo构造的这个去中心化的微博还是一个完全公开的发帖系统，在新浪微博上你可以拉黑某个人，让他无法读到你的信息。但在Memo上，你是无法拉黑任何人的。

>

**Comment by KS-OTO** [comment]
产品刘一脚

**Comment by duxiaofeng-github** [comment]
#18514
