### ISSUE TITLE
欢迎杭州程序员加微信群，内推 阿里、网易、vivo、今日头条等公司职位，抱团应对996

### ISSUE THREAD

**Issue by FanGuangcheng** [996icu/996.ICU#15628]
![image](https://user-images.githubusercontent.com/16233620/55155003-343c8500-5191-11e9-9ba1-3b97249c9028.png)

**Comment by FanGuangcheng** [comment]
杭州程序员进群，有好职位，互相分享

**Comment by zl0711** [comment]
![image](https://user-images.githubusercontent.com/29787870/55155046-533b1700-5191-11e9-9580-70423380aacd.png)
