### ISSUE TITLE
北京程序员吐槽群 ~~~~~`北京的进群，组织在召唤，就差你了

### ISSUE THREAD

**Issue by wang8098chao** [996icu/996.ICU#15621]

**Comment by zl0711** [comment]
![image](https://user-images.githubusercontent.com/29787870/55155000-30a8fe00-5191-11e9-8f05-c992c8c24ab2.png)

**Comment by zl0711** [comment]
![image](https://user-images.githubusercontent.com/29787870/55155019-3dc5ed00-5191-11e9-99ee-76eb925ad724.png)
