### ISSUE TITLE
字节跳动内推，上下班不强制，隔周加班一天给加班费！

### ISSUE THREAD

**Issue by ianho** [996icu/996.ICU#15630]
[点击进入](https://ee.bytedance.net/hr/?token=WhRHwXnpGstKDVSZk7XIyg==)

> or 扫码 ⤵️

![](http://sf6-ttcdn-tos.pstatp.com/obj/developer-baas/baas/tt38956bv3v5xslr15/2cabf7f7e9add7ea_1552469552786.png)

**Comment by ZackLeeyg** [comment]
贵司高居黑名单第四位。。。
