### ISSUE TITLE
母胎单身专注于安全计算的美女程序员求相亲

### ISSUE THREAD

**Issue by fengsx** [996icu/996.ICU#15747]
尊敬的各位程序员同志：
现有一年轻貌美的学霸级单身女程序员敞开心扉，求一人生伴侣。
坐标杭州，要求 85 - 89。希望你有一点点生活情趣，会 python、会密码学优先！

**Comment by jackToken** [comment]
我信你个鬼

**Comment by ArtisanM** [comment]
我信你个鬼

**Comment by qbeenslee** [comment]
你怕不是HR吧

**Comment by homekuanyi** [comment]
信你条铁

**Comment by fengsx** [comment]
等下，照片发不上来啊。。。github 挂了啊

**Comment by hacklinshell** [comment]
我信你！  微信告诉我(狗头)

**Comment by iuok1001** [comment]
我想学，求教

**Comment by hacklinshell** [comment]
> 等下，照片发不上来啊。。。github 挂了啊

为什么你介绍是个boy~

**Comment by zhangxinlong633** [comment]
HR。。骗简历的

**Comment by fengsx** [comment]
> > 等下，照片发不上来啊。。。github 挂了啊
> 
> 为什么你介绍是个boy~

发的我同事的。。。加了vpn 都发不了图啊

**Comment by hacklinshell** [comment]
> > > 等下，照片发不上来啊。。。github 挂了啊
> > 
> > 
> > 为什么你介绍是个boy~
> 
> 发的我同事的。。。加了vpn 都发不了图啊

在线等照片~~
