### ISSUE TITLE
百度科技园K1，打卡下班

### ISSUE THREAD

**Issue by sirwzgaara** [996icu/996.ICU#1598]
rt

**Comment by rammiah** [comment]
十点半下班，也太惨了吧

**Comment by sirwzgaara** [comment]
> 十点半下班，也太惨了吧

打完卡发现又走不了了。。不能浪

**Comment by maikebing** [comment]
我看百度到现在都是灯火通明。 百度大楼里的人都在加班吗？我看每个办公室都亮灯。 西二旗 那边的

**Comment by sirwzgaara** [comment]
> 我看百度到现在都是灯火通明。 百度大楼里的人都在加班吗？我看每个办公室都亮灯。 西二旗 那边的

现在还有1/5的人吧，最近赶Q1的OKR，平时这个时候没这么多人了，一般9点就走了

**Comment by tanqizhi** [comment]
刚刚不是还有个百度发招聘的吗
刚好联动这个

**Comment by Sakuraezra** [comment]
我正在百度科技园

**Comment by maikebing** [comment]
我每次下班后看到百度还灯火通明， 搞的我都不好意思下班了。

**Comment by sirwzgaara** [comment]
> 我正在百度科技园

你这太拼了，班车都没了

**Comment by maikebing** [comment]
> > 我正在百度科技园
> 
> 你这太拼了，班车都没了

全当健身。
