### ISSUE TITLE
各位大佬可以来【offerpie】【offer校园派】分享一波你们校招时候的经验啊，心得啊，校招薪水啊。。。。。我是一个加班蹭热度的运营🐶，虽然我是在宣传我司产品，但我还是想吐槽一遍我的老板，压榨员工不让下班！

### ISSUE THREAD

**Issue by offerpie** [996icu/996.ICU#16018]
各位大佬可以来【offerpie】【offer校园派】分享一波你们校招时候的经验啊，心得啊，校招薪水啊。。。。。我是一个加班蹭热度的运营🐶，虽然我是在宣传我司产品，但我还是想吐槽一遍我的老板，压榨员工不让下班！

这个是我们的微信小程序二维码：
[https://img-blog.csdnimg.cn/20190327193052262.png](url)

这个是薪资爆料实例
[https://img-blog.csdnimg.cn/20190327193112141.jpeg?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NDEwMzYwNw==,size_16,color_FFFFFF,t_70](url)

**Comment by UserName-Haha** [comment]
哪儿来的运营狗。。
