### ISSUE TITLE
字节跳动下抖音内推通道，坐标上海。

### ISSUE THREAD

**Issue by fantastao** [996icu/996.ICU#1605]
有兴趣可发简历到这个账号的邮箱😄，我们不是996。

**Comment by aeolusheath** [comment]
是的，你们不是，你们是9-11-7

**Comment by 303snowing** [comment]
字节跳动1011 大小周吧  正常操作应该是这样

**Comment by fantastao** [comment]
> 是的，你们不是，你们是9-11-7

**Comment by fantastao** [comment]
> 字节跳动1011 大小周吧 正常操作应该是这样

大小周正解，而且双周加一天班会有加班费。上班时间其实正常都是10点，晚上7点吃完饭就可以走了，不过一般活没干完都会加会儿班，不会硬性要求你留下来干到几点才能走。有时候有事情也可以早走，打招呼就行。上海这边负责抖音海外的团队是这样的。

**Comment by ZechCal** [comment]
大佬内推有实习吗，感觉错过了暑期实习

**Comment by fantastao** [comment]
> 大佬内推有实习吗，感觉错过了暑期实习

可以，发简历吧。现在在校招。

**Comment by yicong** [comment]
字节跳动对学历学校要求很高？985/211？

**Comment by ZechCal** [comment]
好的谢谢大佬。。我还得问下导师需要不需要提前去。。需要我就投了。。

**Comment by thankwsx** [comment]
活干不完得留下来加班就不是加班了？

**Comment by yjhmelody** [comment]
过了四面迟迟不发offer……

**Comment by EscapeFromCoding** [comment]
我司日常十点以后下班，求职请慎重

**Comment by 857092** [comment]
我没记错的话 北京这边996的风气 就是头条带起来的吧 。。。

**Comment by tanguofu** [comment]
+1 上海相对灵活
