### ISSUE TITLE
我觉得 应该成立一个程序员工会

### ISSUE THREAD

**Issue by maikebing** [996icu/996.ICU#1606]
1、接受援助，工会非盈利组织， 以工会方式发出函到公司， 避免一些员工被公司排挤
2、提倡高效，工作时间有效发挥每个人的效能，而不是看网页闲逛。 
3、用工咨询，对一些员工消极怠工等，不提高效率也要给一些小企业提供一些解决方案。

**Comment by sandelion** [comment]
前来支持

**Comment by Alan110** [comment]
顶

**Comment by zombie110year** [comment]
工会的经济来源? 如果无法支撑离职 (罢工) 人员的生活, 工会将毫无凝聚力.

**Comment by maikebing** [comment]
> 工会的经济来源? 如果无法支撑离职 (罢工) 人员的生活, 工会将毫无凝聚力.

工会肯定不能承担这个事情， 目前的能提供一些帮助和针对企业提供一些咨询， 已经就可以了。 我相信能做到第一步， 有一天就能实现你说的第二部 。

**Comment by Alan110** [comment]
![image](https://user-images.githubusercontent.com/7564425/55086555-9343c080-50e3-11e9-856c-3fc4065d6e24.png)

![image](https://user-images.githubusercontent.com/7564425/55086608-a8b8ea80-50e3-11e9-8677-8f1ca0c76904.png)

之前知乎上的一个答案，貌似现在找不到了~~~

**Comment by yicong** [comment]
顶

**Comment by EscapeFromCoding** [comment]
工会就别想了……自有国情在此

**Comment by yizibi** [comment]
😌搜了下，果然有志同道合的人，想想，难度大，无异于登天

**Comment by sandelion** [comment]
已经走偏了，看看issue，有些心凉
