### ISSUE TITLE
被拖欠工资，劳动仲裁不作为的路过

### ISSUE THREAD

**Issue by noecs** [996icu/996.ICU#16076]
老板一直拖，口头一直一天拖一天，到最后，被逼无奈申请了劳动仲裁。开庭中，不允许录音或是视频。劳动仲裁向着公司，让我出具无意义且与本案不相关的证据，他所仲裁提交的，最后我成了倒欠他几万块。当然，我很无奈，被告人（老板）得意洋洋。身边比比皆是的案例，没有一个通过劳动仲裁能够拿到自己劳动应有的钱，让这些人逍遥法外，胡作非为。

**Comment by zhangnanvip** [comment]
去法院走起诉，不行就再往上到高级人民法院，实在不行发个抖音说不定就解决了。

**Comment by Leo10086** [comment]
我也是劳动仲裁不作为，仲裁委员会一直帮公司说话，比如“30天肯定给不到啦、45天不给你直接申请强制执行好啦”，这帮人领着工资和稀泥，我也想干这种工作。坐标天津南开

**Comment by XieB** [comment]
被拖欠700块工资，至今不给！坐标河南新乡

**Comment by helloworld112234** [comment]
加油

**Comment by noecs** [comment]
@zhangnanvip 我以前以为，邪不胜正。直到有一天，我在劳动仲裁的法庭上，看着他们将黑说成白。彻底死心了。法院？笑话。

**Comment by w2xx** [comment]
仲裁赢了，法院强制执行又如何，老板一句话没钱，法院都拿他没办法。老板直接在微信群说，中国的法律又能帮你们什么呢。法院的人说，案子只能放在那，等哪天有钱了在给。。呵呵，武汉和北京两边一共差员工一百多万。就这么不了了之了

**Comment by helloworld112234** [comment]
这个社会是为资本家服务的，要怪只怪自己成为不了资本家，打工者，就做好被压迫的准备，没啥的

**Comment by noecs** [comment]
@w2xx 是的，法院的强制执行，根本无法对这些人有威胁。从我开庭完的那一天，彻底死心了。当然，老板又在筹备开他的下一个公司。

**Comment by noecs** [comment]
@helloworld112234 现在只有无助，愤怒。此事对我造成的影响，就是一辈子。:(

**Comment by ywzhou** [comment]
@noecs 好心情是金钱买不来的。虽然遇到这种糟心的事，但也算得到了一次成长的经历，以后能更好地保护自己的权益不被侵害。

而且，法院、仲裁不是主持正义的，法律只讲证据。即便打赢官司，强制执行也不一定能保证能成。

不管发生了什么，请得饶人处且饶人。饶的不是别人，是你自己，放下过去，放过自己。

共勉，

**Comment by noecs** [comment]
@ywzhou 谢谢

**Comment by Song-HaiFeng** [comment]
加油 你是最胖的

**Comment by noecs** [comment]
@Song-HaiFeng 你才是！
