### ISSUE TITLE
这个抵抗有用吗

### ISSUE THREAD

**Issue by zoeeeNg** [996icu/996.ICU#16112]
回家路上接到今晚上线通知 又赶回公司 先来个通宵再说 话说 这个项目有用吗

**Comment by bofeiw** [comment]
人多力量大，先要让问题走进人们视野

**Comment by yuhaocan** [comment]
不能发声呐喊，敲敲键盘也一时爽啊

**Comment by ShuaiShuaiLee** [comment]
你死的时候连句呐喊都不敢吗！

**Comment by ShuaiShuaiLee** [comment]
不在沉默中爆发！就在沉默中死亡！

**Comment by helloworld112234** [comment]
> 你死的时候连句呐喊都不敢吗！

说那么多有啥用，人家企业就不 care，政府也不 care，因为并不赚钱，这个社会不缺人，活有大把人干

**Comment by lynkas** [comment]
如果不抵抗，会让你过得更舒服吗？

会——继续加班
不会——点个star

**Comment by bofeiw** [comment]
> > 你死的时候连句呐喊都不敢吗！
> 
> 说那么多有啥用，人家企业就不 care，政府也不 care，因为并不赚钱，这个社会不缺人，活有大把人干

知乎上说的对，希望有人能够站出来，通过谈判解决问题

**Comment by lynkas** [comment]
> > > 你死的时候连句呐喊都不敢吗！
> > 
> > 
> > 说那么多有啥用，人家企业就不 care，政府也不 care，因为并不赚钱，这个社会不缺人，活有大把人干
> 
> 知乎上说的对，希望有人能够站出来，通过谈判解决问题

没用的，谈判……坦克压人么……

不得不承认，有的东西就是很垃圾，哪怕天天宣传吹得天花乱坠。

**Comment by bofeiw** [comment]
> > > > 你死的时候连句呐喊都不敢吗！
> > > 
> > > 
> > > 说那么多有啥用，人家企业就不 care，政府也不 care，因为并不赚钱，这个社会不缺人，活有大把人干
> > 
> > 
> > 知乎上说的对，希望有人能够站出来，通过谈判解决问题
> 
> 没用的，谈判……坦克压人么……
> 
> 不得不承认，有的东西就是很垃圾，哪怕天天宣传吹得天花乱坠。

至少要有点信心吧

**Comment by lynkas** [comment]
> > > > > 你死的时候连句呐喊都不敢吗！
> > > > 
> > > > 
> > > > 说那么多有啥用，人家企业就不 care，政府也不 care，因为并不赚钱，这个社会不缺人，活有大把人干
> > > 
> > > 
> > > 知乎上说的对，希望有人能够站出来，通过谈判解决问题
> > 
> > 
> > 没用的，谈判……坦克压人么……
> > 不得不承认，有的东西就是很垃圾，哪怕天天宣传吹得天花乱坠。
> 
> 至少要有点信心吧

抱歉，没有信心，看了这么多社会事件的处理之后真的是一点一丁点信心都没有了……

**Comment by Saberko** [comment]
![image](https://user-images.githubusercontent.com/6974527/55162684-4a534100-51a3-11e9-8e3a-c4725ef362df.png)
