### ISSUE TITLE
我每天都需要工作3小时以上，好累

### ISSUE THREAD

**Issue by ECNUJason** [996icu/996.ICU#16188]
我每天都需要工作3小时以上，好累

**Comment by 313567063** [comment]
![1](https://user-images.githubusercontent.com/33477809/55160200-bf237c80-519d-11e9-8fc5-a7e7c5977784.jpeg)
![2](https://user-images.githubusercontent.com/33477809/55160220-cd719880-519d-11e9-9c9e-1d506da939ad.jpeg)
![3](https://user-images.githubusercontent.com/33477809/55160228-d2364c80-519d-11e9-9d43-6f216a3dcc0f.jpeg)
![4](https://user-images.githubusercontent.com/33477809/55160233-d498a680-519d-11e9-9f40-3c016dc0bfa1.jpeg)
