### ISSUE TITLE
建议成立程序员工会

### ISSUE THREAD

**Issue by a919591735** [996icu/996.ICU#16210]
团结一切可以团结的程序员同志，互相帮助，互相理解，制定一套可行的规则，既不损害公共秩序，又能合理的保护程序员群体的合法利益。

**Comment by swuecho** [comment]
[投票](https://cloudqa.iego.cn/sr/icu996)

[添加](https://cloudqa.iego.cn/sr/icu996)


<img width="514" alt="Screen Shot 2019-03-28 at 12 43 36 AM" src="https://user-images.githubusercontent.com/666683/55138002-60dea580-516d-11e9-9b67-4d92ba72903c.png">

[公司名单](http://blog.meihao.us/icu996_poll_result/)

<img width="798" alt="Screen Shot 2019-03-28 at 4 55 01 PM" src="https://user-images.githubusercontent.com/666683/55143726-4a8b1680-517a-11e9-9264-191c902497df.png">

[参与开发](https://github.com/swuecho/icu996_poll_result)

可以基于调查结果做可视化，分析等


[JSON数据](http://122.112.218.148:15666/v_answer)

可以用来做二次开发

**Comment by jaciot** [comment]
为推动中国企业遵守劳动法奋斗，保护程序员正当权益

**Comment by worldbeatiful** [comment]
Good idea，i will support you
