### ISSUE TITLE
全国人大代表浙江部分名单及手机电话号

### ISSUE THREAD

**Issue by zhlhuang** [996icu/996.ICU#16219]
[全国人大代表浙江部分名单及手机电话号](https://boxun.com/news/gb/china/2011/03/201103030148.shtml)

**Comment by siminx** [comment]
网页打不开了。。。。。。

**Comment by zhlhuang** [comment]
许　江（网上称是江泽民外甥 中国美术学院院长，中国美协副主席，浙江省文联主席 13606629491）　　
    
    张金如（浙江省绍兴市委书记 13806753366 0575 85087999）
    
    王建华（浙江绍兴文理学院党委书记 13735246677，0575-88057788）
    
    王梅珍（女，浙江纺织服装职业技术学院院长 13306666603 0574-86328001，86329001，86329003）
    
    车晓端（女，民建浙江省副主委、绍兴市主委，绍兴市人大常委会副主任13505751302 0575-85128912 ）
    
    毛光烈（新任浙江省副省长，传将任浙江大学党委书记，原浙江省宁波市委副书记、市长，13567899068，新手机号未知）
    
    厉月姿（女，浙江省妇联主席13958030566 0571-87057502）
    
    卢亦愚（民盟浙江省副主委，省政府参事，省公共卫生应急检测重点实验室主任 13858190562 0571-87235034）
    
    孙建国（浙江省衢州市委书记 13905700269）
    
    李卫宁（浙江省嘉兴市委副书记、市长 13906511537 ）
    
    张新建（中国电信集团浙江省电信公司总经理 13905710558 0571-87856001）
    
    陈小恩（浙江省劳动和社会保障厅厅长 13805728866 0571-87058866）
    
    李令红（浙江省宁波港集团有限公司总裁 13906699001 0574-27695900）　
    
    杨　卫（浙江大学校长 0571-87951109 ）
    
    姒健敏（全国人大常委会委员，九三学社浙江省主委，浙江大学副校长，13905810767 0571-87953700）
    
    郑继伟（致公党中国常委、浙江省主委，浙江省副省长，13906506582，0571-88008866，87051522）
    
    邵占维（杭州市长、副书记，原浙江省温州市委书记、市人大常委会主任 13805862586 0571-85251000）
    
    范　谊（致公党浙江省副主委、宁波市主委，宁波市政协副主席，宁波大学外语学院院长 13606584499 0574-87600322）
    　
    吴国华（民建中央常委、浙江省委主委，省人大常委会副主任 13606649948 0571-87053945 ）
    
    钟昌明（畲族，浙江省景宁畲族自治县委副书记、县长 13906785133）
    
    吴桂英（女，浙江省民政厅厅长 13606805959 0571-87050201 ）
    
    沈明才（中国联合网络通信有限公司浙江省分公司总经理 13003601818）
    
    刘希平（浙江省教育厅厅长 0571-88008800）　
    
    陈铁雄（浙江省台州市委书记，原副书记、市长 13857196129 0576-88511666）
    
    陈云龙（浙江省人民检察院检察长 原省国安厅副厅长，厅长，0571-88810001）
    
    齐　奇（浙江省高级人民法院院长 0571-87054269 87054206）
    
    蔡　奇（浙江省委常委、组织部长，原浙江省杭州市委副书记、市长 0571-87053399转）
    
    刘锡荣（全国人大常委会委员、全国人大法律委员会副主任委员）
    邱继宝（飞跃集团有限公司董事长，中国国际商会副会长，浙江省工商联副会长）
    
    李大鹏（浙江康莱特集团党委书记、董事长、总裁、浙江中医学院教授）
    
    孙　伟（十届全国人大常委会副秘书长、机关党组成员）
    
    汪惠芳（女，九三学社浙江省衢州市主委、市人大常委会副主任、市农科所所长）
    
    张剑星（浙江虎山集团有限公司董事长、总裁，中国建材南方水泥有限公司常务副总经理）　　
    
    张德江（中央政治局委员、国务院副总理）
    
    陆元盛（国家体育总局乒乓球羽毛球运动管理中心主任助理）
    　　
    陆东福（铁道部副部长）
    　　
    陈　飞（浙江省永嘉县渠口乡珠岸村农民、永嘉县绿色环保志愿者协会会长）　　
     
    陈昆忠（浙江省金华市委副书记、市长）
    　　
    陈荣高（浙江省丽水市委书记）
    　　
    陈笑华（女，浙江省温州市人大常委会副主任）
    　　
    陈海啸（农工党浙江省台州市主委、市人大常委会副主任、台州医院院长）
    　　
    茅威涛（女，浙江小百花越剧团团长，中国戏剧家协会副主席）
    　　
    林　燚（女，浙江省温岭市农业技术推广站副站长）
    　　
    金颖颖（女，工商银行温州市分行营业部个金中心兼个人理财室主任）
    　　
    周晓光（女，浙江新光控股集团有限公司董事长）
    　　
    郑玉歆（中国社会科学院环境与发展研究中心主任，中国社会科学院数量经济与技术经济研所副所长）
    
    杨成涛（浙江苍南县宜山镇宜一村党委书记 ）
    　　
    李如成（雅戈尔集团股份有限公司党委书记、董事长、总裁）
    　　
    李　牧（全国人大教科文卫委员会委员，中国文联副主席、党组副书记、书记处书记）
    　　
    李科平（舟山市华鹰远洋渔业有限公司船长、总经理）
    　　
    杨晓霞（女，浙江省宁波维科精华家纺有限公司制品分厂二车间质量员）
    　　
    吴子婴（女，浙江理工大学材料与纺织学院纺织材料实验室主任）
    　　
    郑杰民（浙江省宁波市人大常委会副主任）　
    　
    宗庆后（杭州娃哈哈集团有限公司董事长、总经理）
    
    冯长根（全国人大常委会委员，全国人大教科文卫委员会委员，中国科协书记处书记）
    
    方中华（浙江省台州市路桥区路南街道方林村党总支书记）
    
    尤小平（浙江省温州市工商联副会长，华峰集团董事局主席、总裁，浙江华峰氨纶股份有限公司董事长）
    　　
    方　青（女，浙江省金华市金东区赤松镇中心小学教务主任）
    　　
    吕　帆（女，浙江省温州医学院副院长，眼视光学院执行院长）
    　　
    吕祖善(浙江省委副书记、省长)
    　　
    朱新康(浙江省湖州市织里镇大港村党总支书记)
    　　
    乔传秀（女，浙江省政协新任主席，全国人大常委会委员、全国人大常委会代表资格审查委员会委员、全国人大内务司法委员会委员，全国总工会副主席、党组副书记、书记处书记）
    　　
    任美琴（女，浙江省临海市外国语学校副校长）
    　　
    庄启传（纳爱斯集团有限公司党委书记、董事长兼总裁）
    　　
    赵　丰（中国丝绸博物馆副馆长）
    　　
    赵林中（浙江富润控股集团董事局主席）
    　　
    赵洪祝（浙江省委书记，省人大常委会主任）
    　　
    南存辉（浙江正泰集团董事长）　
     　
    俞学文（浙江省武义县更香有机茶开发有限公司董事长）
    　　
    姚献平（浙江省杭州市化工研究院党委书记、院长）
    　　
    高　强（全国人大财政经济委员会副主任委员、全国人大常委会预算工作委员会主任）
    　　
    夏士林（浙江省升华集团控股有限公司党委书记、董事长）
    　　
    倪岳峰（调任福建省副省长 全国人大常委会委员、全国人大环境与资源保护委员会副主任委员）
    　　
    徐秋芳（女，浙江林学院环境科技学院教授）
    　　
    曹棉英（女，国家赛艇队女子组主教练、浙江体育职业技术理学院竞技体育六系主任助）
    　　
    崔　巍（女，浙江省杭州歌舞剧院副院长）
    　　
    阎寿根（浙江省金华市人大常委会主任）
    　　
    梁黎明（女，浙江省舟山市委书记、市人大常委会主任）
    　　
    韩启德（全国人大常委会副委员长，九三学社中央主席，中国科学技术协会主席，北京大学医学部主任）
    　　
    程惠芳（女，浙江工业大学经贸管理学院院长）
    　　
    傅企平（浙江省奉化市萧王庙街滕头村党委书记，宁波滕头集团公司董事长、总裁）
    　　
    鲁冠球（浙江省万向集团党委书记、董事局主席）
    　　
    褚　平（全国人大内务司法委员会委员，全国工商联党组副书记、专职副主席兼秘书长）
    　　
    缪水娟（女，浙江省杭州高级中学校长）
    　　
    薛少仙(浙江省台州市人大常委会主任)
     
    于辉达（浙江省杭州市人大常委会党组书记、副主任）
    　　
    马　以（浙江省湖州市委副书记、市长）
    　　
    王小同（民革浙江省温州市主委，温州市人大常委会副主任，温州医学院康复系主任）
     　
    王仁洲（浙江省宁波市发展和改革委员会主任）
    　　
    王平安（回族，武警浙江省总队总队长）
    　　
    王永明（浙江省人大常委会副主任）
    　　
    王　鸣（民进浙江省杭州市副主委、杭州市第一人民医院肾内科主任）
     
    浙江籍全国政协委员 徐冠巨（浙江省政协副主席，浙江省工商联合会会长 13905817665）

**Comment by honky-tonk** [comment]
我可以用微信去搜一搜吗
