### ISSUE TITLE
还没下班的来聊聊你们觉得这次这个项目能撑多久？

### ISSUE THREAD

**Issue by wjh4dev** [996icu/996.ICU#16342]
![55126906-64f8cc00-5149-11e9-951f-8e94a4dde728](https://user-images.githubusercontent.com/29775367/55162095-04e24400-51a2-11e9-8c04-a074de6ec943.png)

**Comment by ZWYxKwbEkcA3WLXhKWso** [comment]
估计会有人约谈项目发起者
