### ISSUE TITLE
希望出非996公司名单！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

### ISSUE THREAD

**Issue by zzce** [996icu/996.ICU#16383]
**希望出非996公司名单！！！
希望出非996公司名单！！！
希望出非996公司名单！！！**

非996公司，Please！！！
非996公司，Please！！！
非996公司，Please！！！

**Comment by kongwang** [comment]
955.wlb 不是已经有了么

**Comment by gitqh** [comment]
有一个955.WLB的项目，可以关注一下

**Comment by zzce** [comment]
好多人不知道啊啊啊啊啊啊啊啊

**Comment by swuecho** [comment]
[投票](https://cloudqa.iego.cn/sr/icu996)

[添加](https://cloudqa.iego.cn/sr/icu996)


<img width="514" alt="Screen Shot 2019-03-28 at 12 43 36 AM" src="https://user-images.githubusercontent.com/666683/55138002-60dea580-516d-11e9-9b67-4d92ba72903c.png">

[公司名单](http://blog.meihao.us/icu996_poll_result/)

<img width="798" alt="Screen Shot 2019-03-28 at 4 55 01 PM" src="https://user-images.githubusercontent.com/666683/55143726-4a8b1680-517a-11e9-9264-191c902497df.png">

[参与开发](https://github.com/swuecho/icu996_poll_result)

可以基于调查结果做可视化，分析等


[JSON数据](http://122.112.218.148:15666/v_answer)

可以用来做二次开发

**Comment by swuecho** [comment]
公司名单里面Q4 = 3或者是2 的就是
