### ISSUE TITLE
,请大家点进来看看知乎的评论,说的很有道理

### ISSUE THREAD

**Issue by z231485** [996icu/996.ICU#16395]
知乎用户
189 人赞同了该回答
星星之火，可以燎原。群众基础是有的。

从issue的评论看，程序员仍然是个缺乏政治意识的群体。

1) 仍然停留在抱怨的阶段，很少有人提出自己的核心诉求。

2) 内部面临着分化。如“市场决定论”思想，如有人问“谁来发工会主席的工资”。这些仍然是大家思想上的大敌。

3) 警惕一些别有用心的人，不要让一颗老鼠屎坏了一锅好粥。我们维护劳动者的权利，要懂法知法依法守法，一切在法律允许的范围内进行。

4) 团结意识仍然不够。比如运营狗产品狗也是996的受害者，他们也愿意声援程序员的运动，但他们目前来看参与度不够。所以一方面要考虑如何团结他们，另外一方面，也要去团结其他有类似诉求的人。

从认识到实践，还有很长的路要走。思想上的觉醒也许只是一时兴起，现实生活中的利益考量，短期收益与长期收益的取舍，个人、家庭的事情怎么处理，这些都是大家的切身利益，需要静下心来好好想想。这是劳动者维护自身权益的一切行动的基础。

团结就是力量！

编辑于 18:52
​赞同 189​
​17 条评论
​分享
​收藏
​感谢
知乎用户
知乎用户
82 人赞同了该回答
首先写在最前面的就是: 这个行为是值得肯定的 ,是大家反抗资本家的第一步
关于资本家吃肉喝血的不多说了 大家心里都有数 :大家努力996 明年老板还能换上一辆新车

但是这只是个开始,现在只是数的过来的几家公司明面996 , 往后会更多的 ,资本家们一看这帮软柿子996也没脾气,资本家在垫脚效应面前能忍得住???于是就会慢慢尽数996 ,然后也许会有胆子大的公司去试探10 10 6 , 不要犯 ” 一开始我不说话 因为我没有996 , 后来我996了 但是已经没有人能替我说话了”这种错误.

我觉得 斗争的对象不仅仅是资本家 还有那些持有反抗无用论、点星星无用论的人们 , 现在这个阶段 点星星 发帖吐槽自然是无用的 , 但是不这样积攒大家的怒火 ,难道立刻能组织起来全国996程序员一起罢工辞职请愿吗?谁有这个能量?

先有星星之火 才能燎原 而不是人家拿出来火苗 你说”这点小火还能燎着草原? ”说完风凉话然后拍拍屁股走了

所以既然做不到这个 也就不要阻挡别人发声的权利

愿中国程序员都摆脱冷气,只是向上走,不必听自暴自弃者流的话.能做事的做事 , 能发声的发声 , 不必等候炬火,若此后没有炬火 ,我便是唯一的光 , 我们可以卑微入尘土 不可扭曲如蛆虫 .

**Comment by Yu-Shuyi** [comment]
同意。最主要的就是核心诉求一定要严格限制在根据国家法律于保障工人权利的范围内，一旦扩大化就会很麻烦。最怕就是被别有用心的人利用，被不同的资本集团枪使，那才是最可悲的。
