### ISSUE TITLE
996不行可以不干啊，中国这么多人。。这是市场决定的

### ISSUE THREAD

**Issue by jiankian** [996icu/996.ICU#1678]

**Comment by coldfog** [comment]
市场决定的么？工业革命后的童工，超负荷的劳动，被剥削的工人。那不也是当时的市场决定的么？

**Comment by coldfog** [comment]
然后你告诉人家说不行可以不干？这给我的感觉就像是觉得生儿子才是传宗接代的老奶奶一样。

**Comment by jiankian** [comment]
可怜弱者总是抱怨社会的这样那样的不公，几千年来人类社会，几万年来大自然丛林法则，可曾有过公平。。

**Comment by RekiDunois** [comment]
是自己开issue然后自己关的屑
