### ISSUE TITLE
光说不做,回头不还是闭嘴加班?一群弟弟.

### ISSUE THREAD

**Issue by JasmineXiaozzz** [996icu/996.ICU#16856]

**Comment by LittleChengxuYuan** [comment]
祝你永远做一个顺服的小绵羊

**Comment by JasmineXiaozzz** [comment]
> 祝你永远做一个顺服的小绵羊

看,程序员还爱互相攻击,哥哥已经裸辞转行了,你们慢慢伺候傻屌老板吧 @LittleChengxuYuan

**Comment by LittleChengxuYuan** [comment]
转行还来这里找存在感？有病？

**Comment by JasmineXiaozzz** [comment]
> 转行还来这里找存在感？有病？

so你呢?除了能在这里点个star,你对抗议996又做了啥?明天睡醒敢怼让你996的boss不?敢换一个不是996的工作不?敢自己创业不让员工加班不?你要是敢我才服你:-)

**Comment by LittleChengxuYuan** [comment]
6，厉害厉害厉害，大佬牛逼。不敢说话

**Comment by cdr-dave** [comment]
说话都不给，有点恐怖啊
