### ISSUE TITLE
起来，不愿做奴隶的人们！把我们的血肉筑成我们新的长城！中华民族到了最危险的时候，每个人被迫着发出最后的吼声，起来！起来！起来！我们万众一心，冒着敌人的炮火，前进！冒着敌人的炮火，前进！前进！前进！进！ 

### ISSUE THREAD

**Issue by ShuaiShuaiLee** [996icu/996.ICU#16861]
起来，不愿做奴隶的人们！把我们的血肉筑成我们新的长城！中华民族到了最危险的时候，每个人被迫着发出最后的吼声，起来！起来！起来！我们万众一心，冒着敌人的炮火，前进！冒着敌人的炮火，前进！前进！前进！进！

**Comment by nilmeme** [comment]
老哥，稳

**Comment by qq260327056** [comment]
1886年的5月1日, 美国芝加哥20多万工人举行大罢工,要求实行每天8小时工作制。
我们要同等的权利！

**Comment by Zam233** [comment]
起来，饥寒交迫的奴隶
起来，全世界受苦的人
满腔的热血已经沸腾
要为真理而斗争！
