### ISSUE TITLE
拿出实际行动来，用技术捍卫我们的权益。《区块链996名单白皮书》【求补充】

### ISSUE THREAD

**Issue by zhoushuren** [996icu/996.ICU#16902]
#16688 的想法和我不某而合，我在白天想了一下午
看到有的人提出的解决方案，什么拿起法律的武器，都是扯淡。

先说问题是怎么产生的，问题就是大家不团结，面对996的公司大家不敢说罢工，不敢正面怼资本家，在GitHub issue来发泄情绪是没用的。这个项目估计只能火这么一段时间，过段时间热度过了大家还是该加班加班。

我的想法是大家可以一起做款DApp（去中心化的应用）来收录996系公司，以及良心企业。
有了这款DApp，面试者在面试前只需要搜一下要面试的公司就知道公司是否为996系公司。
只要数据足够多，大家足够团结，踊跃在DApp上披露996公司，记录在区块链里。任何人或组织都无法操控这些数据，可以做到绝对真实。而公司上了黑名单将面临招人难的问题，以此威慑公司。

具体做法： 
    
1.  我的初步想法是做打分机制。
    账号系统的问题，如何防止不良用户马甲号恶意中伤良心企业？
    可以选择GitHub活跃多的大佬来做种子用户，新用户必须通过其他用户认证才有投票权重，种子用户的权重最高，被很多有权重用户认证过的账号权重也相应提高，这一切基于加密算法实现。
2.  如果公司认识到错误，改过自新怎么办？
答： 花钱呗，犯错误是要付出代价的，以购买token的形式把被扣的分提上去，但是历史记录还是在的。
3. token从哪来？
token是对这个项目原始贡献者以及矿工的奖励。

这只是个人想法，不喜勿喷。最见不得说风凉话的。看到 #16688  下面一些喷子，我只能说你活该996. 

4. 被封问题，项目可以是开源的前端代码+底层链，任何人都可以同步完区块后自己部署一套。服务器放墙外。

同时：希望大家能在下面对这个想法提出疑问，以及解答疑问，完善这个想法。技术方案还没想好，但是我知道一定可以实现的，希望我能看到实现的那一天。欢迎大佬补充。

**Comment by Alan110** [comment]
实际的行动才是最靠谱的，顶一手

**Comment by Alan110** [comment]
如果用钱就能提高分数，会不会还是有空子可钻，还是可收买。 
打分代表的是员工的真实感受，企业改变是好是坏，最直观感受的也仍然是员工，所以是否可以每隔一段时间由员工重新对这家公司打分

另外，github活跃的大佬是否会企业收买这很难说。由人来控制权限发放的机制，迟早会腐败。这种评分权限的授予机制得是一个公平的、不受干扰的机制。 其实这个问题有点像怎么样真实可靠的选出人大代表。

**Comment by zhoushuren** [comment]
@Alan110 要做到完全去中心化，我觉得是不太可能的，不然你觉得通过什么方式注册能解决马甲号问题？
企业交了钱并不代表没事了，只是交了钱后分数上去了，并不影响后续打分。如果继续996，还是会有人打分把分数扣下。

企业可能会收买一两个GitHub大佬，但是无法收买很多个。一个大佬授权的权重有限。其实可以跟抱团取暖一样相互认证对方是程序员，是一个星型的结构体系。没有100%的不能发杜绝马甲号，但是可以加大注册大量马甲号的成本。

最后，为什么要让企业交钱，就像交警开罚单一样，有犯罪成本。罚的钱归执法者的工资。
没钱，项目是无法运作下去的。让大家众筹钱不太可能，只能通过罚款了。

**Comment by Foxtile** [comment]
让企业花钱，钱给谁？
你真要做，就历史记录绝对不可更改。
企业改过自新，新的评分足够多足够好自然会逐渐拉高平均分。
但其实也没用。之前某招聘app有类似功能，所有企业都一片差评你怎么办？说白了资本家团结起来坑你，你不工作？还不得乖乖找一家干....而团结资本家比团结无产阶级容易太多了。一群人出于利益步调一致很容易，让一群无产阶级无视利益步调一致那是自欺欺人。

**Comment by Foxtile** [comment]
以个人更邪恶的想法...其实可以搞个bug节之类的...类似人家罢工不过更隐蔽一些。在某一天（1024？）大家都到生产环境搞出一些bug热闹热闹。看谁的花里胡哨而且不能给提前发现~

**Comment by zhoushuren** [comment]
@Foxtile 企业向token持有者购买token啊。token持有者是对项目有贡献的人。
除了黑名单之外还有白名单机制。良心企业也会被认可，引导市场良性竞争，有些公司为了吸引人才可以做良性企业认证，打分高。最终可以是一个公正的招聘社区。传统app可能迫于生存压力制作假数据，删除不良数据，但是区块链里伟大的加密算法不会说谎。

**Comment by zhoushuren** [comment]
@Foxtile 其实真正的技术牛的人在招聘市场上是供不应求的，可是为什么从经济学上来说依然被动？那是因为这个市场在恶化，工人是弱势群体，信息不对称，我不知道哪家公司不996。
世界上没有良心公司，可以说人没有善恶之分，只有利益的攀比。举个例子，张三跟李四两家公司发展条件饱和了，很难找突破口的时候，张三家公司尝试996得到了利益，战胜了李四家公司，李四家公司不敌，所以也只能996，这就导致了所有公司都996。

那如果信息透明了，求职者知道哪家不996，哪家是996，在待遇相同的前提下自然避开996的公司，导致996公司无招人困难。那么996公司采取的措施就应该是向好的方向攀比从而吸引人才加入。

**Comment by eifoj** [comment]
还不如录入一次信息交个10块钱，这样既减少中心化降低曝光门槛，企业想要提高分数也要花真金白银

**Comment by Doralle** [comment]
好点子，持续关注中。如果发起众筹，也不一定不成功。

**Comment by zhoushuren** [comment]
@eifoj 直接花钱，你你们公司的竞争对手想搞垮你公司就直接花钱砸死你公司。你们公司想洗白再砸钱，最后变成拼钱的游戏了。
这个项目拼的是人品，（应该叫司品）。司品是靠群众来检验的。
打分的好处是，可以负面打分，也可以正面打分来抵消负面。
权重高的用户打的分越有效。相信权重高的用户种很少有失德之人乱来。大家都是无产阶级

**Comment by eifoj** [comment]
@zhoushuren 我想的是将工作时间，加班情况，福利待遇，工作环境这些信息具体地曝光出来，通过一个比较公平的公式算出评分。如果想要有影响力，就应该让更多各行各业的无产阶级参与进来。而且权重高的用户实际上不会去很多家公司，未必能反应真实情况。

**Comment by zhoushuren** [comment]
@eifoj 通过公式算评分，好主意，但是先只能从互联网行业入手，如果成功了，然后慢慢渗透各行各业。
「而且权重高的用户实际上不会去很多家公司，未必能反应真实情况。」这个问题，其实是这样的，小权重用户a检举公司A。影响力虽不大，但是可以邀请前同事，或者认识技术群，或者社区的人来一起吐槽，一起打分。

**Comment by eifoj** [comment]
@zhoushuren 打分应该独立出来，可以通过赞同、反对的方式影响每条信息占公司评分的权重，通过评论进行补充说明

**Comment by wyswill** [comment]
有没有原型产品呢？

**Comment by jacobjiangwei** [comment]
真正的做法应该是编辑制作
类似米其林的美食点评
用暗访的方式去记录每家公司

**Comment by emilytimer** [comment]
豆瓣就是原型，照着改改就好了。开始防水军就用年活跃度。
可视化部分搞个折线图啊，像股票的图一样，月度走势，年度走势都能直观看出来。

**Comment by RayKim1006** [comment]
关于开发用于劳动过程证据固定的公益DAPP的倡议及初步设想
https://github.com/996icu/996.ICU/issues/18514

**Comment by RayKim1006** [comment]
核心其实不是打分，因为打分是可以刷的。
只有和用户切身利益绑定，且能够为平台带来一定程度收益的才可能有生命力。

**Comment by lxiaodao** [comment]
我刚要写一个建议区块链996，就看到你了。先不说多了，快点组织起来，我参加。我自认为对区块链很熟悉了，搞起来有影响力了再完善。我建议先建立一个组织，叫996.icu基金会什么的，先搞起来。

**Comment by ougato** [comment]
游戏前端开发，愿意参与

**Comment by robbertzhang** [comment]
为什么close?
