### ISSUE TITLE
票投韩国瑜，台湾发大财 taiwan2020.github.io

### ISSUE THREAD

**Issue by taiwan2020** [996icu/996.ICU#16923]
[taiwan2020.github.io](https://taiwan2020.github.io/)

猜总统，拿奖金
建立在 EOS 区块链合约上的 2020 台湾总统选举

**Comment by qq260327056** [comment]
你妈的，能不能不发你们台湾的东西，要独立就独立去，大陆没空理你们。

**Comment by DongFangWuShuang** [comment]
> 你妈的，能不能不发你们台湾的东西，要独立就独立去，大陆没空理你们。

快笑死我了

**Comment by AugustWong** [comment]
为什么不能选择习大大？
