### ISSUE TITLE
我们可以做的更多

### ISSUE THREAD

**Issue by xiangwf** [996icu/996.ICU#16921]
既然本次抵抗996的活动已经逐渐壮大了，是否可以考虑进一步的措施了呢？1.是否可以@大 V，@人权组织，@著名人物以及扩大到国内外尽可能的社交媒体等方式将活动进一步扩大化;2.是否可以将诉求具体化，并将其呈交给相关机构;3.是否可以将这次活动的成果不仅仅只留于表面口嗨，而采取措施落实到实处，加颗星是无法解决问题的。4.抵制996，是否可以扩大人群，联合其他群体来加深影响。
最后，抵制996，不进ICU.愿大家都能为自己的权益发声！！！

**Comment by helsonxiao** [comment]
你可以直接罢工，和支持的同事一起，只是在休息时间不工作而已，没有那么难。
