### ISSUE TITLE
 习大大选总统 taiwan2020.github.io

### ISSUE THREAD

**Issue by taiwan2020** [996icu/996.ICU#16962]
# 维尼维尼得第一

[taiwan2020.github.io](https://taiwan2020.github.io)

猜总统，拿奖金
建立在 EOS 区块链合约上的 2020 台湾总统选举

**Comment by modi12jin** [comment]
韩流

**Comment by taiwan2020** [comment]
![photo6116118659291261074 (1)](https://user-images.githubusercontent.com/47896577/55179538-a083ac80-51c2-11e9-838e-e8265d4b78e5.jpg)

**Comment by kylesean** [comment]
@taiwan2020 say 666 to you!!!

**Comment by taiwan2020** [comment]
![f6R0GSpFKpGkpE8tNuNm](https://user-images.githubusercontent.com/47896577/55179764-1ee04e80-51c3-11e9-845c-7a685d31ae34.jpg)

**Comment by Cappuccino2014** [comment]
你这是在作死

**Comment by taiwan2020** [comment]
湾湾绝不996，人肉翻墙过来吧

**Comment by GodDai** [comment]
**？？？脑子有问题吧 在这里发政治**
