### ISSUE TITLE
依图招聘前端，后端，产品经理及算法开发人员

### ISSUE THREAD

**Issue by LRL-A** [996icu/996.ICU#1697]
依图与商汤，face++，云从并称计算机视觉四小龙。业务主要包括安防，医疗，智能（金融，商业，BI），语音识别等领域。高层来自于阿里云团队，技术实力雄厚，在各大国际比赛中表现优异（ACM、FRVT 冠军）。要求代码能力强，经验值2-7年，公司前景广阔，待遇非常优厚！如果感兴趣请加微信13501125963详聊

**Comment by kajweb** [comment]
996吗？准时下班吗？

**Comment by Ling-Jing** [comment]
这么晚发招聘，快说是不是刚下班

**Comment by LRL-A** [comment]
> 这么晚发招聘，快说是不是刚下班

😄，这位朋友很风趣～

**Comment by light0x00** [comment]
这怕不是9912吧

**Comment by wangpengcheng** [comment]
这个点发招聘，说好的996呢？

**Comment by like3107** [comment]
招暑期实习生吗= =研一暑期想回国干两三个月，比较擅长python

**Comment by LRL-A** [comment]
> 招暑期实习生吗= =研一暑期想回国干两三个月，比较擅长python

欢迎加微信私聊
