### ISSUE TITLE
说说自己对996的看法

### ISSUE THREAD

**Issue by ysy950803** [996icu/996.ICU#16980]
首先表明态度，对996，**不赞成** 。
姑且先不说什么劳动法了，就我所经历的来看，大部分996的人，工作效率都比较低。明明两天能做完的需求估工期可以估四天，然后白天划水，晚上吃了饭回来吹吹逼，再写写代码，九十点钟撤。其实需求还是没做完，质量还低，Bug一堆。
我相信很多人已经养成了这种加班的习惯，反正对他们来说，单身一个，在家也是上网，在公司也是上网，都差不多，早点晚点回去无所谓，甚至如果某些公司给加班费，那这种现象就更疯狂了，混也要混到九点下班。
然后，刚来的实习生或者刚毕业的应届生，在这种环境下，就会被传染，因为他们也不好意思那么早下班。
最终加班文化就这样代代相传地形成了，管理层会跟风，认为只有靠加班这种方式才能提高生产力，殊不知人类的本质，要混的人你让他7×24小时工作他也只会做那点量的事，真的热爱技术热爱工作的人，加不加班他都会抽时间提高自己，为公司带来更好的业绩。
其实大家扪心自问，你加班真的做了更多的事吗？如果按小时来算，你真的为公司带来了更多效益吗？
我可以说，如果你在白天全神贯注认认真真地写代码，少撩妹少吹逼少水群，你白天正常工作时间就能做完该做的事情。你也没必要为了显得自己很忙去加班，去拖延工期。中国这些互联网企业真的是病态的，下班下早了，管理者会认为你事情做少了而不是效率高了，于是就无休止地压榨，码农们为了保卫自己的咸鱼生活，就想方设法地划水，如此造成恶性循环。所以说，996的始作俑者不仅有那些不懂管理的老板，也有我们这些混子码农自身的原因。
真正的受害者是谁？
第一就是公司，说得不好听点就是养了一群表面努力的蛀虫。
第二就是有家庭的人，他们的时间被无理由压榨，缺少了给家人的陪伴，到头来幸福感降低，孩子不认爹，老婆跟人跑，结果工资并不会因为996而带来显著提升。
第三就是初入职场的小白，他们本应该在高效完成本职工作后，享受属于自己为数不多的晚间时光，这几个小时完全可以用来学习提升自己，不管是知识还是健康上的，最后良性循环，身体越来越好，技术水平也越来越高，而不是加班划水写垃圾代码。当寒冬来临才发现，加的那些班，并不会给你编织一件保暖衣。
最后，我也不否定有创业公司筚路蓝缕，非常艰辛的，初期需要投入大量人力做事情，但那也一定不会是常态，不应该成为一种风潮。
很多人可能也会说，你不加班，你累死了，总有人补上，不缺你一个。是，你说得对，长江后浪拍死前浪，但这又回到了最开始的问题，正因为这些欣然接受996的人来顶替这个位置，才会有无良管理者的肆无忌惮。
同学们，劳动者的尊严是劳动者自己捍卫的，就因为中国码农多，所以不应该享有法律给予的权利吗？这就是为什么中国互联网没有真正伟大的公司，因为都是血汗工厂，是反人类的。人类要进步应该是提高生产效率，而不是反其道而行之。也希望各位老板们能看清楚996的本质。
总之，其百害而无一益。

**Comment by LucyVictor** [comment]
是的，加班是学习效率最低，身体伤害最大的一种方式，愿所有开发都能被岁月温柔以待

**Comment by zhoushuren** [comment]
我已经提出了技术的解决方案，大家可以看看 #16902 
楼主说的很客观。
我再补充一点，还有一些员工完全是被洗脑的。我几十年来一直很费解的一件事是，人怎么会被洗脑，包括有的人为什么就相信宗教。人家说说你就信？

有的公司就是给员工洗脑，向员工灌输扭曲的价值观，让员工认为加班才是正常的，不加班是不正常的。

我以前曾经入职一家创业公司，我加班到8点半下班。电梯口遇到老板。老板说你怎么不加班？我只是笑了笑说事情做完了。我心里再想，我8:30走难道还不算加班？果断离职了。
