### ISSUE TITLE
依图（北京和上海）招聘前端，后端，产品经理，及算法开发人员

### ISSUE THREAD

**Issue by LRL-A** [996icu/996.ICU#1699]
依图（北京和上海）招聘前端，后端，产品经理，及算法开发人员。依图与商汤，face++，云从并称计算机视觉四小龙。业务主要包括安防，医疗，智能（金融，商业，BI），语音识别等领域。高层来自于阿里云团队，技术实力雄厚，在各大国际比赛中表现优异（ACM、FRVT 冠军）。要求代码能力强，经验值2-7年，公司前景广阔，待遇非常优厚！如果感兴趣请加微信13501125963详聊

**Comment by EscapeFromCoding** [comment]
在这里招人，怎么也得承诺个965吧

**Comment by abramyangCN** [comment]
招应届毕业生吗
