### ISSUE TITLE
此项目证明无产阶级从以前的工人农民换成了广大码农

### ISSUE THREAD

**Issue by iamybj** [996icu/996.ICU#17031]
此项目证明无产阶级从以前的工人农民换成了广大码农。但是这个无产阶级阶层，虽然有些懦弱胆小怕事，也有爆发的一天。我们应该依靠互联网，建立起全球超越国家边界的联合组织，相互声援，相互支持。

顺便曝光携程梁建章这个道德败坏的人旗下途家网，996和加班不给加班费，哥为了和它打官司失业半年了。这两天就去最高院申请复审。
![WechatIMG7](https://user-images.githubusercontent.com/1802494/55197959-261d5180-51ef-11e9-8754-576cfbbf7d13.jpeg)
![WechatIMG8](https://user-images.githubusercontent.com/1802494/55197960-274e7e80-51ef-11e9-8505-c66fd881d534.png)

**Comment by HolyChen** [comment]
只是证明了曾经高高在上自诩为中产、高收入群体的成员，只不过也是工人阶级的一部分。

**Comment by iamybj** [comment]
可以把 996.icu建立成全世界工程师支援网站，发展成类似西方共济会，共济会就是当年工匠石匠等技术人员建立的组织。

**Comment by yuankk8** [comment]
工程师也是工人
