### ISSUE TITLE
建立成立中国共济会，用互联网技术改变控制世界

### ISSUE THREAD

**Issue by iamybj** [996icu/996.ICU#17041]
建立成立中国共济会，用互联网技术改变控制世界。
西方共济会，就是当年的石匠工匠科学家自己组织的一个会，据说伽利略还是他们的头目。
中国码农不仅代替了工人农民成了无产阶级，而且还掌握计算机和互联网技术，完全有能力建立起超越国家边界的新共济会。

顺便曝光无耻携程旗下途家网996而且不给加班费。
![WechatIMG7](https://user-images.githubusercontent.com/1802494/55197959-261d5180-51ef-11e9-8754-576cfbbf7d13.jpeg)
![WechatIMG8](https://user-images.githubusercontent.com/1802494/55197960-274e7e80-51ef-11e9-8505-c66fd881d534.png)

**Comment by diverger** [comment]
重量级神秘嘉宾是谁？

**Comment by iamybj** [comment]
> 重量级神秘嘉宾是谁？

梁建章啊，就是那个少年班的畸形怪胎，本来也是老码农的，给外国公司在中国做技术支持的垃圾。
