### ISSUE TITLE
有没有成都的程序员小哥哥可以勾搭呀(*∩_∩*)

### ISSUE THREAD

**Issue by cherryzhang1023** [996icu/996.ICU#1704]
这里有运营萌妹纸一枚，请查收~

靠实力加班的运营+设计搬砖狗🤣🤣

**Comment by LALINUX2019** [comment]
**收！**

**Comment by ilsl1007** [comment]
此issues必火。。

**Comment by showkiwi** [comment]
小姐姐，我们来勾搭一下吧

**Comment by duzhongyu** [comment]
来撕

**Comment by duzhongyu** [comment]
美的

**Comment by cherryzhang1023** [comment]
刚刚玩这个，怎么回复帖子啊，🤣闹心

**Comment by LALINUX2019** [comment]
没图说个鸡脖？

**Comment by g8up** [comment]
@cherryzhang1023 你好像不会 git，我们不约！

**Comment by ChenBerlin** [comment]
成都某校学生表示围观

**Comment by LALINUX2019** [comment]
邮箱 la592213965@gmail.com 

**文明交友**

**Comment by cherryzhang1023** [comment]
明天研究怎么发吧，学历背景是川音传媒专业，半文半艺。毕业从了互联网，新媒体搬砖狗🤣

**Comment by wangpengcheng** [comment]
没图没真相

**Comment by MaybeMirracle** [comment]
为盖楼添砖Java
同成都，来一波文明交友，走起

**Comment by JesseXia** [comment]
> 这里有运营萌妹纸一枚，请查收~
> 
> 反正长的还算可爱啦^_^
> 
> 靠实力加班的互联网运营+设计搬砖狗🤣🤣

要火啊妹子

**Comment by Ccccche** [comment]
插眼！

**Comment by leon0625** [comment]
环球中心码农来报道

**Comment by xjr7670** [comment]
兹磁

**Comment by INTERESTING-OMG** [comment]
目测要火

**Comment by brelian** [comment]
你个糟老头子，

**Comment by bobo826** [comment]
请联系我zb826922

**Comment by qq398935137** [comment]
运营也要用github？

**Comment by chai-chai** [comment]
无图无真相

**Comment by FindView** [comment]
妖孽哪里逃，看老衲收了你~~~

**Comment by wuming12335** [comment]
[无图言甚][https://p1.ssl.qhmsg.com/t01cb7b9739d9209628.jpg](url)

**Comment by wuming12335** [comment]
你个糟老头子坏得很~

**Comment by Wjj954628981** [comment]
震惊！全球最大同性交友网站混进了一些不得了的东西

**Comment by cherryzhang1023** [comment]
![QQ浏览器截图20190328104823](https://user-images.githubusercontent.com/48997833/55126400-e8192280-5147-11e9-90c1-5a445a0bf5b3.png)


卧槽，不知道怎么贴内回复，泪奔佬！！！

**Comment by cherryzhang1023** [comment]
> 妖孽哪里逃，看老衲收了你~

网页版好用多了嘛

**Comment by cherryzhang1023** [comment]
> 震惊！全球最大同性交友网站混进了一些不得了的东西

哈哈哈哈一起来搞基啊

**Comment by cherryzhang1023** [comment]
> 你个糟老头子，

搞基搞基搞基！！！

**Comment by cherryzhang1023** [comment]
> 此issues必火。。

嘻嘻嘻~~~~

**Comment by cherryzhang1023** [comment]
> @cherryzhang1023 你好像不会 git，我们不约！

哈哈哈看来你们还是适合跟键盘一起玩儿~O(∩_∩)O~

**Comment by cherryzhang1023** [comment]
> > 这里有运营萌妹纸一枚，请查收~
> > 反正长的还算可爱啦^
> > 靠实力加班的互联网运营+设计搬砖狗🤣🤣
> 
> 要火啊妹子

不是搅基平台了吗哈哈哈

**Comment by cherryzhang1023** [comment]
> 为盖楼添砖Java
> 同成都，来一波文明交友，走起

哈哈为降低大成都单身率而奋斗⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄

**Comment by wenfengtou** [comment]
婚前留名。

**Comment by wenfengtou** [comment]
婚前留名。

**Comment by wenfengtou** [comment]
婚前留名。

**Comment by wenfengtou** [comment]
婚前留名。

**Comment by FindView** [comment]
这里有Android汉子一枚，请查收~

反正长的还算不怎么样啦^_^

靠实力加班的Android开发+ 支持搞基~~~

**Comment by cherryzhang1023** [comment]
> 婚前留名。
意思是马上要婚后了吗哈哈

**Comment by cherryzhang1023** [comment]
> 这里有Android汉子一枚，请查收~
> 
> 反正长的还算不怎么样啦^_^
> 
> 靠实力加班的Android开发+ 支持搞基~~~

哈哈哈，这个平台的程序员小哥哥好精准诶。

**Comment by OracleRubyRose** [comment]
![微信图片_20190328113116](https://user-images.githubusercontent.com/16449385/55128008-06cde800-514d-11e9-8727-a35e462ec27e.jpg)

**Comment by cherryzhang1023** [comment]
> 这里有运营萌妹纸一枚，请查收~
> 
> 反正长的还算可爱啦^_^
> 
> 靠实力加班的互联网运营+设计搬砖狗🤣🤣

**Comment by jypleo** [comment]
我去居然在这看到你，世界真的太小了

**Comment by wangshanqiang** [comment]
有没有成都小姐姐可撩的

**Comment by Peakchen** [comment]
勾撩

**Comment by cherryzhang1023** [comment]
> 我去居然在这看到你，世界真的太小了

吉普罗~~~~

> ![QQ浏览器截图20190328104823](https://user-images.githubusercontent.com/48997833/55126400-e8192280-5147-11e9-90c1-5a445a0bf5b3.png)
> 
> 卧槽，不知道怎么贴内回复，泪奔佬！

**Comment by cherryzhang1023** [comment]
> 我去居然在这看到你，世界真的太小了

哈哈哈难道是熟人吗，快溜！！！

**Comment by jypleo** [comment]
> > 我去居然在这看到你，世界真的太小了
> 
> 哈哈哈难道是熟人吗，快溜！

你对面学校的

**Comment by cherryzhang1023** [comment]
> 这里有运营萌妹纸一枚，请查收~
> 
> 反正长的还算可爱啦^_^
> 
> 靠实力加班的互联网运营+设计搬砖狗🤣🤣

**Comment by cherryzhang1023** [comment]
> > > 我去居然在这看到你，世界真的太小了
> > 
> > 
> > 哈哈哈难道是熟人吗，快溜！
> 
> 你对面学校的

也姓张那个吗？！！！！

**Comment by jypleo** [comment]
> > > > 我去居然在这看到你，世界真的太小了
> > > 
> > > 
> > > 哈哈哈难道是熟人吗，快溜！
> > 
> > 
> > 你对面学校的
> 
> 也姓张那个吗？!!!!

嘿嘿嘿，这种问题怎么能告诉你，溜了，你加油

**Comment by cherryzhang1023** [comment]
> > > > > 我去居然在这看到你，世界真的太小了
> > > > 
> > > > 
> > > > 哈哈哈难道是熟人吗，快溜！
> > > 
> > > 
> > > 你对面学校的
> > 
> > 
> > 也姓张那个吗？!!!!
> 
> 嘿嘿嘿，这种问题怎么能告诉你，溜了，你加油

妈蛋，不带这么坑的！要自闭佬~

**Comment by fujiazhang** [comment]
笑看一群舔狗。

**Comment by fujiazhang** [comment]
![image](https://user-images.githubusercontent.com/11347639/55131477-bad57000-5159-11e9-8761-31a96c38444c.png)

**Comment by fujiazhang** [comment]
![image](https://user-images.githubusercontent.com/11347639/55131505-d771a800-5159-11e9-8068-6e1a71453580.png)

**Comment by cherryzhang1023** [comment]
老哥，脱单才是根本诶。既然都是加班狗，不主动更没有机会T-T

**Comment by fotock** [comment]
https://github.com/fotock/996Board
提交996企业，让我们举手制止

**Comment by fujiazhang** [comment]
> 老哥，脱单才是根本诶。既然都是加班狗，不主动更没有机会T-T

老婆说的对，咱手牵手回家吧。

**Comment by DLLjy** [comment]
借楼，哈哈哈哈哈哈

**Comment by brelian** [comment]
> > 你个糟老头子，
> 
> 搞基搞基搞基！！！
我信你个鬼!!!

**Comment by fujiazhang** [comment]
> 不信就算了，一起注孤生吧

老婆我信，老婆说的对，咱手牵手回家吧。

**Comment by edqick** [comment]
我啊，我啊。顺便一提，python才是世界上最好的语言！

**Comment by CoderYanKang** [comment]
孵化园

**Comment by HuaHuaHuaHe** [comment]
🐂🍺

**Comment by xt998** [comment]
图嘞🙃

**Comment by xiaohuwu** [comment]
围观中。。。。

**Comment by mymusise** [comment]
小姐姐你是来挖人的吧

**Comment by lixiaohu123** [comment]
看来码农舔狗居多呀。

**Comment by huayintianlai** [comment]
金融城码农报到

**Comment by cherryzhang1023** [comment]
> 金融城码农报到

这帖子不是被关了么！

**Comment by fujiazhang** [comment]
不要把这个当成帖子，这个不是帖子，github也不是论坛，不要回复了。谢谢！连github都不知道做什么的，别瞎几把凑热闹了。别回我了 不想收到邮件了。
