### ISSUE TITLE
软弱的程序员阶级，不能带领中国走向现代化

### ISSUE THREAD

**Issue by liyonghelpme** [996icu/996.ICU#17108]
中国有大量新兴的程序员。但是他们似乎没有成为推动社会的力量，没有成为有社会组织力量的一群，也没有多大的愿望。
实力弱小，下不能团结劳苦大众，上没有谈判资本，革命的领导者注定不能是软弱的阶级

**Comment by liuqinglong110** [comment]
程序员不软弱，大家删库跑路，反正哪里都不好过。

**Comment by lhf686868** [comment]
全国程序员一起联合起来罢工3天会怎样
