### ISSUE TITLE
秀才造反，三年不成

### ISSUE THREAD

**Issue by Wolfire** [996icu/996.ICU#17161]
秀才的初衷是要反他娘的，经过三年的谋划，还是老老实实当个教书匠。虽然有法可依，可是违法犯罪成本低到令人发指，可维权成本又高到让人望而却步，有毛用？

**Comment by xxllp** [comment]
秀才只要发动群众才能真的行

**Comment by gagayuan** [comment]
来到集上，见范进正在一个庙门口站著，散著头发，满脸污泥，鞋都跑掉了一只，兀自拍著掌，口里叫道：“中了！中了！”胡屠户凶神般走到跟前，说道：“该死的畜生！你中了甚么？”一个嘴巴打过去，众人和邻居见这模样，忍不住的笑。不想胡屠户虽然大著胆子打了一下，心里到底还是怕的，那手早颤起来，不敢打第二下。范进因这一个嘴巴，却也打晕了，昏倒于地，众邻居齐上前，替他抹胸口，捶背心。弄了半日，渐渐喘息过来，眼睛明亮，不疯了。众人扶起，借庙门口一个外科郎中姚驼子的板凳上坐著，胡屠户站在一边，不觉那只手隐隐的疼了起来。自己看时，把个巴掌仰著，再也弯不过来；自己心里懊恼道：“果然天上文曲星是打不得的，而今菩萨计较起来了！”想一想，更疼得狠了，连忙问郎中讨了个膏药贴著。

**Comment by sapuser2017** [comment]
毛泽东不也是个教书匠么

**Comment by yajw** [comment]
怎么才能成呢
