### ISSUE TITLE
996为什么是问题？我一直都是15x7啊，你是把工作当成了工作，并没有当成事业，才会有次抱怨，你对所做的事情缺乏敬畏之心，要付出不亚于任何人的努力，不光是付出时间，还要不断学习思考，提升自己的认知。

### ISSUE THREAD

**Issue by cliukabam** [996icu/996.ICU#1718]

**Comment by ljhskyso-whalevii** [comment]
人各有志

**Comment by Yang-gg** [comment]
说到底还是钱没给够，多劳不能多得，而被资本压榨

**Comment by Inseeker** [comment]
Love 、Death or Robot ?
So what are you ?

**Comment by cliukabam** [comment]
> 说到底还是钱没给够，多劳不能多得，而被资本压榨

如果工作纯为了那点工资，那就没有任何意义，你也始终只能是个码农

**Comment by FactorialN** [comment]
也就是有你们存在，资本家才敢这么肆无忌惮。

**Comment by LALINUX2019** [comment]
同意，敬你一杯





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by ChenBerlin** [comment]
你不在意996没问题，但请不要代表我们。

**Comment by ZhouJoseph** [comment]
人各有志，家庭/人际关系/业余爱好/事业；
你选择了事业 15/7，我们可能更想努力的均摊一下吧

**Comment by cliukabam** [comment]
我不代表任何人，我只是想国内的开发人员可以真正强大起来，是不是996不重要，关键是你每天有没有进步，你有没有享受每天都在提升自我的快乐，当你真正去追求把每一件事情都做的极致的时候，付出再多都会觉得是快乐的。

**Comment by FactorialN** [comment]
> 我不代表任何人，我只是想国内的开发人员可以真正强大起来，是不是996不重要，关键是你每天有没有进步，你有没有享受每天都在提升自我的快乐，当你真正去追求把每一件事情都做的极致的时候，付出再多都会觉得是快乐的。

但你不能将其制度化，更不能以此作为剥削程序员的借口。众所周知，以自己的道德标准要求他人是一种流氓行径。

**Comment by mlkr** [comment]
每当你想要批评别人时，你要记住，这个世界上所有的人，并不是个个都有过你拥有的那些优越条件。
－－<了不起的盖茨比>

**Comment by suosui** [comment]
给别人打工和经营自己的事业是两码事。请不要偷换概念。

**Comment by Artyom2033** [comment]
您书得对，看您这么热爱工作，要不明天开始您给自己开小灶，007走起😁 😁

**Comment by cliukabam** [comment]
> > 我不代表任何人，我只是想国内的开发人员可以真正强大起来，是不是996不重要，关键是你每天有没有进步，你有没有享受每天都在提升自我的快乐，当你真正去追求把每一件事情都做的极致的时候，付出再多都会觉得是快乐的。
> 
> 但你不能将其制度化，更不能以此作为剥削程序员的借口。众所周知，以自己的道德标准要求他人是一种流氓行径。

你把这个当成剥削，证明你还有被利用的价值，当你强大的一定程度，你就可以制定更人性化的制度。

**Comment by Imccccc** [comment]
平均一周工作时长也996吧，但是个人并不支持；
我现在这么做是因为我乐意，而不是别人强制。要强制，钱先给够吧。

法律就摆在那，大家依法办事没毛病吧

**Comment by Inseeker** [comment]
I have a serious question:
    How can you have enough time to study for becoming  a better developer like you said， if you need work all the time like you said.

Please remember that most of the people  are ordinary employees, not an entrepreneur, not the owner of the company, and not you.  

And most people will die young if they work too much, Not everyone has robot muscles like you do.

**Comment by itwood** [comment]
真有心甘情愿当奴的，朋友说的时候我还不信，真让人大开眼界

**Comment by Inseeker** [comment]
> 真有心甘情愿当奴的，朋友说的时候我还不信，真让人大开眼界

Maybe he  is the owner of the company， work is his business and pleasure.

**Comment by 857092** [comment]
论奋斗逼是如何把全体员工拖入军备竞赛的hhh

**Comment by cliukabam** [comment]
> Love 、Death or Robot ?
> So what are you ?

a human with full of love

**Comment by cliukabam** [comment]
> > 真有心甘情愿当奴的，朋友说的时候我还不信，真让人大开眼界
> 
> Maybe he is the owner of the company， work is his business and pleasure.

I am the ower of my job, owership is the key to success.
