### ISSUE TITLE
提供下一些马克思《资本论》中的原文

### ISSUE THREAD

**Issue by sd44** [996icu/996.ICU#1719]
我正好写过996这方面的内容。以下是我所引用的马克思《资本论》中的一些话 ^_^～ 

至于个人受教育的时间，发展智力的时间，履行社会职能的时间，进行社交活动的时间，自由运用体力和智力的时间，以至于星期日的休息时间，——这全都是废话！但是，资本由于无限度地盲目追逐剩余劳动，像狼一般地贪求剩余劳动，不仅突破了工作日的道德极限，而且突破了工作日的纯粹身体的极限。（《资本论》第一卷，人民出版社2004版，306页）

  《1861年爱尔兰面包业委员会的报告》中提到，“委员会认为，把工作日延长到12小时以上，是横暴地侵犯工人的家庭生活和私人生活，这就侵犯一个男人的家庭，使他不能履行他作为一个儿子、兄弟、丈夫和父亲所应尽的家庭义务，以致造成道德上的非常不幸的后果。12小时以上的劳动会损害工人的健康，使他们早衰早死，因而造成工人家庭的不幸，恰好在最必要的时候，失去家长的照料和扶持。”（《资本论》第一卷，人民出版社2004版，292页）

  工人阶级中就业部分的过度劳动，扩大了它的后备军\footnote{想在本行业入职的失业或半失业人}的队伍，而后者通过竞争加在就业工人身上的增大的压力，又反过来迫使就业工人不得不从事过度劳动和听从资本的摆布。工人阶级的一部分从事过度劳动迫使它的另一部分无事可做（无事可做指后备军），反过来，它的一部分无事可做迫使他的另一部分从事过度劳动，这成了各个资本家致富的手段，同时又按照与社会积累的增进相适应的规模加速了产业后备军的生产。（《资本论》第一卷，人民出版社2004版，737页）

  决定工资的一般变动的，不是工人人口绝对数量的变动，而是工人阶级分为现役军和后备军的比例的变动，是过剩人口相对量的增减，是过剩人口时而被吸收、时而又被游离的程度。

  产业后备军在停滞和中等繁荣时期加压力于现役劳动军，在生产过剩和亢进时期又抑制现役劳动军的要求。所以，相对过剩人口是劳动供求规律借以运动的背景。它把这个规律的作用范围限制在绝对符合资本的剥削欲和统治欲的界限之内。”（《资本论》第一卷，人民出版社2004版，733页）

  不变资本的固定部分即工厂建筑物、机器等等的规糕，不管用来工作16小时，还是12小时，都会仍旧不变。工作日的延长并不要求在不变资本的这个最花钱的部分上有新的支出。此外，固定资本的价值，由此会在一个较短的周转期间系列中再生产出来，因而，这种资本为获得一定利润所必须预付的时间缩短了。因此，甚至在额外时间支付报酬，而且在一定限度内甚至比正常劳动时间支付较高报酬的情况下，工作日的延长都会提高利润。因此，现代工业制度下不断增长的增加固定资本的必要性，也就成了唯利是图的资本家延长工作日的一个主要动力。（《资本论》第三卷，人民出版社2004版，91页）

  资本主义生产方式按照它的矛盾的、对立的性质，还把浪费工人的生命和健康，压低工人的生存条件本身，看做不变资本使用上的节约，从而看做提高利润率的手段。（《资本论》第三卷，人民出版社2004版，101页）

**Comment by stephenchow9527** [comment]
### 厉了我的哥

**Comment by Trumeet** [comment]
> ### 厉了我的哥

这个大字报 NB

**Comment by fotock** [comment]
https://github.com/fotock/996Board
提交996企业，让我们举手制止
