### ISSUE TITLE
反动统治阶级力量十分强大

### ISSUE THREAD

**Issue by liyonghelpme** [996icu/996.ICU#17273]
为何中国不能及时爆发革命

从出生到死亡，反动统治阶级，通过两个方面来压制被统治阶级
经济上和思想上
经济上，通过低社会福利，高额房价，户口制度，为被统治者设立目标，使其始终挣扎在生存的边缘
同时通过到特定岁数，身体垮掉，而被裁员，只能从事滴滴司机以及送外卖业务，从而彻底摧毁这个群体，使群体新加入者无法理解革命的迫切性

其二通过不断洗脑政策，从出生的奋斗，到比你有钱还比你努力
而模糊了，你的努力只能为统治阶级带来法拉利的事实

而通过小恩小惠，进一步使你忽略了不同阶级的本质

兄弟和同学的称呼只是统治阶级麻醉你的产物
当你毕生积蓄换来户口和房产，终将因为缺少养老和失业而离你而去的时候，你才会明白
而这时的你早已丧失革命的能力

**Comment by BuhuanJin** [comment]
香港人占中的时候，19.3万人参加游行，79万人参与民间公投及“51万人参加七一游行，输了。
在大陆现在有大规模游行抗议？这个项目是在扩大，但有局限性，没发现这里的人多是程序员吗？因为首先要知道这个网站，知道这个项目，还要注册一个账号，点star，issue。很多其它职业的人，连这网站都不知道，两夜6万很多了，可是和中国人数比起来，这多吗？
很多人其它行业的人，连控诉的机会都没有。我的父亲是个厨师，以前加班领的工资不会过五千……没休假，他在那里做了十几年。换了个老板后，休息时间充足到能在晚上一两点不睡觉……工资五千。
