### ISSUE TITLE
没人敢吐槽阿里?..讲道理阿里晚上9点谁敢走?

### ISSUE THREAD

**Issue by Foxtile** [996icu/996.ICU#1745]
曝光贴没阿里，你们也就装着硬一下，接着回去加班吧!

**Comment by T-mans** [comment]
相对而言，阿里巴巴算是给钱给到位的了

**Comment by MSMING** [comment]
我一般下班半小时内就走，不服的辞退我😌

**Comment by MSMING** [comment]
我一般下班半小时内就走，不服的辞退我😌

**Comment by wonderfulMan** [comment]
阿里到位哪个奶子，可以这么说 阿里 无休息！不要觉得阿里给的多到位

**Comment by Foxtile** [comment]
说阿里钱到位的...这么说吧，至少当初我在的部门，社招能拿到P7的，多数来阿里都得大幅度降薪。同级别的人在哪拿到的钱都不比阿里少。如果按时薪计算在阿里收入绝对低得离谱。不要天真地以为在外面拿着20k "稍微努力努力" "运气好的话" 去阿里能一天干20小时然后拿3w5。人家HR精得很，给的比人家少也有的是人挤破头想去。除非你真的值50k在外面只拿着20k，完了纯粹因为阿里的面试相对正规能“发现”你的价值最后给你35k。这个概率非常非常低。
阿里真被给到位了的只有当年上市前稀里糊涂拿了一堆股票的。当年给一堆股票的时候马云压根没想过能发展壮大，不然也不会做什么年会找个凳子坐垫底下塞2万股看谁运气好坐到这个凳子这种事情。现在上市了你去看看阿里股票几百几百给？集团据我所知现在社招P7已经完全没股票了吧。
别看什么支付宝股票，支付宝的人一年等一年多少年了没有上市计划，再等几年以里面的人那种身体状况基本就是家祭无忘告乃翁？孩子都不一定是自己的。
马云是生意人，不是慈善家。把生意人当慈善家什么下场自己想想。
