### ISSUE TITLE
跟你们说个事，我在新西兰当码农 9点上班9点才从家走，5点下班5点差不多就到家了/狗头

### ISSUE THREAD

**Issue by huliyehutu** [996icu/996.ICU#1748]

**Comment by gigantic2** [comment]
哪家公司啊带上我

**Comment by leoduyun** [comment]
带上我

**Comment by rong4188** [comment]
哪家公司啊留个名啊

**Comment by huliyehutu** [comment]
这样并不好。。。小公司初创，毕业两年都在这，除了跟着老板学了不少忽悠客户投资的手段，技术上基本没啥进步。。
当然我看大部分跟我们同层的it公司也差不多这样，没啥压力

**Comment by gigantic2** [comment]
没事儿一起堕落

**Comment by leoduyun** [comment]
没关系技术我们可以教你 一起哈皮

**Comment by hjq2016** [comment]
duo luo together

**Comment by speakpeach** [comment]
五线城市，八点半到五点半。住的地方离公司800m

**Comment by zhangshiqin** [comment]
那么问题来了，国内工作狗怎样才能去国外工作呢

**Comment by leoduyun** [comment]
> 那么问题来了，国内工作狗怎样才能去国外工作呢

拿新西兰来说
标准路径 留学 => 技术移民 
也可以国内拿SFV或者WHV登陆直接找工作但要看运气
大牛可以直接离岸申请移民

**Comment by wenxushen** [comment]
想去那边工作，英语得过关吧

**Comment by huliyehutu** [comment]
我是走的留学这条路，英语肯定是必须的本科雅思6.0，硕士6.5.但是这是入学条件你毕业要是还这水平肯定是不够用的。几个国人同事韩国同事英语水平真是听他们说话我就想赶紧走开。。口语交流很重要一般的公司招聘要求都有交流顺畅这一项，说明他们也不在乎在国外招人只要你能交流。
