### ISSUE TITLE
企业把加班作为企业文化，不加班就是不尊重企业？

### ISSUE THREAD

**Issue by Lry0504** [996icu/996.ICU#17812]
不知道你们工作有没有遇到这样的企业：把企业当作企业文化，在招聘中明明写的是五天双休，但是后面工作却变成了每晚加班，六天工作制，甚至有时候周末也叫你上班。但是工资仍然不算加班工资。。。

**Comment by gaojian10120** [comment]
迟到一分钟都要扣工资，加班四五个小时没有工资，这样都企业谈何尊重？

**Comment by manolixx** [comment]
完全不喜欢这样 的工作氛围,明明合理工作完了,办公室没有一个人走,我工作完走了,说真的完成了么,看到真的完成了 说 工作不饱和,从别的项目组拉活给我们.好像晚上八点之前下班就是 工作不饱和的象征,在之前的公司肩颈都需要理疗,过劳肥,,,换了一个公司 ,现在身体健康正常吃喝还瘦了.

**Comment by manolixx** [comment]
休婚嫁 请假 领导审批了,但是条件是在家手机随时待命,明明在采购婚礼用品,还要扛着电脑,晚上都不敢关机,因为 没看qq消息 老大会直接打电话过来,休假结束 ,说我休息了半个月 其实只是婚嫁 +十一的假期而已,

**Comment by Lry0504** [comment]
> 迟到一分钟都要扣工资，加班四五个小时没有工资，这样都企业谈何尊重？

我们是迟到五分钟后算你没来。。。而且一天打卡6次。。。

**Comment by manolixx** [comment]
在上家公司每天都很疲惫,难得的朋友聚会我还扛着电脑 时不时的听手机qq消息的声音 ,每天都精神紧绷,感冒发烧 请病假一天,结果这一天是在家敲代码,真爽,有时候 我就想或许只有我全身瘫痪的时候才可以不这样吧

**Comment by Lry0504** [comment]
> 休婚嫁 请假 领导审批了,但是条件是在家手机随时待命,明明在采购婚礼用品,还要扛着电脑,晚上都不敢关机,因为 没看qq消息 老大会直接打电话过来,休假结束 ,说我休息了半个月 其实只是婚嫁 +十一的假期而已,

我记得我几次晚上没加班，领导还特地叫我去办公室，问我为什么不加班，我说今天工作完成了为什么要加班。。。现在很多企业都觉得员工加班理所应当了

**Comment by manolixx** [comment]
上家公司我坚持了一年多的996 这样的氛围 ,直到我爷爷去世 我真的受不了了 ,最爱的人都不在了  还有什么理由坚持,辞职了 换了一个公司 现在好多了,虽然还有工作的压力 但是最起码工作氛围喝企业文化 比之前好太多了

**Comment by manolixx** [comment]
现在的公司不强制加班,都是我自己觉得 我需要加班我自己才加班,加班了也有餐补 , 比之前那种压迫的加班好太多,上家公司加班调休要领导审批 才可以算加班 ,加班餐补 打的补贴 也要领导层层审批,其实基本都是 没有人去 申请,因为就算申请了  一个领导批了 还要再过几层审批,真的是可笑

**Comment by manolixx** [comment]
现在的公司  ,比较人性化,有时候同事的孩子 放假了,允许在公司 呆着,不像之前的公司 ,公司不大  搞得自己好像是机密单位一样要求多,福利少
