### ISSUE TITLE
【上海鲸谷座招聘】android首席开发工程师 25K-50K 10点左右上班，不打卡，自由Code完收工

### ISSUE THREAD

**Issue by lailaiwei** [996icu/996.ICU#1796]
25K-50K  10点左右上班，不打卡，自由Code完收工  有电竞专区，吧台，按摩椅等等...
Android首席工程师
职位描述
关于我们：

我们正在寻找一个Android团队负责人加入我们优秀的移动开发团队来领导Android app的开发。我们的团队充满激情、聪明谦逊，并致力于使用尖端技术创造出色的移动产品。 创新、研究和创造力始终是我们工作的重要核心。如果您对改变名人与粉丝联系方式的社交产品感兴趣，我们非常期待与您见面。

这个职位将作为Android团队负责人。作为团队的基石，我们希望他能身兼多职，并对整个Android移动应用程序的全生命周期负责，包括设计和架构以及管理优秀的工程师团队。

你会做什么：

	设计、实现、交付和测试Android app，并能够从技术和业务角度理解和拓展我们的产品
	通过基于对业务和技术优先级的理解，与产品经理、设计师、后端工程师等协同合作
	管理和培养一个小型的敏捷开发团队，并能够身先士卒参与开发
	有优秀的问题解决能力，能通过将复杂问题分解为优雅的技术解决方案，并完成实现
	积极推动采用新的技术架构，改进最佳实践。我们一直在寻求改进构建软件的流程，我们需要你能够帮助我们更快速地推进技术革新

你应该有：

	8年以上的行业经验
	2年以上的技术领导开发团队经验
	多年REST或GraphQL、基础网络API方面的相关经验
	了解最新的Android原生或混合应用程序架构和设计模式，并有实际的开发参与经验
	能够设计和构建复杂的UI层次结构
	了解MVC/MVP/MVVM，异步/多线程模式，和其他面向对象的开发模式/概念
	能够产出和审阅高质量、高可读性和高测试覆盖率的代码。有自动化测试相关经验（单元，自动化，集成）
	协作版本控制的经验（我们用git）
	对产品质量和细节关注充满热情，并热衷于在快节奏的科技创业公司工作
	计算机科学或相关领域的大学学位/同等经验

联系我们：

	Email:  developers@whalevii.com
	WeChat: xiaomaoYeah007
	Link:  http://suo.im/4AhiB0
Android Lead Engineer     
Job description
About the Opportunity:

We are looking for an Android Team Lead to join our awesome mobile team to Lead Android Development. Our mobile team is a talented group of smart, humble people who are passionate about creating amazing mobile products using cutting-edge technology. Innovation, research, and creativity are always at the forefront of what we do, so if you’re excited to work on a product that will revolute the way celebrities are connecting with fans, we look forward to meeting you.

This role will focus as an Android Team Lead who is willing to wear many hats and take ownership of full-lifecycle development, including design and architecture and managing a team of awesome Android Engineers

What you will work on:

	Design, implement, deliver, and test awesome Android applications while understanding our products from both a technical and business perspective.
	Communicate with leadership, product owners, designers, and your peers to create working software based on an understanding of business and technical priorities.
	Manage, mentor, and participate in a small agile team.
	Break down complex problems into elegant technical solutions to intelligently solve problems
	Actively contribute to the adoption of strong software architecture, development best practices, and new technologies. We are always improving the process of building software; we’ll need your help to do that

You should have:

	8+ years of industry experience
	2+ years of experience tech leading a team of developers
	Years of experience developing with REST, GraphQL and foundation networking API
	Fully self-sufficient in the Android platform and tools
	An understanding of Android app architecture and design patterns
	Recent hands-on development experience in a complex native/hybrid application
	Ability to design and architect complex UI hierarchies
	Demonstrated skills in writing and testing (unit, automation, integration) high-quality, readable, well-architected and efficient code
	Experience with collaborative version control (we use git)
	A creative and agile team-player with a passion for product quality and attention to the little things
	A passion for working in a fast-paced technology company
	College degree in Computer Science or related field of study/equivalent experience

Contact Us:

	Email:  developers@whalevii.com
	WeChat: xiaomaoYeah007
	Link:  http://suo.im/4AhiB0

**Comment by xxllp** [comment]
不写待遇和工作时间发毛啊

**Comment by 574759229** [comment]
发在这里的意思是。该公司没有996 也没有自愿加班是吗。//手动滑稽

**Comment by lailaiwei** [comment]
> 不写待遇和工作时间发毛啊

立马更新

**Comment by xxllp** [comment]
为了招人蹭热度尔，工资一般
