### ISSUE TITLE
北京Grab欢迎你，外企基本不加班

### ISSUE THREAD

**Issue by zinclee123** [996icu/996.ICU#18]
感兴趣的可以发简历到18708242@qq.com

**Comment by chan17** [comment]
文明之光

**Comment by zhengjian518** [comment]
qq邮箱？

**Comment by zinclee123** [comment]
> qq邮箱？

公司邮箱邮件太多了，怕错过

**Comment by NZQiu** [comment]
新加坡Grab欢迎你, imqiuqiu@gmail.com 😯

**Comment by Eyey110** [comment]
好
虽然不知道好在哪里，但是就是觉得好

**Comment by qudexin1986** [comment]
做啥的？

**Comment by zhongjiajie** [comment]
这个招聘广告打得好

**Comment by songjim** [comment]
可惜杭州外企少

**Comment by MrUncleX** [comment]
优秀啊老哥 grab国外还挺好用

**Comment by piedro** [comment]
SRE & DevOps 团队呢

**Comment by zinclee123** [comment]
> SRE & DevOps 团队呢

招，evergreen，欢迎投递简历

**Comment by zinclee123** [comment]
> 做啥的？

东南亚的出行平台，总部在新加坡

**Comment by time-art** [comment]
给个star鼓励一下吧，感谢
[https://github.com/liangzai92/blog](https://github.com/liangzai92/blog)
![](http://qiniu.adebibi.com/qrcode-web.jpg)

**Comment by jerry-zzk** [comment]
这广告打的，赶紧就投了一封(手动滑稽狗头）
