### ISSUE TITLE
30万star很简单，应该把学校那群准程序员发动起来加星，毕竟这也是他们的未来！

### ISSUE THREAD

**Issue by ChenShisen** [996icu/996.ICU#18017]

**Comment by EchoZw** [comment]
我就是在学校得准程序员，现在在实习，10 9 6 吧，刚来的时候 10 7 5，后来上新服务，然后一开始还是 10 7 5，过了几天，领导说我们不努力，强制 10 9 6 ，现在已经在考虑是否留在这了。
