### ISSUE TITLE
一群散兵游勇，不可能成事。期待组织领导出来带领大家推翻这些不公平。为了自己也为了后代

### ISSUE THREAD

**Issue by 0neGeng** [996icu/996.ICU#18174]

**Comment by jamesiter** [comment]
为了子孙后代！

**Comment by LinFeng1987** [comment]
说得对，没人领导组织是不可能成功的

**Comment by 0neGeng** [comment]
成立工会。。一定要有自己的工会

**Comment by jamesiter** [comment]
@0neGeng 对，要真正的工会。不是挂羊头卖狗肉的假工会。

**Comment by jamesiter** [comment]
@LinFeng1987 别急，凉水从常温，烧到 100°，需要烧很久的。靠一根火柴烧一秒，当然烧不开。但是开水，一定是被一直加温烧开的。

**Comment by LinFeng1987** [comment]
@jamesiter 赞成，但是在这个体制下权力得不到监督 成立工会也一个样

**Comment by jamesiter** [comment]
@LinFeng1987 咱们都是搞互联网的，换种思维方式。方法总比障碍多。
