### ISSUE TITLE
是不是女装大佬，掏出来很大系列？

### ISSUE THREAD

**Issue by deelian** [996icu/996.ICU#18200]
是不是女装大佬，掏出来很大系列？

_Originally posted by @AnswerNo2 in https://github.com/996icu/996.ICU/issues/18154#issuecomment-477835718_

是的

**Comment by AnswerNo2** [comment]
> 是不是女装大佬，掏出来很大系列？
> 
> _Originally posted by @AnswerNo2 in [#18154 (comment)](https://github.com/996icu/996.ICU/issues/18154#issuecomment-477835718)_
> 
> 是的

前端还是后端
