### ISSUE TITLE
我觉得现在互联网公司 要求 996 也不是不行 但是工资肯定得加 不然真就是耍流氓！

### ISSUE THREAD

**Issue by NaCoLiu** [996icu/996.ICU#1847]
想想早上9点上班 晚上5点上班 每周只工作5天 ，我凭什么给你干到 晚上9点 还得多上一天班，这样既然员工也不愿意，大大降低工作的积极性，这难道不是高层更应该考虑的问题嘛？

**Comment by yalishizhude** [comment]
前辈们用生命争取而来的8小时工作制就被这种公司的员工所破坏了~
