### ISSUE TITLE
北京 上海 杭州 深圳 广州等地区 微信内推群 ~准备换工作的可以进来看看

### ISSUE THREAD

**Issue by BestDingSheng** [996icu/996.ICU#18525]
### 目前已经超过100人需要邀请才能进来，有需要的加我微信 备注想进哪个地区的内推群

![image](https://user-images.githubusercontent.com/13111768/55204580-8cfc3400-520a-11e9-9727-8cf5836cd815.png)
![image](https://user-images.githubusercontent.com/13111768/55204588-94234200-520a-11e9-9f43-56ec2cdaf366.png)
![image](https://user-images.githubusercontent.com/13111768/55204591-97b6c900-520a-11e9-9a8d-fe3098607e74.png)

### 本人微信

![image](https://user-images.githubusercontent.com/13111768/55204572-7950cd80-520a-11e9-90f3-db8c923f6096.png)

**Comment by wift-smith** [comment]
有济南的不
