### ISSUE TITLE
我们公司虽然不是996，但下班了也天天在微信群里艾特你处理问题；还以为就我们是这么苦逼呢，原来大家都是...不人性啊

### ISSUE THREAD

**Issue by wangzf001** [996icu/996.ICU#18554]
下班照样工作，还没工资提成，同样遭遇的留个言

**Comment by Gaozn** [comment]
微信发展到今天，已经成了办公/社交软件了

**Comment by elecCore** [comment]
我们从来不拒绝全情投入，请给响应的回报好么

**Comment by FKmyCode** [comment]
我们也经常这样。在家也得处理，拿teamviewer远程公司电脑

**Comment by HouHaiqiang** [comment]
其实是可以避免的。以前遭遇过 刚毕业没经验 发现有问题就@我 处理这处理呢 带我的组长你咋不@的。 后来发现真的急就打电话了 消息可以假装没看见。 用 噢 我手机在充电 噢 昨天发消息的在开车没注意 喔 下班和朋友聚会去了 没看消息 噢 昨天有事儿没注意到群消息。 真电话了 就说我在外面吃饭 我在地铁上 我在开车 我在外面 我还没到家 总之没在电脑边上要一两个小时候才行 然后他就会@别人 只要你坚持原则就肯定有变化。    后来  后来我就辞职了。。。。。。

**Comment by gxg569157706** [comment]
程序猿的心声！

**Comment by wangzf001** [comment]
为了产品，偶尔的占用下班时间工作，我们敬业，可以接受。但请不要一直占用，用我们的敬业精神当要挟我们加班的筹码

**Comment by Followang** [comment]
都是给惯的.起初我也是这样,后来我下班以后就直接把工作用微信关了，如果真是十万火急的事情人家会直接打你电话
