### ISSUE TITLE
爆料：上海嵩恒网络科技有限公司（东方头条）995起！！！！

### ISSUE THREAD

**Issue by Coder-Justin** [996icu/996.ICU#18611]
1、每天必须晚于9点钟下班，早上必须及时打卡，否则以旷班论处
2、HR会通过钉钉后台监控工作时间，如果加班时间不够，会找你洗脑，说你不够奋斗，不够努力，不够积极，并且会延迟你的转正，甚至不允许转正
3、老板李嵩直接在钉钉群里骂哭HR，骂哭前台你敢信？CTO骂产品经理的时候直接摔笔记本你敢信？

**Comment by DayDreamCoder** [comment]
脾气很暴躁啊

**Comment by chenye0408** [comment]
太过分了！

**Comment by gxg569157706** [comment]
删库跑路！等着干啥？
