### ISSUE TITLE
996公司列表看这里吧，markdown太卡可能加载不出来

### ISSUE THREAD

**Issue by LinXueyuanStdio** [996icu/996.ICU#18710]
复制下面网址到浏览器里
```
https://feathub.com/LinXueyuanStdio/996.ICU?format=svg
```
或者点击
[https://feathub.com/LinXueyuanStdio/996.ICU?format=svg](https://feathub.com/LinXueyuanStdio/996.ICU?format=svg)

**Comment by Glowingstar** [comment]
浙江温州江南皮革厂这都有？

**Comment by zlx362211854** [comment]
https://github.com/zlx362211854/ICU-charts  这里有投票出来的公司名单的图表呈现

**Comment by iqwxiaopeng** [comment]
光说996没用，我觉得得贴工资上去啊，别人3年经验 996 一月40那自愿， 我这6年996一月10K那才不像话

**Comment by LinXueyuanStdio** [comment]
浙江温州江南皮革厂也实行996？哈哈
