### ISSUE TITLE
【求列举】根据 2.75 倍工资倒算，996的你的实际工资应该有多少

### ISSUE THREAD

**Issue by dvaknheo** [996icu/996.ICU#1892]
求个列举吧。算一算经济帐，看一看怎么亏的。
比如 20k 工资 996，实际等同于 7272 月薪。
20k 13薪996 等同于 7878。

有没有亏损的小伙伴出来报告？

**Comment by hacknife** [comment]
还是我现在这个公司好，虽然小，但是准时上下班

**Comment by dvaknheo** [comment]
2.275 倍，不是 2.75 ,我算错了
8791
