### ISSUE TITLE
搞不懂这种帖子还能活起来

### ISSUE THREAD

**Issue by CPUdream** [996icu/996.ICU#18968]
完全可以不是996呀市场决定价格不是996，可以工资减半，或者是其他得呀，还是因为程序猿太多，你不干有人干，哪个行业加班不严重了，
有那么多传统软件公司不是996得你们又嫌弃工资低

**Comment by Mysakura** [comment]
就你抖机灵？嗯？

**Comment by CPUdream** [comment]
拿着高薪控诉公司加班

**Comment by jxwsy** [comment]
当纳粹来抓共产主义者的时候，
我保持沉默；
我不是共产主义者。

当他们囚禁社会民主主义者的时候，
我保持沉默；
我不是社会民主主义者。

当他们来抓工会会员的时候，
我没有抗议；
我不是工会会员。

当他们来抓犹太人的时候，
我保持沉默；
我不是犹太人。

当他们来抓我的时候，
已经没有人能替我说话了。

**Comment by CPUdream** [comment]
@

> 当纳粹来抓共产主义者的时候，
> 我保持沉默；
> 我不是共产主义者。
> 
> 当他们囚禁社会民主主义者的时候，
> 我保持沉默；
> 我不是社会民主主义者。
> 
> 当他们来抓工会会员的时候，
> 我没有抗议；
> 我不是工会会员。
> 
> 当他们来抓犹太人的时候，
> 我保持沉默；
> 我不是犹太人。
> 
> 当他们来抓我的时候，
> 已经没有人能替我说话了。

你可以不去工作呀，没人抓你，就会引用这些没用得话，还是那句话拿着高薪控诉公司加班

**Comment by webwhy** [comment]
@CPUdream**但是该发泄的还是要发泄的呀**
