### ISSUE TITLE
这些呐喊是没有用的，要想改变除非去告，违反劳动法，或者国家强制来一波，要么就是改变自己的思想；仅仅在这抱怨依我看，说不定不能让你心情变好，还可能会更坏

### ISSUE THREAD

**Issue by HaoXianSen** [996icu/996.ICU#19014]

**Comment by liuqinglong110** [comment]
引起更多人注意，至少比默默忍受要抢。当纳粹来抓共产主义者的时候， 我保持沉默； 我不是共产主义者。 当他们囚禁社会民主主义者的时候， 我保持沉默； 我不是社会民主主义者。 当他们来抓工会会员的时候， 我没有抗议； 我不是工会会员。 当他们来抓犹太人的时候， 我保持沉默； 我不是犹太人。 当他们来抓我的时候， 已经没有人能替我说话了。
