### ISSUE TITLE
试想一下，如果程序员，集体罢工，会怎样？

### ISSUE THREAD

**Issue by cmdit** [996icu/996.ICU#19023]

**Comment by WangHolmos1205** [comment]
不现实的。

**Comment by superace** [comment]
整体瘫痪，，，

**Comment by lisuyu** [comment]
nothing happen...

**Comment by fy5220** [comment]
不会出现的..即便出现了...集体滚蛋了..后面有人补上...

**Comment by Hey-xhl** [comment]
那成都的经济基本上。。。。

**Comment by rmctJ** [comment]
由于bug是程序员写代码的时候产生的。当所有的程序员停止写代码，短时间内bug的产生将减少。
在之后的时间里，由于历史bug的不断被公布和无人修复，bug越来越多，人类将被bug淹没。

**Comment by cmdit** [comment]
是不现实，哪里有压迫，哪里就有用反抗。反抗了，很多企业就完了。

在 2019-03-29 10:40:41，"WangHolmos1205" <notifications@github.com> 写道：


不现实的。

**Comment by cmdit** [comment]
国家就会混乱

在 2019-03-29 10:41:18，"superace" <notifications@github.com> 写道：


整体瘫痪，，，

**Comment by cmdit** [comment]
这种现象就是，成为资本家压榨工人的资本，你不干，有成千上万的人想干

在 2019-03-29 10:43:42，"fy5220" <notifications@github.com> 写道：


不会出现的..即便出现了...集体滚蛋了..后面有人补上...

**Comment by lisuyu** [comment]
成都经济？成都经济的支柱产业不是IT培训么？培训三个月，出去就说你有三年工作经验！

**Comment by cmdit** [comment]
成都的IT培训很多，有的培训机构还很不错，是不是有些培训机构是培训出来拿着高薪写BUG的

在 2019-03-29 10:50:39，"lisuyulisuyu" <notifications@github.com> 写道：


成都经济？成都经济的支柱产业不是IT培训么？培训三个月，出去就说你有三年工作经验！
