### ISSUE TITLE
如果成功和房子要以ICU为代价，我另可不要

### ISSUE THREAD

**Issue by jxwsy** [996icu/996.ICU#19107]

**Comment by SallyOne** [comment]
@jxwsy  有多少人能做到的，这里面的 issue 我觉得好多只是觉得工资水平和996对应不上而已。

**Comment by jxwsy** [comment]
@SallyOne 当纳粹来抓共产主义者的时候， 我保持沉默； 我不是共产主义者。 当他们囚禁社会民主主义者的时候， 我保持沉默； 我不是社会民主主义者。 当他们来抓工会会员的时候， 我没有抗议； 我不是工会会员。 当他们来抓犹太人的时候， 我保持沉默； 我不是犹太人。 当他们来抓我的时候， 已经没有人能替我说话了

**Comment by jxwsy** [comment]
@SallyOne 所以跟薪资无关，我从来没996。人与人的思想境界是不同的。
