### ISSUE TITLE
上海ICU.996，微信群

### ISSUE THREAD

**Issue by FaceGhost** [996icu/996.ICU#19191]
拉入微信群

![微信图片_20190329104955](https://user-images.githubusercontent.com/19989061/55206265-d8194580-5210-11e9-8042-4e52ac18be02.jpg)

**Comment by dulingkang** [comment]
![NLP-机器学习](https://user-images.githubusercontent.com/11434105/55206352-1d3d7780-5211-11e9-804c-48cc6dc38f52.jpeg)
