### ISSUE TITLE
强烈建议大佬弄一个专门曝光各大公司加班石锤的内部群里或者网站，方便找工作过滤这些公司

### ISSUE THREAD

**Issue by wl948508016** [996icu/996.ICU#19225]

**Comment by dulingkang** [comment]
![NLP-机器学习](https://user-images.githubusercontent.com/11434105/55206441-655c9a00-5211-11e9-991c-b50ee031608c.jpeg)

**Comment by sunqitao** [comment]
加班半年，调理一年

**Comment by WangHolmos1205** [comment]
这个github就有投票的。

**Comment by wl948508016** [comment]
明明是搞技术的，弄得跟流水线工人一样，技术价值根本不被承认，本来工作越久越想提高自己的工作效率，多余的时间可以丰富自己的生活，现在可好年限越久工作时间越长，感觉目前公司理念已经畸形，偶尔问起还会被说：“抢着来加班的人大有人在”。理想变成现实就是物质，空谈理想就是道德绑架，甚至是骗子
