### ISSUE TITLE
建议推到微博热搜，不要放弃，坚持下去

### ISSUE THREAD

**Issue by houyuesong** [996icu/996.ICU#19488]
反抗失败不可怕，可怕的是人们逐渐的习惯，默认这种形式，并且忘记了抵抗，我们必须要争取自己的合法权益，加班不是不可以，项目是有着急的时候，但是必须要给相对应的报酬，不然工资都不够看病的，而且现在程序员本来工作年限就少，二线城市有的甚至招聘写出30岁以下，大学毕业到30岁，试问能干几年？希望大家不要放弃，努力起来，做一个能够改变历史的人。

**Comment by CH-Augustine** [comment]
哦
