### ISSUE TITLE
程序员大部分都是很自傲的，自以为是拿个几万一个月很优越，然后就忘了自己是谁，其实都是青春饭，等你哪天不能熬夜了，公司倒闭了，高不成低不就，种田都轮不到你

### ISSUE THREAD

**Issue by zhu106878723** [996icu/996.ICU#19577]

**Comment by bangok** [comment]
多数没有上万吧，我们这里6000-8000

**Comment by yiboforever** [comment]
听你说话，咋感觉有点欠揍

**Comment by ty850454** [comment]
你这个人有病

**Comment by sharkrock** [comment]
酸柠檬🍋

**Comment by jxwsy** [comment]
@zhu106878723 其实这说的是一种反压榨反剥削的自省，不只是IT行业，这个人的思想我给他一句名言，当纳粹来抓共产主义者的时候，
我保持沉默；
我不是共产主义者。

当他们囚禁社会民主主义者的时候，
我保持沉默；
我不是社会民主主义者。

当他们来抓工会会员的时候，
我没有抗议；
我不是工会会员。

当他们来抓犹太人的时候，
我保持沉默；
我不是犹太人。

当他们来抓我的时候，
已经没有人能替我说话了。

**Comment by ywk1993** [comment]
种田还真的轮的到我 壁7

**Comment by shixinzi** [comment]
几万的还是少的 哥

**Comment by shixinzi** [comment]
一线城市过2.5w的比例都很少了
