### ISSUE TITLE
、字楼里写字间，写字间里程序员；程序人员写程序，又拿程序换酒钱。  酒醒只在网上坐，酒醉还来网下眠；酒醉酒醒日复日，网上网下年复年。  宁愿老死程序间，只要老板多发钱；小车大房不去想，撰个二千好过年。  若要见识新世面，公务员比程序员；一个在天一在地，而且还比我们闲。  别人看我穿白领，我看别人穿名牌；天生我才写程序，臀大近视肩周炎。  年复一年春光度，度得他人做老板；老板扣我薄酒钱，没有酒钱怎过年。  春光逝去皱纹起，作起程序也委靡；来到水源把水灌，打死不做程序员。  别人笑我忒疯癫，我笑他人命太贱；状元三百六十行，偏偏来做程序员。  但愿老死电脑间，不愿鞠躬老板前；奔驰宝马贵者趣，公交自行程序员。  别人笑我忒疯癫，我笑自己命太贱；不见满街漂亮妹，哪个归得程序员。

### ISSUE THREAD

**Issue by tangjinjinwx** [996icu/996.ICU#19593]
程序员 跪求star  https://github.com/tangjinjinwx/Public.WeChat.CRM.SDK

字楼里写字间，写字间里程序员；程序人员写程序，又拿程序换酒钱。 
酒醒只在网上坐，酒醉还来网下眠；酒醉酒醒日复日，网上网下年复年。 
宁愿老死程序间，只要老板多发钱；小车大房不去想，撰个二千好过年。 
若要见识新世面，公务员比程序员；一个在天一在地，而且还比我们闲。 
别人看我穿白领，我看别人穿名牌；天生我才写程序，臀大近视肩周炎。

年复一年春光度，度得他人做老板；老板扣我薄酒钱，没有酒钱怎过年。 
春光逝去皱纹起，作起程序也委靡；来到水源把水灌，打死不做程序员。 
别人笑我忒疯癫，我笑他人命太贱；状元三百六十行，偏偏来做程序员。 
但愿老死电脑间，不愿鞠躬老板前；奔驰宝马贵者趣，公交自行程序员。 
别人笑我忒疯癫，我笑自己命太贱；不见满街漂亮妹，哪个归得程序员。

程序员 跪求star  https://github.com/tangjinjinwx/Public.WeChat.CRM.SDK

**Comment by Xcode123456** [comment]
666老哥，这么有才，建立个组织吧，每天发点诗就行。

**Comment by tangjinjinwx** [comment]
不是我写的  我只是苦逼程序员

**Comment by xunbudaotiantangdemeng** [comment]
这诗 大才呀  老哥   我刚才还看到个写文言文README的老哥  现在的程序员都这么有才的吗
看来我做不了程序员了

**Comment by JHsunshine** [comment]
年复一年春光度，度得他人做老板；老板扣我薄酒钱，没有酒钱怎过年。
老哥你为什么穿着品如的衣服？
