### ISSUE TITLE
写字楼里写字间，写字间里程序员；程序人员写程序，又拿程序换酒钱。   酒醒只在网上坐，酒醉还来网下眠；酒醉酒醒日复日，网上网下年复年。   宁愿老死程序间，只要老板多发钱；小车大房不去想，撰个二千好过年。  别人笑我忒疯癫，我笑他人命太贱；状元三百六十行，偏偏来做程序员。   但愿老死电脑间，不愿鞠躬老板前；奔驰宝马贵者趣，公交自行程序员。   别人笑我忒疯癫，我笑自己命太贱；不见满街漂亮妹，哪个归得程序员。

### ISSUE THREAD

**Issue by tangjinjinwx** [996icu/996.ICU#19669]
程序员 跪求star  https://github.com/tangjinjinwx/Public.WeChat.CRM.SDK
写字楼里写字间，写字间里程序员；程序人员写程序，又拿程序换酒钱。 

酒醒只在网上坐，酒醉还来网下眠；酒醉酒醒日复日，网上网下年复年。 

宁愿老死程序间，只要老板多发钱；小车大房不去想，撰个二千好过年。

别人笑我忒疯癫，我笑他人命太贱；状元三百六十行，偏偏来做程序员。 

但愿老死电脑间，不愿鞠躬老板前；奔驰宝马贵者趣，公交自行程序员。 

别人笑我忒疯癫，我笑自己命太贱；不见满街漂亮妹，哪个归得程序员。
程序员 跪求star  https://github.com/tangjinjinwx/Public.WeChat.CRM.SDK

**Comment by ElephantGit** [comment]
6666666666666666666

**Comment by No-Sky** [comment]
优秀人才

**Comment by luhuiming** [comment]
优秀

**Comment by checkException** [comment]
兄弟 牛逼啊

**Comment by jsycdut** [comment]
太优秀了

**Comment by BenderCM** [comment]
你是要考研吗????

**Comment by Tieban** [comment]
优秀
