### ISSUE TITLE
上海，南京，武汉的同学可以真的考虑来我们公司，20天年假，早10点，晚六点，一周五天，工资还不比互联网低

### ISSUE THREAD

**Issue by HEQIANZHOU** [996icu/996.ICU#19700]

**Comment by fengxiaodi** [comment]
你们什么公司？

**Comment by HEQIANZHOU** [comment]
感兴趣的加我QQ：2258159945

**Comment by ltq2014** [comment]
什么公司

**Comment by HEQIANZHOU** [comment]
半导体行业软件开发

**Comment by HEQIANZHOU** [comment]
最近几年国家对半导体投入还是蛮多的，所以工资也渐渐上来了

**Comment by macoscoder** [comment]
什么公司，本人准备移驾南京

**Comment by HEQIANZHOU** [comment]
> 什么公司，本人准备移驾南京

Synopsys，有兴趣的可以加我微信，如果你有实力的话可以帮你内推
![WeChat Image_20190329115240](https://user-images.githubusercontent.com/14013441/55211352-95626800-5226-11e9-9bc9-4e13dae6b44a.jpg)

**Comment by wanjun123** [comment]
什么公司，武汉的表示有兴趣。。。
