### ISSUE TITLE
gitHub  Star 排名 13  增长速度已创造历史。

### ISSUE THREAD

**Issue by tipshot** [996icu/996.ICU#19715]
![image](https://user-images.githubusercontent.com/18547353/55207535-8a530c00-5215-11e9-9724-35a35f9fac9d.png)
![image](https://user-images.githubusercontent.com/18547353/55207539-8f17c000-5215-11e9-8d88-c23fd0cb67f2.png)

**Comment by zhaoweih** [comment]
页面的翻译。。。
