### ISSUE TITLE
袁隆平让劳苦大众吃太饱了

### ISSUE THREAD

**Issue by jiangminbing** [996icu/996.ICU#19911]
饭都吃不饱的时候就不会想着要加班了！！哈哈哈，这种变态的背后必然是高薪酬，不然谁干活！！

**Comment by jxwsy** [comment]
当纳粹来抓共产主义者的时候，
我保持沉默；
我不是共产主义者。

当他们囚禁社会民主主义者的时候，
我保持沉默；
我不是社会民主主义者。

当他们来抓工会会员的时候，
我没有抗议；
我不是工会会员。

当他们来抓犹太人的时候，
我保持沉默；
我不是犹太人。

当他们来抓我的时候，
已经没有人能替我说话了。

**Comment by NicodeLee** [comment]
仓廪实而知礼节 衣食足而知荣辱

**Comment by nuoyan2** [comment]
> 当纳粹来抓共产主义者的时候，
> 我保持沉默; 
> 我不是共产主义者。
> 
> 当他们囚禁社会民主主义者的时候，
> 我保持沉默; 
> 我不是社会民主主义者。
> 
> 当他们来抓工会会员的时候，
> 我没有抗议; 
> 我不是工会会员。
> 
> 当他们来抓犹太人的时候，
> 我保持沉默; 
> 我不是犹太人。
> 
> 当他们来抓我的时候，
> 已经没有人能替我说话了。

是的 国人都这样的心态 都是事不关己高高挂起 都害怕了 都在保护自己 因为不沉默也没什么用

**Comment by nuoyan2** [comment]
> 饭都吃不饱的时候就不会想着要加班了!!哈哈哈，这种变态的背后必然是高薪酬，不然谁干活!!
你要了解人的基本权力 这种996是一种犯法侵权行为  不要胡搅蛮缠了
