### ISSUE TITLE
年复一年春光度，度得他人做老板；老板扣我薄酒钱，没有酒钱怎过年。  春光逝去皱纹起，作起程序也委靡；来到水源把水灌，打死不做程序员。  别人笑我忒疯癫，我笑他人命太贱；状元三百六十行，偏偏来做程序员。  但愿老死电脑间，不愿鞠躬老板前；奔驰宝马贵者趣，公交自行程序员。  别人笑我忒疯癫，我笑自己命太贱；不见满街漂亮妹，哪个归得程序员。苦逼程序员跪求star  https://github.com/tangjinjinwx/Public.WeChat.CRM.SDK 

### ISSUE THREAD

**Issue by tangjinjinwx** [996icu/996.ICU#19922]
苦逼程序员跪求star  https://github.com/tangjinjinwx/Public.WeChat.CRM.SDK
年复一年春光度，度得他人做老板；老板扣我薄酒钱，没有酒钱怎过年。 
春光逝去皱纹起，作起程序也委靡；来到水源把水灌，打死不做程序员。 
别人笑我忒疯癫，我笑他人命太贱；状元三百六十行，偏偏来做程序员。 
但愿老死电脑间，不愿鞠躬老板前；奔驰宝马贵者趣，公交自行程序员。 
别人笑我忒疯癫，我笑自己命太贱；不见满街漂亮妹，哪个归得程序员。
苦逼程序员跪求star  https://github.com/tangjinjinwx/Public.WeChat.CRM.SDK

**Comment by txqcoder** [comment]
666

**Comment by 11084956** [comment]
大佬这个项目功能很溜啊
