### ISSUE TITLE
某程序员对书法十分感兴趣，退休后决定在这方面有所建树。于是花重金购买了上等的文房四宝。一日，饭后突生雅兴，一番磨墨拟纸，并点上了上好的檀香，颇有王羲之风范，又具颜真卿气势，定神片刻，泼墨挥毫，郑重地写下一行字：hello world。  苦逼程序员跪求star  https://github.com/tangjinjinwx/Public.WeChat.CRM.SDK

### ISSUE THREAD

**Issue by tangjinjinwx** [996icu/996.ICU#20087]
某程序员对书法十分感兴趣，退休后决定在这方面有所建树。于是花重金购买了上等的文房四宝。一日，饭后突生雅兴，一番磨墨拟纸，并点上了上好的檀香，颇有王羲之风范，又具颜真卿气势，定神片刻，泼墨挥毫，郑重地写下一行字：hello world。 
苦逼程序员跪求star  https://github.com/tangjinjinwx/Public.WeChat.CRM.SDK

**Comment by Domingowen** [comment]
I think your action will let the other people hate you. because they no just expression working time problem, Also expression the government don't have any action to punishment Illegal of the company in China
