### ISSUE TITLE
有没有想过为什么？

### ISSUE THREAD

**Issue by zhangsiyuan718** [996icu/996.ICU#20128]
明明有上下班时间，可总有那么一些人不愿意下班就走，自愿加班。这样，部门很多人下班不走，想正常走的人为了合群，不得不在公司继续呆着，领导看到同事们那么热衷于下班加班，那么好吧，大刀挥起来，延迟下班时间吧，反正你们还会在这多呆一会儿的。最后发现，不行，实在受不了，默默的抗争，最后我们仍然在边缘试探。996的大刀依然在脖子上悬着。人为财死。

**Comment by weiweiok** [comment]
下班坐着不走的人，一多半不是在工作……
