### ISSUE TITLE
程序员这么大的群体，明年两会能不能有个人代表程序员们提提建议

### ISSUE THREAD

**Issue by MirrorZyb** [996icu/996.ICU#20151]

**Comment by chenkaiC4** [comment]
不会的

**Comment by superlucky8848** [comment]
应该代表全体劳动者，整顿一下用工问题，只代表程序员没啥意义。

**Comment by Gomuko** [comment]
您好，您觉得提建议有用吗？

**Comment by chenkaiC4** [comment]
古人云，一将功成万骨枯，别的不想了，改bug去了

**Comment by weiweiok** [comment]
你觉得政协委员里有程序员？

**Comment by nositno4** [comment]
万一代表是马化腾呢？

**Comment by jamesiter** [comment]
工会应该由工人自己成立，工会代表应该由工人选举。拒绝阿猫阿狗借着工会的名义，挂羊头卖狗肉，出卖工人的权益。

**Comment by Medivh2011** [comment]
不会有的,底层人民永远只能是底层人民

**Comment by chenkaiC4** [comment]
程序猿顶多屌丝了点，还不至于是弱势群体，不会有人为咱们发声的。何况，很多人说起程序员没啥好感，比如项目经理，产品经理这些。

自己成立工会是比较可行的。

**Comment by MirrorZyb** [comment]
> 应该代表全体劳动者，整顿一下用工问题，只代表程序员没啥意义。

是的，但IT行业确实普遍比其他行业的工作时长高，工作强度大。。

**Comment by chenkaiC4** [comment]
最好的出路，还是技术扎实，加强培养产品感，加强自身的沟通表达能力，等自己成了马化腾了，记得是技术出身，给手下人多点福利，这应该是最具有操作性的方式了

**Comment by Gomuko** [comment]
楼上那么做到最后屁股都歪了！和劝人别做程序员是一个意思
