### ISSUE TITLE
一个程序员对自己的未来很迷茫，于是去问上帝。“万能的上帝呀，请你告诉我，我的未来会怎样？”上帝说：“我的孩子，你去问Lippman，他现在领导的程序员的队伍可能是地球上最大的”。于是他去问Lippman。Lippman说：“程序员的未来就是驾驭程序员”。这个程序员对这个未来不满意，于是他又去问上帝。“万能的上帝呀，请你告诉我，我的未来会怎样？”。上帝说：“我的孩子，你去问Gates，他现在所拥有的财产可能是地球上最多的”。万能的上帝呀，请你告诉我，我的未来会怎样？”。上帝说：“我的孩子，你去问侯捷，他写的计算机书的读者可能是地球上最多的”。万能的上帝呀，请你告诉我，我的未来会怎样？”。上帝摇摇头：“唉，我的孩子，你还是别当程序员了” 苦逼程序员跪求star  https://github.com/tangjinjinwx/Public.WeChat.CRM.SDK

### ISSUE THREAD

**Issue by tangjinjinwx** [996icu/996.ICU#20166]
一个程序员对自己的未来很迷茫，于是去问上帝。“万能的上帝呀，请你告诉我，我的未来会怎样？”上帝说：“我的孩子，你去问Lippman，他现在领导的程序员的队伍可能是地球上最大的”。于是他去问Lippman。Lippman说：“程序员的未来就是驾驭程序员”。这个程序员对这个未来不满意，于是他又去问上帝。“万能的上帝呀，请你告诉我，我的未来会怎样？”。上帝说：“我的孩子，你去问Gates，他现在所拥有的财产可能是地球上最多的”。万能的上帝呀，请你告诉我，我的未来会怎样？”。上帝摇摇头：“唉，我的孩子，你还是别当程序员了”
苦逼程序员跪求star  https://github.com/tangjinjinwx/Public.WeChat.CRM.SDK

**Comment by weiweiok** [comment]
你已经成功引起了我的反感。。。刷了一上午了，歇会吧

**Comment by lzlz000** [comment]
蹭热度刷屏打广告，非常反感

**Comment by tangjinjinwx** [comment]
骂吧 继续骂   反正闲着也是闲着
