### ISSUE TITLE
你干了多久？超过一个月就是你自己的问题，怪不了公司

### ISSUE THREAD

**Issue by jaspergong** [996icu/996.ICU#20257]
你干了多久？超过一个月就是你自己的问题，怪不了公司

_Originally posted by @JunerLee in https://github.com/996icu/996.ICU/issues/20208#issuecomment-477862333_

**Comment by jaspergong** [comment]
整个项目组都是这样的   不是我一个人

**Comment by leanang** [comment]
莫抬扛
