### ISSUE TITLE
我建议搞996ICU的区块链，想办法平衡员工利益，公司利益，法律风险，社会风险？？

### ISSUE THREAD

**Issue by lxiaodao** [996icu/996.ICU#20272]
我建议搞996ICU的区块链，写好投票智能合约，先解决如下核心问题：

1. 要不要成立基金会（非盈利组织，接受社会监督，接受捐款，管理996ICU的区块链的研发和规划）
   这个基金会最好有一些有社会影响力的技术大牛、律师、经济学家、社会学家等等参加。
   
2. 要不要成立工会（受基金会的监督管理）

3. 如果要维权，要不要采取法律手段

4. 基金会里面要有全职的人员，更多是兼职人员

5. 更多内容不断由基金会和996ICU区块链来完善

6. 怎么平衡程序员利益，公司利益，法律风险，社会风险？？

**Comment by e7** [comment]
想法不错，刘明

**Comment by BrickXu** [comment]
随便找个已知的币直接写进去就行了。

**Comment by lxiaodao** [comment]
目前在一个群QQ618651911。
最好单独搞链，设计经济学模型问题，要有自己的模型来调整平衡利益。还以以后投票，肯定是相对复杂的。这样一个涉及很多人的链，最好把核心能力掌握在自己手里。

**Comment by lxiaodao** [comment]
> 想法不错，刘明

目前在一个群QQ618651911，别人建立的，看能不能讨论出实际可行的东西来。

**Comment by BrickXu** [comment]
block！

**Comment by huahaofeng** [comment]
@lxiaodao 对区块链挺感兴趣，请问用什么语言开发
