### ISSUE TITLE
不只是程序员，是中国所有被996模式压榨的人民

### ISSUE THREAD

**Issue by onegiter** [996icu/996.ICU#20295]
大家应该要把门槛扩宽，本项目人群应该是被996工作模式所覆盖被压榨的人，而不是仅仅只有程序员这一行。发展广大的革命阵线，宽大受众群体，进入GIThub还需要注册才能发言，那些不能发言的人群呢，只是看一眼却留不下讯息。

**Comment by BuhuanJin** [comment]
对
