### ISSUE TITLE
Hoàng Sa, Trường Sa là của Việt Nam

### ISSUE THREAD

**Issue by vancuongitf** [996icu/996.ICU#20323]

**Comment by ty850454** [comment]
越南是中国自古以来的领土，古称安南，中国的交趾

**Comment by Anxure** [comment]
mmp，越南都是中国的

**Comment by ty850454** [comment]
> mmp，越南都是中国的

还真是的

**Comment by zhangfeng0415** [comment]
bullshit

**Comment by vancuongitf** [comment]
https://en.wikipedia.org/wiki/Nam_qu%E1%BB%91c_s%C6%A1n_h%C3%A0

**Comment by vancuongitf** [comment]
https://en.wikipedia.org/wiki/B%C3%ACnh_Ng%C3%B4_%C4%91%E1%BA%A1i_c%C3%A1o
