### ISSUE TITLE
全民共振，全民维权

### ISSUE THREAD

**Issue by izvkh2** [996icu/996.ICU#20435]
全国每年有数十万起维权行动，过三千万人次参与，但都因为在空间上分散（全国各地），在时间上也分散（365天），每次行动的人数都不足够压倒维稳力量，每次都被打压消声。 

解决办法很简单：全民共振---全国各地各阶层的维权群体约定时间和地点一起上街，提出各自诉求，互相支持壮大声势，形成共振效应，产生强大力量！人民力量够大，政府才肯听话！

步骤：

        1、在网上和网下约定时间（节假日或周末）地点（各省市政府附近的繁华商业街或广场），向各地各阶层维权群体广泛传播。

        2、维权者到时从四面八方奔赴约定地点。

        3、齐唱国际歌聚集形成队伍。

        4、向附近的政府大楼或电台电视台进发。

        5、维权群体纷纷提出各自诉求。

记住：几百几千人上街维权，我们会遭到他们的驱散和打压；几万几十万人一起上街，政府会解决人民提出的问题；几百万几千万人一起上街，我们就能解决出了问题的政府！

下次共振时间：

1、2019年两会

2、大米每斤过8块、面粉过5块

3、突发全国民愤极大事件

 全民共振平台邮箱： quanminggongzhen2018@gmail.com

官方电报群：https://t.me/QMGZ2019

官方电报频道:https://t.me/QMGZ2018

官方推特：https://twitter.com/2018qmgz

**Comment by BuhuanJin** [comment]
支持

**Comment by Jayzhanscar** [comment]
支持

**Comment by a232319779** [comment]
牵扯政治的爬。反对的是996。你这tmd的是不怀好意。好好的事让你给搅黄了。滚滚滚。

**Comment by zbw0046** [comment]
中华人民共和国集会游行示威法了解一下

**Comment by izvkh2** [comment]
单独维权很容易被镇压，全民上街，全民维权，才能够解决问题

**Comment by marvinzh** [comment]
牵扯政治的爬。反对的是996。你这tmd的是不怀好意。好好的事让你给搅黄了。滚滚滚。

**Comment by izvkh2** [comment]
仔细看看内容，这不是政治，而是一种全民维权的策略
