### ISSUE TITLE
大家可以进来看一下外企的招聘要求

### ISSUE THREAD

**Issue by HEQIANZHOU** [996icu/996.ICU#20490]
Job Requirements:
-   Fresh master or bachelor in CS/EE with 3+ years’ experience in complex software programming of related field.
-   Good software programming skills with hand-on C++ programming experience under Unix/Linux. Strong background in data structures and algorithms is required.
-   Strong desires to learn and explore new technologies and able to demonstrate good analysis and problem solving skills.
-   Good written and verbal English communication skills are necessary.
-   Able to work independently on project planning, implementation and testing.
-   Self-motivated and good team working spirit.
-   Experience in EDA industry or IC design especially in back-end flow or design planning is a plus.

早10点，晚6点，一周工作5天，第一年18天年假，以后每年增加1天，待遇不比996的互联网公司差，有兴趣的可以把简历发我邮箱：hqzhou@synopsys.com，我可以帮大家内推

**Comment by HEQIANZHOU** [comment]
要进一步了解的也可以先加我微信
![WeChat Image_20190329115240](https://user-images.githubusercontent.com/14013441/55210714-c9885980-5223-11e9-859b-886e19f40b0f.jpg)

**Comment by worldbeatiful** [comment]
好的

**Comment by worldbeatiful** [comment]
等我辞职啊

**Comment by HEQIANZHOU** [comment]
忘了说了，工作地点目前可以有上海和武汉

**Comment by de-rk** [comment]
> 忘了说了，工作地点目前可以有上海和武汉
招实习吗

**Comment by HEQIANZHOU** [comment]
> > 忘了说了，工作地点目前可以有上海和武汉
> > 招实习吗

有实习的，就是实习岗位比较少

**Comment by HEQIANZHOU** [comment]
> > 忘了说了，工作地点目前可以有上海和武汉
> > 招实习吗

**Comment by sonny-zhang** [comment]
有深圳的可以给我说下吗？
