### ISSUE TITLE
罢工提议

### ISSUE THREAD

**Issue by HzSpring** [996icu/996.ICU#20514]
这种情况我们应该奋起反抗,来一个集体罢工,不能再这样被剥削了！

**Comment by Skyofmine** [comment]
算了，工资要紧工资要紧

**Comment by izvkh2** [comment]
支持宕机一小时
https://github.com/996icu/996.ICU/issues/20351

**Comment by HzSpring** [comment]
将大型网站全部重定向到icu 996！！
