### ISSUE TITLE
996程序员一枚，了解下我的项目https://github.com/shiguanghuxian/etcd-manage

### ISSUE THREAD

**Issue by shiguanghuxian** [996icu/996.ICU#20560]
[](https://github.com/shiguanghuxian/etcd-manage)

**Comment by godcong** [comment]
。。。内容都没有，能更懒一点么？

**Comment by shiguanghuxian** [comment]
[https://github.com/shiguanghuxian/etcd-manage](https://github.com/shiguanghuxian/etcd-manage)
