### ISSUE TITLE
中国法律已死，共残党早已放弃人权！#初级程序员通常分析不出问题的根本原因，看不到现象的本质#

### ISSUE THREAD

**Issue by liaogx** [996icu/996.ICU#20579]
从小处来说，只是当今社会有一类叫做“程序员”的职业群体过渡加班，没有得到宪法规定的劳动报酬；从历史来看，这是没有`民主、自由、法律`的恶果，集权社会下意识形态控制，封杀网络，监控言论....
五十年前文革批斗刘少奇
![image](https://user-images.githubusercontent.com/24697768/55210969-df4a4e80-5224-11e9-80f2-c68175156598.png)

五十年后逼最高人民法院大法官认罪
![image](https://user-images.githubusercontent.com/24697768/55210909-a27e5780-5224-11e9-9251-0c0a6d6dd86e.png)

**大陆的人权、自由、法律早已死去**，何以解忧，唯有移民！

**Comment by xunboo** [comment]
活该，这就是你们的父辈的父辈们作出的选择

**Comment by wendrewshay** [comment]
维权归维权，但不要反党反国家，不然你把我们大家都拖下水了

**Comment by xnng** [comment]
请不要犯政治错误

**Comment by niehui** [comment]
又想把大家帶偏了？開發者的訴求是抵制 996 公司，要求國家修理這些公司，根本沒有反政府。

**Comment by wuxuebai** [comment]
哈哈 当初民国给你们民主  老蒋给你们自由   你们不要 你们都支持共产党 现在共产党真的执政了  结果专政独裁比国民党狠一万倍 ！

**Comment by isrobin** [comment]
带尼玛的节奏，草拟吗，loser

**Comment by JavaXiaoJun** [comment]
节奏狗滚尼玛

**Comment by wy514** [comment]
请不要犯政治错误

**Comment by 0xe590b4** [comment]
我们争取权利， 但是 我们更爱自己的国  傻逼法轮份子滚吧！

**Comment by jemmy117** [comment]
不合法的背后 都有一层保护伞 和 不作为！

**Comment by LingHS** [comment]
你们看这哥们的介绍，反共势力啊！！

**Comment by wzg110** [comment]
这带节奏就不好了吧

**Comment by Rookie-liu** [comment]
带节奏的孤儿

**Comment by mika-cn** [comment]
确实早就没人权了，看了此楼的回复，唉，洗脑教育太可怕了

**Comment by isrobin** [comment]
> 确实早就没人权了，看了此楼的回复，唉，洗脑教育太可怕了

想要人权，请移民去印度，去不被洗脑的地方，就你没有被洗脑？傻逼loser

**Comment by mika-cn** [comment]
> > 确实早就没人权了，看了此楼的回复，唉，洗脑教育太可怕了
> 
> 想要人权，请移民去印度，去不被洗脑的地方，就你没有被洗脑？傻逼loser

祝你在思想高度一致的土地上，长命

**Comment by isrobin** [comment]
> > > 确实早就没人权了，看了此楼的回复，唉，洗脑教育太可怕了
> > 
> > 
> > 想要人权，请移民去印度，去不被洗脑的地方，就你没有被洗脑？傻逼loser
> 
> 祝你在思想高度一致的土地上，长命
嗯，祝你在皿煮，自由，有人权的印度，缅甸享受快乐，另外说一句，不是别人思想高度一致，而是你思考的层次太低，多元化的东西你看不见，多读点书吧。

**Comment by mika-cn** [comment]
> > > > 确实早就没人权了，看了此楼的回复，唉，洗脑教育太可怕了
> > > 
> > > 
> > > 想要人权，请移民去印度，去不被洗脑的地方，就你没有被洗脑？傻逼loser
> > 
> > 
> > 祝你在思想高度一致的土地上，长命
> > 嗯，祝你在皿煮，自由，有人权的印度，缅甸享受快乐，另外说一句，不是别人思想高度一致，而是你思考的层次太低，多元化的东西你看不见，多读点书吧。

劝别人移民，这种层次，高得到哪里去？

**Comment by mika-cn** [comment]
> > > > 确实早就没人权了，看了此楼的回复，唉，洗脑教育太可怕了
> > > 
> > > 
> > > 想要人权，请移民去印度，去不被洗脑的地方，就你没有被洗脑？傻逼loser
> > 
> > 
> > 祝你在思想高度一致的土地上，长命
> > 嗯，祝你在皿煮，自由，有人权的印度，缅甸享受快乐，另外说一句，不是别人思想高度一致，而是你思考的层次太低，多元化的东西你看不见，多读点书吧。

另，大胆地打上「民主」，别再自我审查了
