### ISSUE TITLE
采访一下习大大，您对工作制度“996”是持什么态度？有什么看法？

### ISSUE THREAD

**Issue by JerryWang24** [996icu/996.ICU#20607]

**Comment by Jayzhanscar** [comment]
小学毕业的文化你还想让他干嘛

**Comment by zjlxgxz** [comment]
http://www.xinhuanet.com/politics/leaders/2019-03/24/c_1124275623.htm

**Comment by qq260327056** [comment]
什么 态度？你们这些人哪，想我当主席时天天加班到晚上四五点也不叫累，你加班到九点就叫累了？还是没有奋斗精神啊

**Comment by anhuidazhou** [comment]
天天加班有利于GDP，有利于维稳。

**Comment by szhielelp** [comment]
我他妈加班到9点**凭什么不能说累**
**凭什么不能说累1？**
搞得好像我的工作能够管理这个国家一样

**Comment by y888** [comment]
最高领袖习胖会声称自己是007 ，你们996闹个屁。
证据是最近跛脚了，“中国领导人习近平正在欧洲访问，但却被外媒发现他的脚步出现异常”
https://www.youtube.com/watch?v=PSD6ZBSTQEs

**Comment by biejun** [comment]
习大大：“我国目前还处于经济发展的初级阶段，希望全国人民继续投身奋斗小康的目标中去，撸起袖子加油干！996是中国发展速度的自豪！”
