### ISSUE TITLE
有这时间，还不如多看会极客时间，提升自己，早点换工作

### ISSUE THREAD

**Issue by xishuixixia** [996icu/996.ICU#20618]
有这时间，还不如多看会[极客时间](https://time.geekbang.org/)，提升自己，早点换工作

**Comment by wy514** [comment]
996早晚会蔓延开来。

**Comment by moetakaoruko** [comment]
大厂都是996，提升自己就能改变社会吗？愚蠢

**Comment by liangmidi** [comment]
楼上的未来ICU名单

**Comment by NeverMoes** [comment]
SB玩意，以后全是996看你往哪跑。

**Comment by JHsunshine** [comment]
早点换工作，换份997的呵呵呵

**Comment by MG0934** [comment]
冷漠的人，迟早也是别人眼中的人

**Comment by EnjoyFalse** [comment]
在茅坑里的虫怎么提升不还是茅坑里吗？除非飞出墙外去了吧

**Comment by Sthpencurry** [comment]
你这广告打的太刻意了

**Comment by qq260327056** [comment]
还提升自己？1887年美国芝加哥劳动大游行，要求8小时工作，8小时休息，8小时给自己。

现在我们的8小时都给了资本家了，还怎么提升自己？

**Comment by lbyxunxunnini** [comment]
> 有这时间，还不如多看会[极客时间](https://time.geekbang.org/)，提升自己，早点换工作
滚出去多好，提升了就不用996了吗

**Comment by huabeiyipilang** [comment]
重度斯德哥尔摩综合征，快进ICU

**Comment by Android-xiaole** [comment]
当纳粹来抓共产主义者的时候， 我保持沉默； 我不是共产主义者。 当他们囚禁社会民主主义者的时候， 我保持沉默； 我不是社会民主主义者。 当他们来抓工会会员的时候， 我没有抗议； 我不是工会会员。 当他们来抓犹太人的时候， 我保持沉默； 我不是犹太人。 当他们来抓我的时候， 已经没有人能替我说话了。--马丁·尼莫拉

**Comment by ShaderFallback** [comment]
典型的别人把你卖了还帮别人数钱的人

**Comment by szhielelp** [comment]
提升自己? 你告诉我他们9点回去能够干嘛?
你告诉我周日一天能干吗?
通宵打麻将吗?

**Comment by xishuixixia** [comment]
关注996.ICU这项目的人，大多是弱者吧。如果你讨厌这个现状，要么给你老板写邮件，让他改变，要么就离职。当然， 你厉害点，可以移民跑欧洲，那里的程序员过得挺轻松。再者，你还可以选择接受。

我觉得这是一个时代和国情的问题，没有对错之分，也许过些年一切都会改变，你回到小城市也会改变。有人把这事和马丁·尼莫拉的那句话联系到一起，纯属蛊惑人心，都TM成年人。
