### ISSUE TITLE
不满996就离职换地方呗。

### ISSUE THREAD

**Issue by ryouaki** [996icu/996.ICU#20636]
不愿意干就离职换地方呗。真的不知道有啥吵的。特别搞不懂那种天天对公司不满。然后还在那里上班接受压迫的人。

**Comment by Android-xiaole** [comment]
当纳粹来抓共产主义者的时候， 我保持沉默； 我不是共产主义者。 当他们囚禁社会民主主义者的时候， 我保持沉默； 我不是社会民主主义者。 当他们来抓工会会员的时候， 我没有抗议； 我不是工会会员。 当他们来抓犹太人的时候， 我保持沉默； 我不是犹太人。 当他们来抓我的时候， 已经没有人能替我说话了。--马丁·尼莫拉

**Comment by bmax121** [comment]
你怕是来着找骂哦

**Comment by qq260327056** [comment]
公司违法居然要员工换地方？你得多脑残？

**Comment by qq260327056** [comment]
别人要强烈你妈，你居然说你妈不会逃吗？怎么会张开腿给他？

**Comment by leanang** [comment]
你可以不说话，但是你不能阻止别人发声

**Comment by SunnyTang** [comment]
现在还只是部分公司996，如果所有公司都996的话，你是没有地方可换的

**Comment by weipinglee** [comment]
以后你就没地方换了，都是996了

**Comment by ryouaki** [comment]
> 以后你就没地方换了，都是996了

我工作这么多年还没去过要求996的公司。。。。。
