### ISSUE TITLE
已经排名第九了这个有点吓人啊，把外国友人吓到了！

### ISSUE THREAD

**Issue by Qiaoshi96** [996icu/996.ICU#20668]

**Comment by zdihua** [comment]
加油干，顶到第一位上去！

**Comment by Nevermind1** [comment]
咋个看排名啊

**Comment by sadlar** [comment]
> 咋个看排名啊
https://github.com/search?o=desc&p=1&q=stars%3A%3E50000&s=stars&type=Repositories

**Comment by glitterxuan** [comment]
https://github-battle-2.firebaseapp.com/popular

**Comment by Nevermind1** [comment]
> > 咋个看排名啊
> > https://github.com/search?o=desc&p=1&q=stars%3A%3E50000&s=stars&type=Repositories

赞

**Comment by Qiaoshi96** [comment]
> 咋个看排名啊
stars:>80000  可以看到

**Comment by Geno1024** [comment]
> > 咋个看排名啊
> > stars:>80000  可以看到

搜索词从 50000 上升到 80000 了 :lol:
