### ISSUE TITLE
共产党宣言文字

### ISSUE THREAD

**Issue by PeterXiao** [996icu/996.ICU#20676]
https://www.marxists.org/chinese/marx/01.htm

**Comment by PeterXiao** [comment]
资产阶级在它已经取得了统治的地方把一切封建的、宗法的和田园诗般的关系都破坏了。它无情地斩断了把人们束缚于天然尊长的形形色色的封建羁绊，它使人和人之间除了赤裸裸的利害关系，除了冷酷无情的“现金交易”，就再也没有任何别的联系了。它把宗教虔诚、骑士热忱、小市民伤感这些情感的神圣发作，淹没在利己主义打算的冰水之中。它把人的尊严变成了交换价值，用一种没有良心的贸易自由代替了无数特许的和自力挣得的自由。总而言之，它用公开的、无耻的、直接的、露骨的剥削代替了由宗教幻想和政治幻想掩盖着的剥削。

**Comment by PeterXiao** [comment]
现代工业已经把家长式的师傅的小作坊变成了工业资本家的大工厂。挤在工厂里的工人群众就象士兵一样被组织起来。他们是产业军的普通士兵，受着各级军士和军官的层层监视。他们不仅是资产阶级的、资产阶级国家的奴隶，并且每日每时都受机器、受监工、首先是受各个经营工厂的资产者本人的奴役。这种专制制度越是公开地把营利宣布为自己的最终目的，它就越是可鄙、可恨和可恶。

**Comment by 285964377** [comment]
这位爷 这位爷 咱们莫谈国事 莫谈国事啊~

**Comment by PeterXiao** [comment]
资产阶级生存和统治的根本条件，是财富在私人手里的积累，是资本的形成和增殖；资本的条件是雇佣劳动。雇佣劳动完全是建立在工人的自相竞争之上的。资产阶级无意中造成而又无力抵抗的工业进步，使工人通过结社而达到的革命联合代替了他们由于竞争而造成的分散状态。于是，随着大工业的发展，资产阶级赖以生产和占有产品的基础本身也就从它的脚下被挖掉了。它首先生产的是它自身的掘墓人。资产阶级的灭亡和无产阶级的胜利是同样不可避免的。

**Comment by PeterXiao** [comment]
正如僧侣总是同封建主携手同行一样，僧侣的社会主义也总是同封建的社会主义携手同行的。
　　要给基督教禁欲主义涂上一层社会主义的色彩，是再容易不过了。基督教不是也激烈反对私有制，反对婚姻，反对国家吗？它不是提倡用行善和求乞、独身和禁欲、修道和礼拜来代替这一切吗？基督教的社会主义，只不过是僧侣用来使贵族的怨愤神圣化的圣水罢了。

**Comment by PeterXiao** [comment]
这种社会主义的另一种不够系统、但是比较实际的形式，力图使工人阶级厌弃一切革命运动，硬说能给工人阶级带来好处的并不是这样或那样的政治改革，而仅仅是物质生活条件即经济关系的改变。但是，这种社会主义所理解的物质生活条件的改变，绝对不是只有通过革命的途径才能实现的资产阶级生产关系的消灭，而是一些行政上的改良，这些改良是在这种生产关系的基础上实行的，因而丝毫不会改变资本和雇佣劳动的关系，至多只能减少资产阶级的统治费用和简化它的财政管理。
　　资产阶级的社会主义只有在它变成纯粹的演说辞令的时候，才获得自己的适当的表现。
　　自由贸易！为了工人阶级的利益；保护关税！为了工人阶级的利益；单身牢房！为了工人阶级的利益。——这才是资产阶级的社会主义唯一认真说出的最后的话。
　　资产阶级的社会主义就是这样一个论断：资产者之为资产者，是为了工人阶级的利益。

**Comment by PeterXiao** [comment]
批判的空想的社会主义和共产主义的意义，是同历史的发展成反比的。阶级斗争越发展和越具有确定的形式，这种超乎阶级斗争的幻想，这种反对阶级斗争的幻想，就越失去任何实践意义和任何理论根据。所以，虽然这些体系的创始人在许多方面是革命的，但是他们的信徒总是组成一些反动的宗派。这些信徒无视无产阶级的历史进展，还是死守着老师们的旧观点。因此，他们一贯企图削弱阶级斗争，调和对立。他们还总是梦想用试验的办法来实现自己的社会空想，创办单个的法伦斯泰尔，建立国内移民区，创立小伊加利亚，即袖珍版的新耶路撒冷，——而为了建造这一切空中楼阁，他们就不得不呼吁资产阶级发善心和慷慨解囊。他们逐渐地堕落到上述反动的或保守的社会主义者的一伙中去了，所不同的只是他们更加系统地卖弄学问，狂热地迷信自己那一套社会科学的奇功异效。
　　因此，他们激烈地反对工人的一切政治运动，认为这种运动只是由于盲目地不相信新福音才发生的。
　　在英国，有欧文主义者反对宪章派，在法国，有傅立叶主义者反对改革派。

**Comment by PeterXiao** [comment]
总之，共产党人到处都支持一切反对现存的社会制度和政治制度的革命运动。
　　在所有这些运动中，他们都特别强调所有制问题是运动的基本问题，不管这个问题的发展程度怎样。
　　最后，共产党人到处都努力争取全世界的民主政党之间的团结和协调。
　　共产党人不屑于隐瞒自己的观点和意图。他们公开宣布：他们的目的只有用暴力推翻全部现存的社会制度才能达到。让统治阶级在共产主义革命面前发抖吧。无产者在这个革命中失去的只是锁链。他们获得的将是整个世界。

**Comment by xunboo** [comment]
共产党人不屑于隐瞒自己的观点和意图。他们公开宣布：他们的目的只有用暴力推翻全部现存的社会制度才能达到。让统治阶级在共产主义革命面前发抖吧。无产者在这个革命中失去的只是锁链。他们获得的将是整个世界。


获得整个世界然后呢？变成统治阶级？然后再用暴力推翻自己？永远循环下去？

**Comment by PeterXiao** [comment]
伏脱冷太骄傲了，以至于他在代表邪恶向善良致敬的时候太过迟疑。或者说得更明白一点，他不愿意表现得太过伪善，他不愿意掩饰自己的邪恶。他以为他可以在捞到了足够多的油水之后再去洗手，却不明白，在世界这个大厨房里，想要向上爬的人不但必须不断的“干脏活”“弄脏手”也需要不断的洗自己的手，让它在任何时候都显得是那么的白那么的香。

**Comment by PeterXiao** [comment]
良好的声誉也能成为一些事件发生时的护身符。这家工厂的前任主人斯特鲁在遭到指责和攻击之后几乎毫无回击的能力，这里面一个很重要的原因就在于他以前的口碑就不太好。在史高治上辈子读书的时候，听到过这样一个笑话。说是在一所学校里，有一天老师在上课，看到王某某又睡着了，于是大怒，批评他说：“你怎么一天到晚就知道睡觉，一读书就睡觉？你看看人家李某某……”然后老师一回头，发现李某某正把脸埋在书里面睡着了。于是老师又说：“你看，人家睡觉都在看书呢。”

**Comment by PeterXiao** [comment]
汉密尔顿的解释看起来是很有道理的，这正体现了自由经济的理想。企业可以自由的选择员工，员工也可以自由的选择企业。即使是现在，自由经济的推崇者们依然在宣称，既然，在这个双向的选择中大家都是自由的，是自愿的，那么自然就不存在所谓的剥削和压迫。而相反，如果干涉了这种自由，无论是不允许工人们自由的选择效力的企业，或者是不允许企业自由的选择员工，那都是通往奴役之路。

**Comment by PeterXiao** [comment]
的确并没有直接的控制那么多的媒体，那些媒体从法律上来说，的确是独立的媒体。它们的主要出资人也不是麦克唐纳，而是一些同样独立的非营利性的机构，而这些非盈利性机构的出资人——你管这么多干啥？这是保密的知道吗？是商业秘密，受阿妹你看法律保护的。当然，作为美国最著名的慈善家，****先生给这些致力于崇高目标的非营利性组织捐过不少的款，那也是毫无疑问的。

**Comment by PeterXiao** [comment]
对于历史，对于经济局面的分析，无不受益于这种伟大的理论。正是这种理论，揭示了笼罩在纷纭复杂的社会经济现象和繁芜丛杂的意识形态之后的人类社会发展的规律，资本运作的规律。依照着这样的认识，史高治才能牢牢的抓住时代的主流，发家致富。

**Comment by PeterXiao** [comment]
比如说现在，在想清楚共产主义运动对于我的好处之后，我都想要偷偷的出钱去支持这种运动了。嗯，不愿意卖出绞死自己的绳套的资本家，不是真正的资本家！”

**Comment by PeterXiao** [comment]
“相信群众，依靠群众。从群众中来，到群众中去。群众的眼睛是雪亮的。”史高治带着讽刺的微笑说，“但是**，人民群众有两个大问题。一个问题是他们没有时间，没有精力来了解来监督国家机器的运行。我前面说过了，社会生产的组织是如此复杂，以至于非专业人士根本看不懂。”
