### ISSUE TITLE
京东智能客服对话大赛 JDDC 亚军解决方案 

### ISSUE THREAD

**Issue by Dikea** [996icu/996.ICU#20682]
[Dialog-System-with-Task-Retrieval-and-Seq2seq](https://github.com/Dikea/Dialog-System-with-Task-Retrieval-and-Seq2seq)
成绩：并列亚军，成绩排名第三，奖金10万元。
方案：初赛使用检索匹配模型，决赛使用生成模型，人工评估使用综合对话框架。详情请参见设计文档。

**Comment by theta666** [comment]
g u n

**Comment by wentaojia2014** [comment]
真是讽刺。抵制某东的地方，出现某东的活动宣传广告。可见这个抵制屁用没有。
