### ISSUE TITLE
感觉你们挺幼稚的，行业现在这个样子，本质就是开发人员的供需平衡被打破了

### ISSUE THREAD

**Issue by hz0324** [996icu/996.ICU#20698]
996的本质是时薪下降，低时薪的原因是程序员早就供过于求了。瞎折腾没有用。

**Comment by wencan** [comment]
+1

**Comment by AaronRD** [comment]
so？可以不遵守法律法规？

**Comment by Zam233** [comment]
那么为什么会有人求呢？求的人哪来的钱呢？

**Comment by lbyxunxunnini** [comment]
你应该是个企业领导吧

**Comment by saber200** [comment]
请问您吃的是哪家的人血馒头？

**Comment by BetterPHPer** [comment]
资本家视角来啦！

**Comment by hz0324** [comment]
想要严格按照劳动法办？那就裁员呗。看看去年年底多少企业突击裁员，就是因为今年要强制补齐社保金，企业为了降低成本，只能裁员。你们以为按劳动法办，你们可以拿着同样的高薪？开什么玩笑呢？

**Comment by xiangbo2015** [comment]
你早点回家种地去。别来参观

**Comment by ExtremeYu** [comment]
你有病吧？人治还是法治？你是不是还想说灭霸灭一半人口就不用996了？三岁小孩你啊？

**Comment by ExtremeYu** [comment]
你有病吧？人治还是法治？你是不是还想说灭霸灭一半人口就不用996了？三岁小孩你啊？

**Comment by NaoziXu** [comment]
需要加班->供过于求
这位大叔你说话真风趣

**Comment by KarryCol** [comment]
认识你的人会怎么回复你

**Comment by MusixNotMusic** [comment]
典型的资本家，互联网不·剥削是养不起那么大的吸血👻的！

**Comment by LangZhai** [comment]
智商捉急，真正供过于求是人人都在街上跪着求代码写，而不是有写不完的代码！

**Comment by xlhandsome** [comment]
放屁，明显个别企业的恶性竞争产生 纳什平衡 让整个行业收敛于恶性竞争，和多少程序员有个毛关系

**Comment by by415304229** [comment]
明明供小于求,根本招不到人

**Comment by hz0324** [comment]
哎，祝你们好运吧。我看你们也就是撒撒气，连问题的本质都看不到，那就不可能改变自己的处境。
