### ISSUE TITLE
看了这里的Issue我知道你们为什么要加班了

### ISSUE THREAD

**Issue by phoenixgao** [996icu/996.ICU#20770]
有空GitHub闲聊啊？

**Comment by tinshee** [comment]
程序员是机器？

**Comment by meiyoumingziyongle** [comment]
我甚至还要水群

**Comment by cb360** [comment]
it行业，浮躁、996的本质原因有一个重要的因素是不重视中层，开除有经验的大龄员工，只想着用时间碓，靠压榨小鲜肉来前进，人才梯队，技术管理一塌糊涂，浮肿的胖子而已，资本催促，一地鸡毛。
