### ISSUE TITLE
相关部门不会管的，别想了

### ISSUE THREAD

**Issue by GdinKing** [996icu/996.ICU#20804]
我公司就是给政府做项目的，省长市长都了解，政府的项目天天加班，9点到晚上11点，每周6天，通宵也是经常的事，你以为政府他们不知道么？谁会管你

**Comment by qq260327056** [comment]
自己的健康自己救！！！这个世界从来就没有什么 救世主！国际歌是怎么唱的？先纳喊起来！

**Comment by phoenixgao** [comment]
政府有很多部门，12333是肯定会管的。

**Comment by hakur** [comment]
人多命贱,只能自求多福

**Comment by davidSeven** [comment]
> 政府有很多部门，12333是肯定会管的。

12333是干啥的，它要是管了，会发生什么

**Comment by jaredtech** [comment]
起来！不愿做奴隶的人们！
把我们的血肉筑成我们新的长城！
程序员们到了最危险的时候，
每个人被迫着发出最后的吼声。
起来！起来！起来！
我们万众一心，
冒着敌人的炮火，前进！
冒着敌人的炮火，前进！
前进！前进、进！

**Comment by 11084956** [comment]
解决这个问题只能找有关部门

问题是我们大中华没有“有关部门”这个单位 哈哈
