### ISSUE TITLE
关于996工会实施考虑

### ISSUE THREAD

**Issue by msDating** [996icu/996.ICU#20819]
我作为一个程序猿，996真的很可恶，想成立一个全国性质的工会，第一 入会一定要填写真实有效的身份 工作信息，并且会专门验证填写信息，每年会费大概10元钱，为的是能够保障程序猿的权益，工会回请律师 一但发生劳动合同纠纷 ，程序猿可以申请工会律师介入。一但程序猿过多，我们可以自己成立程序员招聘群，但是工会也要把好关，可以成立技术群，促进程序猿的技术交流。如果有想法，想成立工会的，请加qq960206782

**Comment by Gomuko** [comment]
怎么总有人这么naive啊，工会要么是合法且没用的，要么是有用但非法的，用QQ就是想合法且有用，这是不可能的。假如可行早就变天了。
