### ISSUE TITLE
诺大的中国，难道连一个github第一都冲不到么

### ISSUE THREAD

**Issue by TheOneChina** [996icu/996.ICU#20820]

**Comment by dugutianxue** [comment]
在哪看到的排名？？

**Comment by Destiny970515** [comment]
> 在哪看到的排名？？

https://github-battle-2.firebaseapp.com/popular

**Comment by xnng** [comment]
如果这个是跟「明星」有关的事件的话，别说第一了，网站服务器搞崩都不在话下

**Comment by TheOneChina** [comment]
搜索框内输入:stars:>70000




| |
18576702314
邮箱：18576702314@163.com
|

Signature is customized by Netease Mail Master

在2019年03月29日 13:52，独孤天血 写道：

在哪看到的排名？？

**Comment by LemonZero** [comment]
别的不提，论人数，谁比得过恰伊那

**Comment by TheOneChina** [comment]
搜索框内输入 stars:>70000,然后选择stars排序就好了
