### ISSUE TITLE
out996 项目组招募贡献者

### ISSUE THREAD

**Issue by zhoushuren** [996icu/996.ICU#20845]
https://github.com/out996/recruit/

这是我建的一个组，后续我会搞个 .org 的域名。本人无业中，可全职做这个项目。
一个人的力量是有限的，希望大家一起参与。
想参与的朋友留言，我拉你进组。一起为革命贡献力量吧

希望你是产品，前端，后端，运维，以及运营。

**Comment by inlics** [comment]
前端 +1
