### ISSUE TITLE
大家有没有听说过一个叫Grab的公司，不加班，15天年假，CEO还要求必须休完

### ISSUE THREAD

**Issue by realcarlos** [996icu/996.ICU#2100]
这家公司很喜欢新技术Swift，Kotlin，Flutter，Golang，都已经大规模投入生产，每周都组织篮球，足球，羽毛球活动，夏天每天中午去游泳，冬天周末一起去滑雪，时不时就新马泰出差，有兴趣的了解一下。

![IMG_3453](https://user-images.githubusercontent.com/13853/55123115-5657e800-513c-11e9-9caa-86f2978924fc.JPG)

![IMG_0583](https://user-images.githubusercontent.com/13853/55122900-936faa80-513b-11e9-8ab9-4a27d170cff5.JPG)

![IMG_1263](https://user-images.githubusercontent.com/13853/55122903-94084100-513b-11e9-8c91-24b6f26d3019.JPG)

<img width="904" alt="屏幕快照 2019-03-28 上午9 29 10" src="https://user-images.githubusercontent.com/13853/55123021-f6f9d800-513b-11e9-87bf-15ec09946b37.png">

<img width="521" alt="屏幕快照 2019-03-28 上午9 29 43" src="https://user-images.githubusercontent.com/13853/55123047-0e38c580-513c-11e9-9784-1309c2d61caf.png">

**Comment by somnuscheung** [comment]
HR?

**Comment by realcarlos** [comment]
> HR?

明显不是，我是码农啊

**Comment by Fretice** [comment]
这公司的产品我用过,,有一个坑的地方 就是能现金付钱给司机 然后绑定卡了以后还会扣钱

**Comment by realcarlos** [comment]
正确的使用方法是，不绑卡不绑支付宝，直接现金，因为我们的app是一口价

**Comment by 2014111963** [comment]
这个公司在哪？国内国外？

**Comment by realcarlos** [comment]
在北京，中关村，融科资讯中心，和谷歌一个楼

**Comment by realcarlos** [comment]
内推，简历请发 1185607@qq.com

**Comment by shiroh0527** [comment]
敬业爱岗，艾特一下少麟
