### ISSUE TITLE
帮大佬宣传下，想成为顶尖架构师么？那你一定要进来看看（经常有送书活动额）

### ISSUE THREAD

**Issue by Nicholas2014** [996icu/996.ICU#21796]
![image](https://user-images.githubusercontent.com/9709321/55213996-3144a180-5230-11e9-8448-3fdeb2d4f520.png)

**Comment by thousmile** [comment]
我宣传你妈的了隔壁！你个龟孙子！草拟吗！蹭你麻痹的热度

**Comment by dongfangyiyu** [comment]
打广告的都是尼玛吃人血馒头的，求求你们不要赚黑心钱啦！

**Comment by iqwxiaopeng** [comment]
我宣传你妈的了隔壁！你个龟孙子！草拟吗！蹭你麻痹的热度

**Comment by 312495624** [comment]
我日你妈！！！！

**Comment by Nicholas2014** [comment]
> 我日你妈！！！！
