### ISSUE TITLE
.....................

### ISSUE THREAD

**Issue by fangsidian** [996icu/996.ICU#22314]

**Comment by liuxiaobina** [comment]
老哥，从程序员开始啊

**Comment by lich** [comment]
他们也可以集中爆发，不过 我觉得国家不会允许大型线下聚会，参考内涵段子。

**Comment by songyiwei** [comment]
1.高中生远比996惨，高三起码得706-707
2.高中生冲刺3-4年，程序员从毕业22岁起码干到35岁（然后失业...）
3.民营企业大部分是生产线，不能停，倒班制，三班倒、两班倒。
