### ISSUE TITLE
警钟长鸣0

### ISSUE THREAD

**Issue by jiayy** [996icu/996.ICU#23257]
[如何看待年仅 25 岁的大疆 DJI 员工或因过劳而猝死家中？公司是否应当承担责任？](https://www.zhihu.com/question/305280080)

**Comment by jiayy** [comment]
[如何看待年仅 25 岁的大疆 DJI 员工或因过劳而猝死家中？公司是否应当承担责任？](https://www.zhihu.com/question/305280080)
[如何看待 36 岁清华毕业 IT 男马桶上猝死，死前对母亲说「太累」？](https://www.zhihu.com/question/29357990)
[]()
[]()

[]()

**Comment by bybywudi** [comment]
支持
