### ISSUE TITLE
不用反驳！程序员就是怂！

### ISSUE THREAD

**Issue by long2ltoy** [996icu/996.ICU#2356]
你们只会在网上BB，你们的公会是摆设吗？ 你们会去劳动部门投诉吗？
如果上面都无效！哪你们都是程序员，就不会做个网站专门维护自己的利益吗，特别是哪些打擦边球的黑公司，曝光出来，让找工作的人都看看？
发声社交也不会，技术也派不上用场，你们的自豪呢？还想有人理你？
不用反驳，程序员最怂！是个人都能管理好你们！
信不信现在已经不只一家公司向GITHUB发信要求查本G主的身份信息？信不信下一秒这个PROJECT就消失？
你们说你们还能退到哪里！还想退到哪里？后面就是ICU！

**Comment by DENGandR** [comment]
说的好像投诉了就有用一样😂

**Comment by long2ltoy** [comment]
建议GIT主使用小众聊天工具建个大群收集违法信息，一定要小众软件，微信这种很可能被封。

**Comment by long2ltoy** [comment]
@996icu

**Comment by long2ltoy** [comment]
留下交流方式，使用SKYPE或是米聊什么的就可以，这个PROJECT我看活不长了 @996icu
