### ISSUE TITLE
965想找个996涨工资有吗

### ISSUE THREAD

**Issue by zhangzhaoyuan30** [996icu/996.ICU#2415]

**Comment by netsman1030** [comment]
996想找个ICU花钱有吗

**Comment by SunnyTang** [comment]
你是不想活的节奏吗。。。，

**Comment by a77321a** [comment]
感觉只有沙雕才觉得自己年轻身体随便折腾

**Comment by zhangzhaoyuan30** [comment]
> 感觉只有沙雕才觉得自己年轻身体随便折腾

你妈没教你礼貌？

**Comment by ydw2305** [comment]
经常加班很容易过劳的~

**Comment by netsman1030** [comment]
> > 感觉只有沙雕才觉得自己年轻身体随便折腾
> 
> 你妈没教你礼貌？

你的心肝裨肺肾比起民工好不了多少，自贱身体卖命换钱，跟卖肾买苹果的没啥区别。
你看对于主动卖肾的家伙谁礼貌的起来？

**Comment by zhangzhaoyuan30** [comment]
> > > 感觉只有沙雕才觉得自己年轻身体随便折腾
> > 
> > 
> > 你妈没教你礼貌？
> 
> 你的心肝裨肺肾比起民工好不了多少，自贱身体卖命换钱，跟卖肾买苹果的没啥区别。
> 你看对于主动卖肾的家伙谁礼貌的起来？

**Comment by zhangzhaoyuan30** [comment]
> > > > 感觉只有沙雕才觉得自己年轻身体随便折腾
> > > 
> > > 
> > > 你妈没教你礼貌？
> > 
> > 
> > 你的心肝裨肺肾比起民工好不了多少，自贱身体卖命换钱，跟卖肾买苹果的没啥区别。
> > 你看对于主动卖肾的家伙谁礼貌的起来？
