### ISSUE TITLE
建议大家把强制996的公司名称和坐标发出来,为以后不想入坑的兄弟提个醒

### ISSUE THREAD

**Issue by chinachance** [996icu/996.ICU#2433]

**Comment by guopuu** [comment]
顶一个

**Comment by chinachance** [comment]
我先来  
赞包网络   坐标杭州

**Comment by long2ltoy** [comment]
怂的一B，是不会说的。已知就是京东，有赞，除此再爆一家北京联创智融，原来还有加班费，现在加班费也没有，原来还能倒休，其实项目经理根本不会给你时间倒休，一直干到你出组。其实你们问问身边的朋友就知道了，基本上都在加班。主要是没加班费。

**Comment by kbxwn** [comment]
然后你就发现找不到公司了
