### ISSUE TITLE
#滑稽#996怎么了  现在的年轻人一点苦都吃不了 

### ISSUE THREAD

**Issue by coolcoolchan** [996icu/996.ICU#244]

**Comment by YuHang0121151624** [comment]
996没问题，但希望能够按照劳动法支付额外工时的加班费。

**Comment by fengleon** [comment]
吃苦可以啊~~吃苦为了收入，不是为了吃苦而吃苦~

**Comment by EzrealJ** [comment]
你头绿了

**Comment by ExtremeYu** [comment]
马德你又是哪根葱，吃的是不是真正的苦是你几把乱说的？

**Comment by monkeyhai** [comment]
现在的年轻人不是怕996，而是反对与薪酬不挂钩的996

**Comment by fengleon** [comment]
是的，谁工作不是为了那点工资，老板虚头八脑的情怀，奋斗，公司前景无限，说白了，和你有关系么，关系大么，以后就算你做到主管、总监的位置，是看你的能力，而不是老板的情怀。

**Comment by zzwphp** [comment]
一点苦？？？按照劳动法规定，996 工作制下只有拿到当前工资的 2.275 倍，才在经济账上不吃亏。也就是说，是双倍，这是一点点？？？

**Comment by EldersSun** [comment]
It's a pity that an old thing like you hasn't died yet.

**Comment by EldersSun** [comment]
回到家饭是凉的,b是热的,这就是你.祝你996多一点

**Comment by stefenson** [comment]
看到这么多人骂你我就放心了

**Comment by Sakuraezra** [comment]
年轻人都去给你戴绿帽了

**Comment by Aptxyhrk** [comment]
看到这么多人骂你我就放心了

**Comment by coolcoolchan** [comment]
握草 我不就是忘了加个滑稽吗  程序员的幽默去哪了

**Comment by EzrealJ** [comment]
@coolcoolchan 那你编辑啊

**Comment by coolcoolchan** [comment]
我日了 滑稽是多么重要！！！！！

**Comment by coolcoolchan** [comment]
> 马德你又是哪根葱，吃的是不是真正的苦是你几把乱说的？

我重新编辑了 有时候意思还得表达清楚好点！

**Comment by coolcoolchan** [comment]
> 回到家饭是凉的,b是热的,这就是你.祝你996多一点

我重新编辑了  加滑稽了  我以为大家都有点幽默感！

**Comment by Sakuraezra** [comment]
好惨的楼主~

**Comment by fengleon** [comment]
楼主好惨~~~抱歉刚才我没看出是反讽，我错了，现在弥补一下还来得及么。
哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈，楼主你真幽默

**Comment by pheromone** [comment]
呵呵...

**Comment by xiao333ma** [comment]
加了滑稽还应该加手动狗头

**Comment by taoranqaq** [comment]
你号没了
