### ISSUE TITLE
成都 菁蓉国际 招聘一个前端小姐姐

### ISSUE THREAD

**Issue by driverzhang** [996icu/996.ICU#255]
成都 菁蓉国际 招聘一个中级前端小姐姐

我司决定抵制996，严格执行965，上班活动自由，任务制度，特殊情况可申请在家办公。公司创始人都是10年经验技术大佬，综合素质人品极好。

react优先，Vue也可以 小姐姐快来Q我

**Comment by harryzjm** [comment]
小姐姐没有 小汉子 有哦

**Comment by ApolloRoad** [comment]
HR get out

**Comment by guomaoqiu** [comment]
画饼？HR  get out~~~~~~~~~~~~~~~

**Comment by driverzhang** [comment]
我是后端 小哥哥

**Comment by luzhaoren** [comment]
小姐姐？你做梦，祝你996

**Comment by leefengzi** [comment]
小姐姐不可能的，永远都不可能的

**Comment by rechun** [comment]
我写了一个月react

之前写了半年vue

**Comment by suichukewan** [comment]
嘻嘻

**Comment by driverzhang** [comment]
来啊 前端小姐姐

**Comment by driverzhang** [comment]
> 我写了一个月react
> 
> 之前写了半年vue

来撒 成都

**Comment by rechun** [comment]
> > 我写了一个月react
> > 之前写了半年vue
> 
> 来撒 成都

我只来996的创业公司哦

**Comment by suichukewan** [comment]
> > > 我写了一个月react
> > > 之前写了半年vue
> > 
> > 
> > 来撒 成都
> 
> 我只来996的创业公司哦

我们公司996，来吗

**Comment by YaoJuan** [comment]
> > > 我写了一个月react
> > > 之前写了半年vue
> > 
> > 
> > 来撒 成都
> 
> 我只来996的创业公司哦

秀！

**Comment by guo-kai** [comment]
25小时高强度工作  嚯嚯嚯

**Comment by driverzhang** [comment]
> > > 我写了一个月react
> > > 之前写了半年vue
> > 
> > 
> > 来撒 成都
> 
> 我只来996的创业公司哦

小姐姐真优秀。

**Comment by welpher** [comment]
好远啊

**Comment by phx350z** [comment]
看成了前台小姐姐...

**Comment by samsaraK** [comment]
同在园区的前端小姐姐举手，写了一年vue了，上线项目也有几个~可以q你么

**Comment by OracleRubyRose** [comment]
![微信图片_20190328113116](https://user-images.githubusercontent.com/16449385/55128628-2e25b480-514f-11e9-8c6e-c12d35c5f233.jpg)

**Comment by myesn** [comment]
![KFURBH5) (O$42R6533`5FJ](https://user-images.githubusercontent.com/18598579/55144520-f5e89b00-517b-11e9-91a9-69211b7ce451.gif)
@suichukewan

**Comment by suichukewan** [comment]
@myesn   [图片]

**Comment by suichukewan** [comment]
@myesn   
![Q}X%4@)TJ1)XL@`@`1_YJ3I](https://user-images.githubusercontent.com/19454577/55144765-7c04e180-517c-11e9-92fa-9e8150b9944f.jpg)

**Comment by driverzhang** [comment]
> 同在园区的前端小姐姐举手，写了一年vue了，上线项目也有几个~可以q你么

可以啊
