### ISSUE TITLE
英文表达

### ISSUE THREAD

**Issue by nec2017** [996icu/996.ICU#26]
最后的Developer's 建议改为 Developers'
这样的表达更常用一些，也能代表更多人  (つд⊂)

**Comment by hope1** [comment]
我相信作者应该是想致敬Black Lives Matter，不然也是从这里得到了启发。若要改的话，Developer Lives Matter就不错。

**Comment by MewX** [comment]
i18n support，日本也有类似的公司

**Comment by 996icu** [comment]
Fixed. Thanks for reporting. I18n is ongoing.
