### ISSUE TITLE
i need “996” I want it ！！！！ 

### ISSUE THREAD

**Issue by weixin641** [996icu/996.ICU#2718]
i need “996” I want it ！！！！

**Comment by Qiaoshi96** [comment]
fuck you!

**Comment by weixin641** [comment]
> fuck you!

pls fuck me.my open Ass, wait u comming

**Comment by heroPool** [comment]
，，，，，，

**Comment by weixin641** [comment]
> ，，，，，，

kiss my ♂ Ass

**Comment by Qiaoshi96** [comment]
Oh my god! You're such a bitch!

**Comment by Qiaoshi96** [comment]
> > fuck you!
> 
> pls fuck me.my open Ass, wait u comming
Oh my god! You're such a bitch!

**Comment by weixin641** [comment]
oh! ye! this good i like this,do not stop pls!!!!!!!!!!

**Comment by weixin641** [comment]
经历过"936" 的人 觉得“996”其实还行
毕竟大家还是要恰饭的

**Comment by weixin641** [comment]
> > > fuck you!
> > 
> > 
> > pls fuck me.my open Ass, wait u comming
> > Oh my god! You're such a bitch!

oh! ye! this good i like this,do not stop pls!!!!!!!!!!

**Comment by weixin641** [comment]
现在公司哪里还需要iOS开发人员啊，在公司说话都要小声点怕被做后端的打 还要给他们买奶茶喝 不然就会被老板开除 端茶倒水啥的 都要干

**Comment by weixin641** [comment]
在家待业无事可做？快来做兼职复读机
1，在家就可以做，工作简单，只要复读别人说的话就可以。 
2，工作条件简单，只要有一台手机或者电脑就可以做
3，工资日结，每日0元 
我自己和朋友也在做十分简单

**Comment by weixin641** [comment]
大部分程序员心里的重要程度依次为

修复BUG>玩游戏>换键盘>技术撕逼>写新功能>写博客>基友烧烤>睡觉>哄女朋友>洗袜子>讨好领导>写注释>维护别人的代码>做PPT>找女朋友>做饭>跟父母聊天>跟相亲对象聊天>产品经理

**Comment by weixin641** [comment]
[Rick and Morty续订了70集! 比前三季加一起(31集) 集数还多!! ]豆瓣9.8分的超高分美国动画《Rick and Morty》,主创DanHarmon 和Justin Roiland在Ins上边洗澡边宣布Rick and Morty的冒险将继续进行,非常期待了

**Comment by weixin641** [comment]
只狼破解版：magnet:?xt=urn:btih:1C26650172E0288B33BB68E804C7A0717C906F4F

**Comment by weixin641** [comment]
📞蔡徐坤向您发起了篮球邀请

🔘 接受       丨       ⚪接受

**Comment by Qiaoshi96** [comment]
同样是移动端开发，你怎么这么优秀呢。佩服佩服，大佬大佬

**Comment by weixin641** [comment]
> 同样是移动端开发，你怎么这么优秀呢。佩服佩服，大佬大佬

要是能发表情包 就更优秀了

**Comment by YuLaiZ** [comment]
为何你这么秀。。。
