### ISSUE TITLE
有种现象叫做加班的比不加班的能力强

### ISSUE THREAD

**Issue by panhainan** [996icu/996.ICU#279]
同样的任务，加班做完的比不加班做完的能力强，领导看上的是他的加班。

**Comment by zcx666** [comment]
你和老板谈钱，老板和你谈格局，谈价值观，谈理想，洗不明白就说你是白痴，没能力！

**Comment by RekiDunois** [comment]
很神奇，加班做完不是表示你比较菜吗，别人一下午弄好的东西你要加班一个通宵，这不是菜是什么。
领导看重加班那说明领导也是菜。
