### ISSUE TITLE
劳动部门看不到疾苦的年轻人们吗？

### ISSUE THREAD

**Issue by kingswjw** [996icu/996.ICU#283]

**Comment by netsman1030** [comment]
不存在了，现在叫人力资源和社会保障部

**Comment by hyspace** [comment]
程序员再996也是高收入群体 有的是活的更惨的 你不干有的是人想顶你

**Comment by netsman1030** [comment]
> 程序员再996也是高收入群体 有的是活的更惨的 你不干有的是人想顶你

把所有行业30岁以后的工资30岁以前发，人人都是高收入群体

**Comment by hopana** [comment]
你是搞笑的么，你走在路上被车撞了，难道要救护车主动来接你？

**Comment by netsman1030** [comment]
问题现在情况是，满大街人都让车撞了，交警还在梦游。。。

糊糊 <notifications@github.com> 于2019年3月27日周三 下午3:27写道：

**Comment by Pulini** [comment]
劳动局工作人员“哦？不知道诶，这不是我们部门处理的。”

**Comment by tangjucai** [comment]
你以为他们靠谁养？
