### ISSUE TITLE
#杭州 #e签宝 #招聘前端 欢迎砸简历 没有996: )

### ISSUE THREAD

**Issue by godkillCK** [996icu/996.ICU#3142]
![image](https://user-images.githubusercontent.com/8386256/55125335-578d1300-5144-11e9-9216-8807092088d5.png)
内推请发简历至：xuzhu@tsign.cn

**Comment by yanghong** [comment]
后端不要嘛？

**Comment by lin1993** [comment]
996么？不是996不去。

**Comment by YTU94** [comment]
> 后端不要嘛？

要

**Comment by godkillCK** [comment]
> 后端不要嘛？

要 都要

**Comment by LByy** [comment]
你要备注一下 没有996 可能看的人会更多一些。毕竟这里面基本上大多数程序员都在，绝壁有能力强的。

**Comment by YTU94** [comment]
前端小姐姐还很漂亮，linyi@tsign.cn
