### ISSUE TITLE
非996公司招聘-信数金服

### ISSUE THREAD

**Issue by enilu** [996icu/996.ICU#3256]
公司简介：http://www.xinshucredit.com/
招聘职位：java工程师（大数据开发，爬虫工程师）
更多职位招聘：http://www.xinshucredit.com/h-col-166.html
简历请投递至zhangtao@xinshucredit.com
弹性工作制

**Comment by z13974509906** [comment]
你可真是个小机灵鬼~

**Comment by yangjaixi** [comment]
997?

**Comment by pengcongcong** [comment]
你真是个人才

**Comment by agfire** [comment]
三班倒？

**Comment by enilu** [comment]
> 997?

10-7-5
