### ISSUE TITLE
。

### ISSUE THREAD

**Issue by nibihzoay** [996icu/996.ICU#330]

**Comment by shywuyanzhu** [comment]
你生活在奴隶时代应该是条会感恩的狗奴

**Comment by Chocolee-sir** [comment]
你生活在奴隶时代应该是条会感恩的狗奴

**Comment by mela93** [comment]
你生活在奴隶时代应该是条会感恩的狗奴

**Comment by nibihzoay** [comment]
提出这问题想必技术也高不到哪里去，使劲喷，发泄出来，生活找不到存在感，网络能赋予你们

**Comment by zzwphp** [comment]
先不说工资是不是和付出正比，那你怎么消费水平不是和一线城市一样？怎么房租不是一样啊？楼市怎么不是一样啊

**Comment by Pulini** [comment]
哪天等你进ICU的时候，请你记得回来告诉我们，我们去看望你

**Comment by mela93** [comment]
那你觉得996就应该是常态是吗？加班不用给加班费？
在你眼中正常的作息时间是什么？正常的作息时间下的工资标准是什么？
凭什么996就应该是常态？就应该不给加班费？
就像之前网上一句话“你把华为当归属，华为把你当什么？” 同理这里华为可以换成任何公司。
不好意思我对你没有归属感，我对钱有归属感。

**Comment by nibihzoay** [comment]
不想996离职呀，去不996的地方有的是，谁逼迫你们了，建议把不满在现实中表现出来，不要成为现实的狗奴，把你们这种能力转化为喷叫你们加班的人，给你们没完没了改需求的人更好。

**Comment by Pulini** [comment]
996不是错， 错在我或主动或被动的参与进了996后却没有得到相应的回报。且因法律法规的不完全，使人无处说法。有多少人因为996被坑害而无法脱坑。大家只是为受害的人抱不平，而你却居高自傲的抨击受害的人是自讨苦吃。一个有责任的人，哪那么容易说离职就离职。财政中断妻儿老小谁来养？去喷同事喷领导？那跟疯狗有什么区别，你身边的同事一点不满就破口大骂，你会怎么看待他？讲真你要是不改标题，你迟早要被人喷成筛子。

**Comment by nibihzoay** [comment]
@Pulini 承认现实 面对现实，薪水是生活质量的保证，有些人想通过努力或者加班达到你们北上广的薪水还达到不了呢，钱多活少离家近谁都想拥有，可是中国有几个王思聪呢，试问，哪个工作不是用生命换钱，如果有我想投简历。

**Comment by iTofu** [comment]
hey，不用什么生命换，给你钱，让你吃屎，你吃吗？
应该是 true，报个价吧，我去众筹一下~
