### ISSUE TITLE
你代码写的像caixukun 

### ISSUE THREAD

**Issue by morning7** [996icu/996.ICU#3353]
面宽长碗大圆

**Comment by LiYeLin** [comment]
ikun nm$l

**Comment by stubhbw** [comment]
蔡徐坤
《童话二分之一》中饰演少年御风。此剧未播先火。也带动了蔡徐坤在娱乐圈的发展。热播电影《完美假妻168》饰演男主角霍克的少年时期。湖南卫视另一部电视连续剧《女刑警李春春》饰演西西一角。并在由好莱坞导演拍摄的耐克广告全球滑板篇与世界顶级滑板明星John Rodeny Mullen对戏。参与曹正叔叔的小主播大梦想小主持人专栏节目荣获小主持人。童一首歌青唱片少儿歌曲大赛获全国十强。国家大剧院作为鞠萍姐姐唯一搭档主持“红领巾之歌”青少年活动。

**Comment by bearcheng** [comment]
你可以侮辱我，不能侮辱我的代码

**Comment by wyw8152** [comment]
你可以侮辱caixukun，但不能侮辱我和我的代码
