### ISSUE TITLE
有多少人是为了提升自己的技术水平才愿意 996的，结果一直在搬砖。

### ISSUE THREAD

**Issue by aliliin** [996icu/996.ICU#3379]
有多少人是为了提升自己的技术水平才愿意 996的，可是进入公司才发现，一直在搬砖。一直996，自学的时间都没有了

**Comment by ztzhangtao** [comment]
996才能提升技术是个伪命题

**Comment by aliliin** [comment]
> 996才能提升技术是个伪命题

是啊。进去之后才知道这是个坑。
