### ISSUE TITLE
求内推产品岗，小姐姐喔...Base北京，点击有惊喜

### ISSUE THREAD

**Issue by vvkee** [996icu/996.ICU#340]
### 有内推HC的麻烦留下 公司 + 邮箱。

本人**坚决抵制996**
另外：
_外企招**初中高级前端**，上班时间965有机会出差美国，简历甩给我
薪资构成 base + 14薪 + 总部期权。
薪资范围是18K-45K区间，能力强的可谈（貌似是这样）
点我头像看联系方式_

**Comment by Dante-dan** [comment]
你是真的秀啊
