### ISSUE TITLE
ThoughtWorks招聘，外企（武汉，北京，成都），965，每天下午6点下班

### ISSUE THREAD

**Issue by rsun-thoughtworks** [996icu/996.ICU#3526]
欢迎简历砸过来。

大武汉

DEV - 后端开发工程师（Java为主，C++等愿意转技术栈的同等考虑）
DEV - 前端开发工程师
BA - 商业需求分析师
PM - 项目经理
QA - 测试开发工程师（英文口语流畅）

**Comment by githubyunplayer** [comment]
我咋不信了  是被坑怕了吗

**Comment by yugai** [comment]
大专有面试机会吗？

**Comment by rsun-thoughtworks** [comment]
> 大专有面试机会吗？

不看学历，看能力

**Comment by zhao9052** [comment]
都什么岗位呀

**Comment by yugai** [comment]
> > 大专有面试机会吗？
> 
> 不看学历，看能力

求个联系方式。

**Comment by rsun-thoughtworks** [comment]
> > > 大专有面试机会吗？
> > 
> > 
> > 不看学历，看能力
> 
> 求个联系方式。

rsun@thoughtworks.com

**Comment by rsun-thoughtworks** [comment]
> 都什么岗位呀

看我更新的

**Comment by linchen2chris** [comment]
成都的可以投到这里来 clin@thoughtworks.com

**Comment by murkHunter** [comment]
前端面试还给套题做， 做个响应式页面， 浪费时间

**Comment by rsun-thoughtworks** [comment]
> 前端面试还给套题做， 做个响应式页面， 浪费时间

通过代码可以更加全面了解一个工程师的技术能力，代码习惯。
