### ISSUE TITLE
现实生活中大多数人都不会反抗。。

### ISSUE THREAD

**Issue by bkunzhang** [996icu/996.ICU#359]
虽然不想，但还是跟着大家一起了

**Comment by bkunzhang** [comment]
之前在一家30个人的公司，就是下班大家都不走，很少有人敢带头

**Comment by YuHang0121151624** [comment]
枪打出头鸟，谁也不愿意冒险

**Comment by 596073656** [comment]
9x5,表示我是出头鸟，头就是铁

**Comment by mela93** [comment]
965 我表示我就是第一个下班的。大家虽然不是准时吧，基本10分钟内走完。。。

**Comment by netsman1030** [comment]
劳动仲裁吧，时间够你换单位了
跟老板怼吧，影响背景调查


离职估计是最常见的反抗了
