### ISSUE TITLE
#杭州 #e签宝 #招聘前端 #招聘后端 #招聘UI(交互方面) #欢迎砸简历 没有996: )

### ISSUE THREAD

**Issue by Tang1118** [996icu/996.ICU#3601]
![image](https://user-images.githubusercontent.com/20086376/55126014-b0f64180-5146-11e9-9d3c-e1b8d219ca60.png)

内推请发简历至：hanjiang@tsign.cn

**Comment by BrightWade** [comment]
招Android吗
