### ISSUE TITLE
说实话我觉得这里留言的好多都是傻屌

### ISSUE THREAD

**Issue by huangxiaochun** [996icu/996.ICU#3833]
没有行动力，只敢在线上吐槽，然后老老实实996，恭喜你，你老板并不会责怪你，因为你有了宣泄的地方，就不会在公司发牢骚了，工作还是得老老实实完成。
还有那些宣群的，你真的以为大多数程序员能上qq？上微信？码代码的人有这人权？如果有这时间，还不如好好码你的代码，早点把事情做完下班回家

**Comment by 1064112734** [comment]
有种加班叫强制加班

**Comment by qiliangya** [comment]
表示上午吹吹水, 下午写点业务+看看新技术+不加班 小日子很舒坦

**Comment by sgr914** [comment]
做完事要能下班，就不会996了
