### ISSUE TITLE
96杭州 有房有车 不要new的对象 有缘跟帖聊

### ISSUE THREAD

**Issue by huhao666** [996icu/996.ICU#3929]
96杭州 有房有车 不要new的对象 有缘跟帖

**Comment by swjjxyxty** [comment]
一起还贷款吗

**Comment by zhanchengqian** [comment]
@996icu Please delete unrelated issue like this one

**Comment by ooshell** [comment]
你是找男友吗

**Comment by SageLu** [comment]
![333333](https://user-images.githubusercontent.com/17927694/55127329-be152f80-514a-11e9-9069-3e523d44be23.jpg)

**Comment by SageLu** [comment]
@huhao666 @swjjxyxty @zhanchengqian @ooshell @peppy 
杭州的戳过来
