### ISSUE TITLE
病历单晒一下，希望大家都身体健康

### ISSUE THREAD

**Issue by KatyChenLu** [996icu/996.ICU#3935]
![711553741970_ pic](https://user-images.githubusercontent.com/15972824/55126656-958c3600-5148-11e9-9b5d-a142a96339a0.jpg)
![701553741969_ pic](https://user-images.githubusercontent.com/15972824/55126663-991fbd00-5148-11e9-9f05-9f8c75791081.jpg)
![691553741953_ pic](https://user-images.githubusercontent.com/15972824/55126669-9e7d0780-5148-11e9-99bf-8d0b6e3c8d03.jpg)
去年确诊，吃药一年。

**Comment by lovin67** [comment]
女

**Comment by jerry4718** [comment]
辛苦了

**Comment by lzg999** [comment]
chenlu

**Comment by lzg999** [comment]
陈璐

**Comment by 7hmA3s** [comment]
### 同志们加班辛苦了，上帝会来拯救你们的！

**Comment by cjr0707** [comment]
姐姐暴露 姓名 性别了

**Comment by janus25** [comment]
小姐姐 辛苦了

**Comment by KatyChenLu** [comment]
> 姐姐暴露 姓名 性别了

没关系，没人认识我😁

**Comment by littlewhiteee** [comment]
小姐姐辛苦了

**Comment by zhaomeiru66** [comment]
@KatyChenLu 现在治愈了吗？
