### ISSUE TITLE
招聘.招聘啦.. Thoughtworks. 不要 996

### ISSUE THREAD

**Issue by pengcao1** [996icu/996.ICU#3952]
欢迎简历砸过来。

大武汉

DEV - 后端开发工程师（Java为主，C++等愿意转技术栈的同等考虑）
DEV - 前端开发工程师
BA - 商业需求分析师
PM - 项目经理
QA - 测试开发工程师（英文口语流畅）

pcao@thoughtworks.com

**Comment by pengcao1** [comment]
不要 996

**Comment by beautive** [comment]
要什么？
