### ISSUE TITLE
合法游行讨论群：654019730

### ISSUE THREAD

**Issue by CaoBaoWang** [996icu/996.ICU#3953]
5.1 号 上午10点 北京最高人民法院 东南一门 门口
喊口号：
依法治国，严格执行劳动法
劳动光荣，拒绝违法996
拍视频，解说，自媒体发酵 众筹资金买热搜。

　    起来！不愿做奴隶的人们！
　　把我们的血肉筑成我们新的长城！
　　中华民族到了最危险的时候，
　　每个人被迫着发出最后的吼声。
　　起来！起来！起来！
　　我们万众一心，
　　冒着敌人的炮火，前进！
　　冒着敌人的炮火，前进！
　　前进！前进、进！

我们是法治国家，所有的口号和游行都需要合法
有志同道合的小伙伴可以加入 qq群：654019730 讨论如何合法为自己发声 合法组织游行
没有星星之火，何以谈燎原

**Comment by rorschach214** [comment]
加油

**Comment by AnCorleone** [comment]
游行是要政府同意的

**Comment by XMISSM** [comment]
日子选的不错，手续肯定有困难

**Comment by rorschach214** [comment]
> 游行是要政府同意的

去派出所报备，但是一般不会批的，尤其北京。

**Comment by CaoBaoWang** [comment]
报备不批，是不会去游行的，也就在网上发发
