### ISSUE TITLE
【拒绝❌996】不加班的陌陌诚邀你加入

### ISSUE THREAD

**Issue by LRL-A** [996icu/996.ICU#3975]
陌陌
公司员工为1600人左右哦。总公司位于北京，在上海、成都、天津、广州等地设有分公司。
 
薪酬福利
陌陌薪资结构：
12M（底薪）+1M（年底双薪）+3~4M（季度奖金）

往年经验看，100%的人可以拿到16M；
2018年营收好，100%的人拿到了18M。

陌陌公司介绍
上市公司，整个公司有1500人，技术团队约400人。陌陌是人均产值最高的互联网公司，800W/人（2017年数据）。
业务线：社交，直播，短视频，游戏，创新项目等
用户和盈利数据：MAU 1.08亿，季度盈利3亿美金左右
文化和氛围：文化氛围轻松，福利好，工程师都很nice。

工作强度
10:00-8:00，双休

公司介绍
MOMO是陌陌（NASDAQ：MOMO）推出的一款基于地理位置的开放式移动视频社交应用，是中国领先的泛社交泛娱乐平台之一。
陌陌公司于2011年成立，2014年12月11日在美国纳斯达克交易所挂牌上市（股票交易代码：MOMO）。陌陌的愿景是希望人们通过移动互联网，发现身边的美好与新奇，让人们连接原本该连接的人。
网址
https://www.immomo.com/
地址
望京SOHO
亮点优势
陌陌目前月活达1.08亿

招聘职位：

推荐算法工程师、高级iOS开发工程师：、Java开发工程师、AI平台开发工程师、流媒体服务开发工程师等职位

👏欢迎自荐推荐，加微信13501125963详聊

**Comment by jdpxiaoming** [comment]
兄弟，机智啊

**Comment by generalbao** [comment]
我php的呢

**Comment by ineyko** [comment]
nice！！

**Comment by LRL-A** [comment]
> 我的PHP的呢

欢迎微信私聊

**Comment by jienice** [comment]
优秀

**Comment by specialLL** [comment]
工作强度
10:00-8:00，双休
我数学不好。。。。

**Comment by LRL-A** [comment]
> 优秀

欢迎加入无压迫公司

**Comment by 66coder66** [comment]
ni……c……e……

**Comment by LRL-A** [comment]
> 工作强度
> 10：00-8：00，双休
> 我数学不好....

工作日早10点到晚8点，有双休

**Comment by wlf1112** [comment]
有前端职位吗

**Comment by Clovertjp** [comment]
陌陌游戏部了解一下，10 11 6

**Comment by LRL-A** [comment]
> 陌陌游戏部了解一下，10 11 6

欢迎微信私聊

**Comment by LRL-A** [comment]
> 有前端职位吗

其他不加班的互联网公司有，欢迎微信私聊

**Comment by Mirsla** [comment]
兄弟牛逼呀

**Comment by lzx2005** [comment]
6666666666666666

**Comment by Powerfulxxr** [comment]
😄

**Comment by sinx-wang** [comment]
校招实习有吗
