### ISSUE TITLE
你来啊，我就是给我的Github打个广告

### ISSUE THREAD

**Issue by RuffianZhong** [996icu/996.ICU#3983]
Android UI 快速开发，专治原生控件各种不服
[RWidgetHelper](https://github.com/RuffianZhong/RWidgetHelper)
RxJava2+Retrofit2+RxLifecycle2+OkHttp3 封装RHttp  使用MVP模式构建项目
[Rx-Mvp](https://github.com/RuffianZhong/Rx-Mvp)

**Comment by swjjxyxty** [comment]
你只是个小安卓，安心996吧
