### ISSUE TITLE
996的元凶基本上都是产品经理 万恶之源

### ISSUE THREAD

**Issue by nibihzoay** [996icu/996.ICU#436]

**Comment by tombeer2011** [comment]
老板是万恶之源吧

**Comment by youruomeizhou** [comment]
The unreasonable demands of product managers result in a lot of complicated work for programmers.

**Comment by zcx666** [comment]
老板是吧！产品经理是背锅侠，再有就是公司的制度没有给底层员工发声的权利，建议保障底层员工的权利，让工会有足够的权力，让老板（管理层），底层员工，工会，三个利益平衡，工会由员工决定，工会制衡管理层，管理层制衡员工，互相制衡，达到利益最大化

**Comment by nibihzoay** [comment]
@zcx666 董事长该有你的位置！
