### ISSUE TITLE
现在我宣布，此吧已被C#占领! C#是世界上最优雅的语言，没有之一！

### ISSUE THREAD

**Issue by Sopcce** [996icu/996.ICU#4508]
好了  看看就好了

**Comment by ChiuMungZitAlexander** [comment]
naive

**Comment by ChinaPicture** [comment]
最优雅的语言不是文言文么？

**Comment by Sopcce** [comment]
> 最优雅的语言不是文言文么？

Microsoft  牛逼 没办法

**Comment by pandyer** [comment]
.NET微信群
![wz](https://user-images.githubusercontent.com/12846899/55131242-bbb9d200-5158-11e9-8dae-634c559e7eac.jpg)
