### ISSUE TITLE
讨论好热闹啊，你们都是在哪看到的

### ISSUE THREAD

**Issue by bkunzhang** [996icu/996.ICU#457]
![image](https://user-images.githubusercontent.com/19164121/55060869-6674b680-50ad-11e9-9fab-93df4bc6de01.png)

跟着vczh逛github？
<https://github.com/trending> trending竟然没有

**Comment by xwcsgo** [comment]
githunt

**Comment by bkunzhang** [comment]
https://github.com/trending

trending竟然没有

**Comment by ted1ore1ee** [comment]
微博

**Comment by Aiiroo** [comment]
学（jiao习（ji）交流群里

**Comment by gaoqiang19514** [comment]
[每日时报](https://wubaiqing.github.io/zaobao/)

**Comment by xwcsgo** [comment]
> https://github.com/trending
> 
> trending竟然没有

估计是看star涨的太快了

**Comment by gaoqiang19514** [comment]
可能被算法排除了（有可能会有机器分析项目内容）

**Comment by gaoqiang19514** [comment]
上了，第一位，哈哈哈

**Comment by xwcsgo** [comment]
是吗

**Comment by gaoqiang19514** [comment]
![Snipaste_2019-03-27_16-37-00](https://user-images.githubusercontent.com/13738577/55061373-95d7f300-50ae-11e9-953a-ac2d3f50d0a5.png)

**Comment by netsman1030** [comment]
网易新闻。。。（捂脸）

**Comment by xwcsgo** [comment]
https://github.com/trending
这里还没有上榜

**Comment by youanming** [comment]
建议里面放一些代码伪装下

**Comment by bkunzhang** [comment]
可能有延迟
> 这里有<https://github.com/explore>

**Comment by xwcsgo** [comment]
估计在知乎这些地方又有一大群人来批判这个项目了

**Comment by bkunzhang** [comment]
> [每日时报](https://wubaiqing.github.io/zaobao/)

这个好厉害，长见识了

**Comment by gaoqiang19514** [comment]
> > [每日时报](https://wubaiqing.github.io/zaobao/)
> 
> 这个好厉害，长见识了

[D2 日报](https://daily.fairyever.com/article/chrome-extension.html)
