### ISSUE TITLE
移民新西兰，脱离996，加微信群

### ISSUE THREAD

**Issue by rickysunx** [996icu/996.ICU#4600]
![WechatIMG97](https://user-images.githubusercontent.com/19698070/55127739-072ea900-5176-11e9-9999-e231a7190ef0.jpeg)

**Comment by ariesZhou** [comment]
![image](https://user-images.githubusercontent.com/46946479/55127563-8c509880-514b-11e9-9db9-1c177210d0dd.png)

**Comment by liyong98847** [comment]
我以为群里会有很多人呢。。。
