### ISSUE TITLE
给个star吧，实习生刚毕业就失业： https://github.com/longer96/CDTU

### ISSUE THREAD

**Issue by longer96** [996icu/996.ICU#4622]
**大哥大姐新年好，给个star吧，给个star吧！实习生刚毕业就失业：**
https://github.com/longer96/CDTU

给大家发红包了
跪谢！！

**Comment by longer96** [comment]
感谢大家！！！

**Comment by neroneroffy** [comment]
不错不错，已经star了

**Comment by longer96** [comment]
> 不错不错，已经star了

谢谢！！！
好人一生平安！！
