### ISSUE TITLE
~~~~~~~~~~~~~~ 程序员小哥内推，不加班 ~~~~~~~~~~~~~~

### ISSUE THREAD

**Issue by CocoaDebug** [996icu/996.ICU#477]
声明，我也是一个程序员，帮忙内推一下而已~ 有兴趣请加我 V 13674831243，备注：内推。
要求不低，老板定的，不要打我~ （ 二本以上+大厂经验加持）

想当初我也是内推进来的哈哈哈~ 坐标深圳，N多技术岗位

我把能想到的公司福利都写在这里：
(简历务必真实，所有面试流程通过后，公司会委托第三方机构进行背景调查)

- 15 薪资，社保公积金全额，免费水果零食，10 点上班，7 点下班，很少加班，人手一台 MacBook-pro （ 16G 内存）
- 上班不打卡，地点深圳科技园（深大地铁站附近）
- 深圳研发规模千人以上，在扩招中
- 薪资普遍高于其他公司，一半以上员工来自 BAT
- 新加坡上市互联网公司，有机会出差新加坡等东南亚国家，主要业务在东南亚地区
- 试用期三个月，试用期工资和转正工资都是一样多
- 年假 15 天，双休
- 每个月月底发当月工资
- 7 点以后提供免费晚餐

**Comment by JasonSpeak** [comment]
地点，岗位？

**Comment by CocoaDebug** [comment]
声明，我也是一个程序员，帮忙内推一下而已~ 有兴趣请加我 V 13674831243，备注：内推。
要求不低，老板定的，不要打我~ （ 二本以上+大厂经验加持）

想当初我也是内推进来的哈哈哈~

我把能想到的公司福利都写在这里：
(简历务必真实，所有面试流程通过后，公司会委托第三方机构进行背景调查)

- 15 薪资，社保公积金全额，免费水果零食，10 点上班，7 点下班，很少加班，人手一台 MacBook-pro （ 16G 内存）
- 上班不打卡，科技园深大地铁站附近
- 深圳研发规模千人以上，在扩招中
- 薪资普遍高于其他公司，一半以上员工来自 BAT
- 新加坡上市互联网公司，有机会出差新加坡等东南亚国家，主要业务在东南亚地区
- 试用期三个月，试用期工资和转正工资都是一样多
- 年假 15 天，双休
- 每个月月底发当月工资
- 7 点以后提供免费晚餐

**Comment by JasonSpeak** [comment]
应届生哭了

**Comment by CocoaDebug** [comment]
也一直在校招呢，985学校优先~

**Comment by GzhiYi** [comment]
十点后提供坐车报销吗😄

**Comment by CocoaDebug** [comment]
从来没待到过10点，这个真不知道

**Comment by abigOrange** [comment]
这波招聘广告6666~

**Comment by HZWCynic** [comment]
1111111111

**Comment by casxter** [comment]
6

**Comment by lala9662** [comment]
年假15天，双休，看哭了，你们公司也太好了吧。

**Comment by Han3Jim** [comment]
年假15天，当月底发工资，nb，上海有分部吗？QaQ

**Comment by 3epochs** [comment]
有机器学习岗吗？

**Comment by LinboLuo** [comment]
学历必须二本以上吗

**Comment by LinboLuo** [comment]
学历必须二本以上吗
