### ISSUE TITLE
【成都】求坑  https://github.com/longer96/CDTU

### ISSUE THREAD

**Issue by longer96** [996icu/996.ICU#5116]
**大佬写求个star**
https://github.com/longer96/CDTU

谢谢！！！
跪谢！！！

**Comment by longer96** [comment]
**大佬写求个star**
https://github.com/longer96/CDTU



谢谢！！！
跪谢！！！

**Comment by longer96** [comment]
**大佬写求个star**
https://github.com/longer96/CDTU

再扣头！！！

**Comment by fengyaogit123** [comment]
互相star 来呀

**Comment by fengyaogit123** [comment]
![image](https://user-images.githubusercontent.com/23473070/55128705-8492f300-514f-11e9-805c-3f05d732150b.png)


> **大佬写求个star**
> https://github.com/longer96/CDTU
> 
> 再扣头！！！

https://github.com/fengyaogit123/bookqd

**Comment by longer96** [comment]
> ![image](https://user-images.githubusercontent.com/23473070/55128705-8492f300-514f-11e9-805c-3f05d732150b.png)
> 
> > **大佬写求个star**
> > https://github.com/longer96/CDTU
> > 再扣头！！！
> 
> https://github.com/fengyaogit123/bookqd

已点  谢谢！！
