### ISSUE TITLE
上海靠谱公司招聘了，QTM的996

### ISSUE THREAD

**Issue by 526353781** [996icu/996.ICU#523]
地点：上海张江高科
薪资范围： 18- 23K
工作时间：9:30 - 6:30 双休
岗位空缺：PHP 2人

岗位职责：
1、开发网站新功能、新模块；
2、负责项目产品各个功能的完善与维护，新功能代码编写及测试；
3、对现有项目进行性能分析、效率优化
4、参与需求分析、系统设计以及核心代码的编写和架构设计；
5、根据不同的业务需求，灵活快速地完成具有挑战性的项目
6、协助项目经理完成部分管理工作

岗位要求：
1、从事PHP编程工作3年以上，有大型网站开发经验、大数据操作经验者优先；
2、深入理解oop思想，熟悉常见设计模式，熟悉常用框架thinkphp或CI或YII其中一种；
3、优秀的数据库设计和优化能力，精通Mysql数据库应用；
4、熟悉Redis,MongoDB,Memcache等NoSQL；
5、熟悉Linux，了解服务器性能优化、负载均衡、IO模型等知识；
6、有优秀的逻辑分析能力，能够对业务逻辑进行合理的抽象和拆分；
7、积极主动，有较强的责任心和团队合作意识；

加分技能：
1、喜欢捣腾前沿技术，善于学习，经常阅读书籍；
2、在可扩展、高性能，高并发，高稳定性系统设计，开发和调优方面有实际经验；
3、有网页前端加载优化经验、心得；
4、有使用sphinx、elasticsearch等全文搜索引擎经验；
5、注重用户体验，善于沟通协作，有管理技术团队（或小组）经验； 

我们需要这样全能的phper，不希望每个人固定在某个角色。我们愿意给到你空间成长，也希望你有足够的自驱力，一个和谐向上的team等你加入~

欢迎简历来砸：57305595@qq.com

**Comment by illionhh** [comment]
见缝插针

**Comment by baiyichu** [comment]
棒！
