### ISSUE TITLE
微信公众号【java后端技术精选】专注Java技术干货：JVM、Spring、Spring Boot、Cloud、IDEA、Dubbo、Redis、git、微服务、MySQL、集群、分布式、中间件、消息队列、Linux、网络、多线程、公众号开发、小程序开发、面试题等。回复1024获得200g视频教程

### ISSUE THREAD

**Issue by Mshangx** [996icu/996.ICU#5368]
微信公众号【java后端技术精选】专注Java技术干货：JVM、Spring、Spring Boot、Cloud、IDEA、Dubbo、Redis、git、微服务、MySQL、集群、分布式、中间件、消息队列、Linux、网络、多线程、公众号开发、小程序开发、面试题等。回复1024获得200g视频教程

**Comment by RenHaoQAQ** [comment]
打你吗的广告,狗东西

**Comment by Mshangx** [comment]
操尼玛的我就打了你来咬我呀，智障东西，

**Comment by Mshangx** [comment]
> 打你吗的广告,狗东西

你有病吗，废物。
