### ISSUE TITLE
[求置顶]强烈要求开放清理整理issue区权限，限制创建issue的权限

### ISSUE THREAD

**Issue by leo-mao** [996icu/996.ICU#5638]
目前issue区出现大量噪音,淹没了有价值的信息，我归类如下：
- 创建组织，求加入组织的（qq群微信群等等），完全可以**归为一个issue**, 求创建人考虑
- 广告，各类小广告，**删无论**
- 嘲讽、闲聊等没有帮助的 issue， **删无论**
- 个人表态立志吐槽的, **归为一个issue**
- 其他

**Comment by leo-mao** [comment]
@996icu

**Comment by lei-jinlei** [comment]
@996icu

**Comment by 996icu** [comment]
Welcome abroad.

**Comment by leo-mao** [comment]
> Welcome abroad.

and Bye?

**Comment by leo-mao** [comment]
> Welcome abroad.

So why do you kick us out of the board? @996icu
