### ISSUE TITLE
杭州IT者联盟（1群） >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>跳槽季踩坑交流 - 微信群

### ISSUE THREAD

**Issue by lamplife** [996icu/996.ICU#5885]
![WechatIMG3599](https://user-images.githubusercontent.com/12744359/55130689-b8bde200-5156-11e9-862c-5b3b3afeddd7.jpeg)

**Comment by misakuo** [comment]
My dear dalao, please daidaiwo

**Comment by liwandaniel** [comment]
My dear dalao, please daidaiwo
