### ISSUE TITLE
【找女朋友】 算打广告吗

### ISSUE THREAD

**Issue by xixily** [996icu/996.ICU#6053]

**Comment by westgoto** [comment]
996的同志，你们辛苦了，小弟特别来点福利，2050tv.com福利影视，自己躲厕所偷偷看吧，
这才是打广告，你的不算

**Comment by stevenwsg** [comment]
666

**Comment by westgoto** [comment]
别只喊6666

**Comment by wondertwo** [comment]
666666

**Comment by ZhuXiuyu** [comment]
没图你说个xx

**Comment by xixily** [comment]
https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1553760097053&di=2befdeaccd45252ebe2f1cca2fc75ec8&imgtype=0&src=http%3A%2F%2Fphotocdn.sohu.com%2F20130221%2FImg366616739.jpg

**Comment by xixily** [comment]
丑的人先发

**Comment by xixily** [comment]
[Image](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1553760097053&di=2befdeaccd45252ebe2f1cca2fc75ec8&imgtype=0&src=http%3A%2F%2Fphotocdn.sohu.com%2F20130221%2FImg366616739.jpg)

**Comment by westgoto** [comment]
> [Image](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1553760097053&di=2befdeaccd45252ebe2f1cca2fc75ec8&imgtype=0&src=http%3A%2F%2Fphotocdn.sohu.com%2F20130221%2FImg366616739.jpg)

666
