### ISSUE TITLE
我希望进996公司

### ISSUE THREAD

**Issue by codesboy** [996icu/996.ICU#6175]
对于一个半路出家的野生程序猿，能进996模式的大科技公司上班也是一种渴望，因为技术有限只能待在一些医疗之类的非IT行业的公司，根本学不到任何东西，所以能在966模式下学习锻炼也是一种幸福，凡事有坏的一面，也会有好的一面，请珍惜。

**Comment by Harman-Wayne** [comment]
在医疗公司积累一些医疗知识,然后再进996公司方便以后进了ICU自救, 有点道理.

**Comment by zacharyzhao** [comment]
你应该直接去看脑科。
