### ISSUE TITLE
相亲贴

### ISSUE THREAD

**Issue by hongxb** [996icu/996.ICU#638]
趁着日将增加的人气，不如此贴大家自己相个亲？

**Comment by tyyzj124** [comment]
要先说好，你是男的还是女的

**Comment by duancoder** [comment]
居然不留个微信号

**Comment by ilaotan** [comment]
gg or mm?

**Comment by hustonchung** [comment]
嗯嗯，18:00 - 21:00 就别工作了，相亲吧

**Comment by RottenWang** [comment]
0 ? 1 ?

**Comment by duancoder** [comment]
前排留名啊 但是吧 这个相亲贴 估计都是相亲女程序吧   。。。。  不然谁上来看这个啊

**Comment by HalfDeadneko** [comment]
我们自动化测试的单身女孩子还是挺多的
∠( ᐛ 」∠)＿

**Comment by hongxb** [comment]
@HalfDeadneko 媒婆业务搞起来

**Comment by duancoder** [comment]
> 我们自动化测试的单身女孩子还是挺多的
> ∠( ᐛ 」∠)＿

在北京么 哈哈哈 媒婆业务搞起来 本人游戏服务器后端

**Comment by DeMeng33** [comment]
在同性交友网站相亲？  你是认真的？   233333

**Comment by penghongru** [comment]
没什么好说的,只有一句66666666666送给你

**Comment by wenying2196** [comment]
坐等资源

**Comment by CHENPINGCAI** [comment]
同城交友

**Comment by hongxb** [comment]
@CHENPINGCAI 
骚年，请留下联系方式

**Comment by lpflpy** [comment]
base 北京  有相亲群吗？
