### ISSUE TITLE
参与开发几万人的项目######欢迎加入前端开发联盟-微信群######

### ISSUE THREAD

**Issue by sufaith** [996icu/996.ICU#6385]
![image](https://user-images.githubusercontent.com/10233977/55131903-7b0f8800-515b-11e9-9805-900efd3ab5fc.png)

**Comment by liangzai92** [comment]
欢迎给个star [https://github.com/liangzai92/blog](https://github.com/liangzai92/blog)
![](http://qiniu.adebibi.com/qrcode-web.jpg)
