### ISSUE TITLE
建议搞个可自由提交和投票的 996 公司名单（附原型）

### ISSUE THREAD

**Issue by jason5ng32** [996icu/996.ICU#642]
没想到这个项目居然有这么多 star ，给各位动手能力强的同学一个建议，搞个网站，让用户可以自由、匿名提交公司的 996 情况，其他人可以进行投票确认。

比如首页：

![首页](https://knb.im/images/996_1.png)

比如公司页面：

![公司](https://knb.im/images/996_2.png)

比如提交页面：

![提交](https://knb.im/images/996_3.png)

作为一个表达声音的项目，不需要过多考虑提交和投票者是否真的在对应的公司，更多的是让更多人能参与表达，发出对这种犹如「高三每个中学都补课，我们不补课就落后了」的扭曲价值观的不认同。

**更新：已经准备开发 ing**

**Comment by gexiaoyun** [comment]
产品经历提需求了。

**Comment by tyyzj124** [comment]
最好手机原型也来一份

**Comment by xlover135** [comment]
开发大大们，接接接，接单啦

**Comment by obrua** [comment]
6666666666666666

**Comment by guomaoqiu** [comment]
six six six

**Comment by jason5ng32** [comment]
考虑到传播，可以做成小程序。

**Comment by bkunzhang** [comment]
顶

**Comment by pizhihui** [comment]
产业链啊

**Comment by vertea** [comment]
顶了，我接了：）

**Comment by vindia9** [comment]
这个需求提的好

**Comment by tyyzj124** [comment]
可以搞搞，反正我还有个空闲的服务器

**Comment by xwcsgo** [comment]
要不搞成小程序

**Comment by bkunzhang** [comment]
> 顶了，我接了：）

我参与

**Comment by ishen7** [comment]
> > 顶了，我接了：）
> 
> 我参与

跟帖，走起

**Comment by AndrewZhengXiao** [comment]
顶一下

**Comment by SongJXin** [comment]
我可以参与一下吗emmm

**Comment by yseric** [comment]
> 666

**Comment by hustonchung** [comment]
建议APP起名“卖卖”

**Comment by jason5ng32** [comment]
我本想找个开源的框架来弄，可是代码能力有限，仅能小打小闹，交给各位大佬了。

**Comment by tyyzj124** [comment]
为啥叫卖卖，叫996不好么

**Comment by Leroy920815** [comment]
叫卖命吧

**Comment by wyxiloveu** [comment]
这个需求不错

**Comment by xinyu2880** [comment]
牛逼  这个项目我接

**Comment by pengcao1** [comment]
666

**Comment by Cody1988** [comment]
名字就叫剥削社会主义程序员的黑心企业家

**Comment by EdisonZhe** [comment]
要不要再把企业再像企业信息查询软件那样对应起来，一点开就能看到企业有没有坑爹记录。。。

**Comment by Driver-C** [comment]
如果访问量大需要运维的话可以找我

**Comment by 19951206chao** [comment]
6666

**Comment by QiangShang** [comment]
工作严重不饱和啊，你不996 谁不996  【滑稽】

**Comment by reinit** [comment]
> 让用户可以自由、匿名提交公司的 996 情况，其他人可以进行投票确认

一个问题是，如何保证信息的准确性。如果提交者和投票者都是匿名的话。

**Comment by zhangjiafan8652** [comment]
坐等微信群，急需一名ceo 创建团队鸭

**Comment by manchiang** [comment]
> > 让用户可以自由、匿名提交公司的 996 情况，其他人可以进行投票确认
> 
> 一个问题是，如何保证信息的准确性。如果提交者和投票者都是匿名的话。

是的,如何避免恶意刷?

**Comment by tyyzj124** [comment]
微信授权，一个微信号在30天内只能投一票，越近期投票权重越大

**Comment by tyyzj124** [comment]
微信授权，一个微信号在30天内只能投一票，越近期投票权重越大

**Comment by vertea** [comment]
> > > 让用户可以自由、匿名提交公司的996 情况，其他人可以进行投票确认
> > 
> > 
> > 一个问题是，如何保证信息的准确性。如果提交者和投票者都是匿名的话。
> 
> 是的,如何避免恶意刷?

经典的验证码（很多第三方公司包括谷歌也有提供此类验证码）
或者是要求用户提供邮箱，定期对数据飙升异常的公司进行限制
微信授权是一种，但是微信授权局限较大

**Comment by ztzhangtao** [comment]
菇凉们  出来接客啦

**Comment by harvey-woo** [comment]
可以搞，小程序，算我一个

**Comment by Comedian1926** [comment]
老哥稳得一批

**Comment by l-qiang** [comment]
做大 做强

**Comment by zsirfs** [comment]
web 都可以拉群拉仓库

**Comment by sunshine2995** [comment]
🐂嗷

**Comment by tyyzj124** [comment]
小程序可以，算我一个

**Comment by zhangjiafan8652** [comment]
恶性刷其实无所谓啊，只要有人提交，存在恶心加班是铁定的。没有谁闲着没事去恶心提交公司的吧。是不是996，让他们hr来邮件投诉就知道了啊。。。

**Comment by manchiang** [comment]
可以拉微信群了

**Comment by QiangShang** [comment]
阿禅图画的好快呀，转型了吗这是？！

**Comment by mela93** [comment]
> > > 让用户可以自由、匿名提交公司的 996 情况，其他人可以进行投票确认
> > 
> > 
> > 一个问题是，如何保证信息的准确性。如果提交者和投票者都是匿名的话。
> 
> 是的,如何避免恶意刷?

> > > > 让用户可以自由、匿名提交公司的996 情况，其他人可以进行投票确认
> > > 
> > > 
> > > 一个问题是，如何保证信息的准确性。如果提交者和投票者都是匿名的话。
> > 
> > 
> > 是的,如何避免恶意刷?
> 
> 经典的验证码（很多第三方公司包括谷歌也有提供此类验证码）
> 或者是要求用户提供邮箱，定期对数据飙升异常的公司进行限制
> 微信授权是一种，但是微信授权局限较大

我想到的差不多，对数据飙升异常IP段进行限制，那个时间段的数据可以视为无效数据

**Comment by reinit** [comment]
> > > 让用户可以自由、匿名提交公司的 996 情况，其他人可以进行投票确认
> > 
> > 
> > 一个问题是，如何保证信息的准确性。如果提交者和投票者都是匿名的话。
> 
> 是的,如何避免恶意刷?

我觉得应该先想好如何解决身份验证的问题，然后才是设计产品。因为这类网站如果内容有差错，会有法律风险。

我在想是否能在提交公司的时候需要附带一张公司内部办公室的照片，拍摄的位置必须使用门卡才能进入。但是这样可能会涉嫌违反公司内部规章并且违法。

邮件验证后戳不知道是不是保险。

**Comment by reinit** [comment]
> > > > 让用户可以自由、匿名提交公司的 996 情况，其他人可以进行投票确认
> > > 
> > > 
> > > 一个问题是，如何保证信息的准确性。如果提交者和投票者都是匿名的话。
> > 
> > 
> > 是的,如何避免恶意刷?
> 
> 我觉得应该先想好如何解决身份验证的问题，然后才是设计产品。因为这类网站如果内容有差错，会有法律风险。
> 
> 我在想是否能在提交公司的时候需要附带一张公司内部办公室的照片，拍摄的位置必须使用门卡才能进入。但是这样可能会涉嫌违反公司内部规章并且违法。
> 
> 邮件验证后戳不知道是不是保险。

总之必须找到一个办法，在保护提交人隐私的同时，验证其身份。

**Comment by Star-Fall** [comment]
啥也别说了 干吧

**Comment by harvey-woo** [comment]
弄小程序吧，web不行了

**Comment by coderhaiyang** [comment]
**666 点你点个赞.**

**Comment by jason5ng32** [comment]
我和一个朋友注册了一个域名： 996.company ，打算贡献出来。

有兴趣参与开发的同学欢迎加到这个群里，一起讨论产品细节，如何保证真实性、如何确保不会被查到等等。然后再建个仓库一起玩。

![qr](https://knb.im/images/qr.png)

P.S. 以上行为与我所在公司无关……

**Comment by slx618** [comment]
666

**Comment by tyyzj124** [comment]
先提供个qq群：229497714
后期再弄微信群吧

**Comment by biekanwonicheng** [comment]
### 名字就叫996吧

**Comment by julian102** [comment]
666666

**Comment by jason5ng32** [comment]
> > > > 让用户可以自由、匿名提交公司的 996 情况，其他人可以进行投票确认
> > > 
> > > 
> > > 一个问题是，如何保证信息的准确性。如果提交者和投票者都是匿名的话。
> > 
> > 
> > 是的,如何避免恶意刷?
> 
> 我觉得应该先想好如何解决身份验证的问题，然后才是设计产品。因为这类网站如果内容有差错，会有法律风险。
> 
> 我在想是否能在提交公司的时候需要附带一张公司内部办公室的照片，拍摄的位置必须使用门卡才能进入。但是这样可能会涉嫌违反公司内部规章并且违法。
> 
> 邮件验证后戳不知道是不是保险。

这是个问题，不过我觉得能想到折衷的办法。

**Comment by zsirfs** [comment]
![image](https://user-images.githubusercontent.com/22249411/55066302-7940b880-50b8-11e9-8c85-d31eb2a4c919.png)
钉钉群

**Comment by LyricTian** [comment]
我这边可以提供基于golang的开发框架，快速实现数据录入：

**Comment by reinit** [comment]
如果要建立网站的话，注意下列要点：

1. 网站前端设计必须对搜索引擎友好，当用户搜索公司名的时候，可以看到搜索结果；
2. 第一条很重要，鼓掌。

**Comment by Zziv** [comment]
最好搞个app，至少起码是小程序

**Comment by zacharyzhao** [comment]
可以调天眼查的 API ，关联老板，像老赖名册一样。

**Comment by KitGavinx** [comment]
这个需求很简单，怎么实现我不管

**Comment by RicoLiu** [comment]
good idea

**Comment by manchiang** [comment]
搞起来可以给招聘网站提供数据了....牛逼

**Comment by hongfei2017** [comment]
996加班高出了，希望原型早日落地成型

**Comment by AssKicker0214** [comment]
发表对公司的评论时，只有别人**认同**你的意见之后才标记为有效。这样是不是能减少恶意行为

**Comment by reinit** [comment]
> 搞起来可以给招聘网站提供数据了....牛逼

开玩笑，现在招聘网站在合伙跟雇佣公司一起隐藏负面消息。

**Comment by zsirfs** [comment]
静等大佬们实现

**Comment by reinit** [comment]
> 发表对公司的评论时，只有别人**认同**你的意见之后才标记为有效。这样是不是能减少恶意行为

不建议，echo chamber了解一下。

**Comment by manchiang** [comment]
> > 搞起来可以给招聘网站提供数据了....牛逼
> 
> 开玩笑，现在招聘网站在合伙跟雇佣公司一起隐藏负面消息。

- -。那可以继续搞个招聘网站

**Comment by responsebody** [comment]
厉害...

**Comment by Yangk030208** [comment]
厉害了。。。

**Comment by WeitongHuang** [comment]
厉害了。。。

**Comment by WeitongHuang** [comment]
你怎么穿着品如的衣服？

**Comment by xinyun512** [comment]
产品原型已经出来了,接下来就看猿类了。。。

**Comment by ZerglingX6** [comment]
行动派，支持

**Comment by abc1763613206** [comment]
支持啊

**Comment by Ning0000** [comment]
> 
> 
> 最好搞个app，至少起码是小程序
> 直接查询公司，然后显示该公司的上下班时间
> 因为不仅有996 还有997 007 这些

007是什么？？

**Comment by ZerglingX6** [comment]
可以先定位成一个服务速查工具性质

**Comment by linuxwind** [comment]
支持。牛逼。

**Comment by xwcsgo** [comment]
> > 最好搞个app，至少起码是小程序
> > 直接查询公司，然后显示该公司的上下班时间
> > 因为不仅有996 还有997 007 这些
> 
> 007是什么？？
0点上班0点下班一周7天

**Comment by Ning0000** [comment]
> 
> 
> > > 最好搞个app，至少起码是小程序
> > > 直接查询公司，然后显示该公司的上下班时间
> > > 因为不仅有996 还有997 007 这些
> > 
> > 
> > 007是什么？？
> > 0点上班0点下班一周7天

有这么狂野的公司存在吗?  真是长见识了）））

**Comment by wenyejie** [comment]
> 如果要建立网站的话，注意下列要点：
> 
> 1. 网站前端设计必须对搜索引擎友好，当用户搜索公司名的时候，可以看到搜索结果；
> 2. 第一条很重要，鼓掌。

非常支持. 哈哈!

**Comment by SiMaLaoShi** [comment]
upup

**Comment by boolak** [comment]
这个产品一定能火

**Comment by suixinger** [comment]
支持，这个产品应该彻底改变这个IT环境

**Comment by xwcsgo** [comment]
还是太难了

**Comment by heyaotang** [comment]
顶起来，原本以为只是吐个槽

**Comment by AomoriL** [comment]
参与参与 :)

**Comment by hongfei2017** [comment]
希望能保护用户隐私，不要被进入人事的 黑名单

________________________________
hf.rong@outlook.com

发件人： heyaotang<mailto:notifications@github.com>
发送时间： 2019-03-27 18:09
收件人： 996icu/996.ICU<mailto:996.ICU@noreply.github.com>
抄送： 飞仔<mailto:hf.rong@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题： Re: [996icu/996.ICU] 建议搞个可自由提交和投票的 996 公司名单（附原型） (#642)

顶起来，原本以为只是吐个槽

**Comment by lambal** [comment]
很想参与项目

**Comment by wenyejie** [comment]
这个项目我接了!

**Comment by hongfei2017** [comment]
我很担心，github扛不住啊，大家手下留情。有需要，这里提供劳动力一枚。

**Comment by fishmankkk** [comment]
@jason5ng32 加不了了 可以拉一下吗

**Comment by Tianyazz** [comment]
坐等设计稿

**Comment by sky121520** [comment]
微信群超限了   大佬拉一把啊

**Comment by zx0721** [comment]
哈哈哈, 反了, 反了

**Comment by GrumpyCat0413** [comment]
牛逼 加油 小程序比较方便点

**Comment by kajweb** [comment]
我这边准备开发一个去参赛……有没有大佬拉我进群

**Comment by lnowave** [comment]
> 坐等设计稿

正想着要不要随意甩个设计稿出来~虽然我没有这怨念，我司6点就下班啊哈哈

**Comment by gaoqiang19514** [comment]
行动派，服气

**Comment by baiyun1102** [comment]
顶起来  可以参与开发

**Comment by ligl0702** [comment]
支持。抵制不良风气。让那些大厂好好反思反思。让他们招聘率 也下去了。别盲目跳槽。全是坑。

**Comment by liqingzhu96** [comment]
支持

**Comment by bkunzhang** [comment]
> 我这边准备开发一个去参赛……有没有大佬拉我进群

拉我一个

**Comment by fishmankkk** [comment]
直接建个2群，然后再拉大佬当群主不就好了嘛，估计1群也爆了

**Comment by 378804441** [comment]
有个入门级阿里云服务器 闲置，如有所需愿意献一份力

**Comment by polarisNoSnow** [comment]
> 直接建个2群，然后再拉大佬当群主不就好了嘛，估计1群也爆了

同建议

**Comment by kajweb** [comment]
> 直接建个2群，然后再拉大佬当群主不就好了嘛，估计1群也爆了

![](https://i.loli.net/2019/03/27/5c9b548f052f6.png)

**Comment by xiaoluome** [comment]
https://join.slack.com/t/996icuworkspace/shared_invite/enQtNTg5NjIxNjg4MzI0LTIxN2Q1NTBmM2YzZGFjNzMxMTRkYjFhYzFlMzE1YmM0OGM0NjdiN2Y0MWNmMTUxYjhiOGIzYTg2NDNkZGRlOTk

我觉得可以用slack，这样大家都能参与进来查看，微信群和QQ群毕竟有限，过往的记录就看不了了

**Comment by Cxd2014** [comment]
墙裂建议！！

**Comment by iceytea** [comment]
求拉微信群

感觉可以用小程序搞，省台服务器

**Comment by kajweb** [comment]
那样那个主体公司就不给你过审了

**Comment by Siomt** [comment]
投票之后具体干什么？

**Comment by jason5ng32** [comment]
更新：已经准备开发 ing

**Comment by RenZSHUN** [comment]
支持一下，以后简历上可以写参加过大型项目了吗？？手动🌺🐔

**Comment by louyu65** [comment]
支持，我实名举报过杭州有赞，特别反感这种变态的行为

**Comment by kajweb** [comment]
> 更新：已经准备开发 ing

有空联系一下，我这里还有一个40人左右的群等待入官方群。

**Comment by abc1763613206** [comment]
> 支持一下，以后简历上可以写参加过大型项目了吗？？手动🌺🐔

star破万项目（预计）

**Comment by jason5ng32** [comment]
> > 更新：已经准备开发 ing
> 
> 有空联系一下，我这里还有一个40人左右的群等待入官方群。

我微信 ID 和我 github ID 一致，可以加我你来拉

**Comment by johnlin0207** [comment]
提架构，我可以参与开发。🙃

**Comment by timmygod** [comment]
从来不参与开源项目的我 准备参与一波

**Comment by xuxuzhaozhao** [comment]
微信群满了呀！！成都的扎起！！！！

**Comment by huangmb** [comment]
愿意为安卓版尽点力

**Comment by atuxe** [comment]
感觉天眼查之类的最适合加这功能

**Comment by swuecho** [comment]
https://cloudqa.iego.cn/sr/icu996

<img width="514" alt="Screen Shot 2019-03-28 at 12 43 36 AM" src="https://user-images.githubusercontent.com/666683/55095190-ab6f0c00-50f2-11e9-8da8-a3b0c7aa5996.png">

**Comment by swuecho** [comment]
如果有人提交数据我每天定时导出JSON或者CSV格式文件或者提供rest api。

**Comment by LyerProgrammer** [comment]
大佬们，群里面给个板凳的位置啊。 @jason5ng32

**Comment by chai-chai** [comment]
666

**Comment by DB-BOY** [comment]
赶紧的吧，我的IDE已经打开了，这可能是我参与的第一个开源项目

**Comment by DB-BOY** [comment]
> 感觉天眼查之类的最适合加这功能

很有可能就是天眼查的新功能，问下内部立项了吗？

**Comment by mzc532** [comment]
牛逼

**Comment by ChongqingWangYu** [comment]
有趣😏

**Comment by xtb666** [comment]
吃瓜群众

**Comment by JslinSir** [comment]
RN  版 找队友

**Comment by swuecho** [comment]
目前 结果 JSON  

http://122.112.218.148:15666/v_answer

可以用来分析了。小伙伴们浪起来！

**Comment by sailuya** [comment]
如果是用Java开发，我也可以一起参与

**Comment by xiaogehenjimo** [comment]
大佬们我愿意尽一份绵薄之力,如果开发iOS客户端我可以参与!!!

**Comment by ilaotan** [comment]
upup

**Comment by IMVector** [comment]
终于有实干的大佬了

**Comment by zhangshiqin** [comment]
缺人喊我
技能点：产品设计、数据分析

**Comment by lishangsheng92** [comment]
我的妈呀prd都出来了啊，我可以参与写代码吗

**Comment by haobinaa** [comment]
我可以contribute

**Comment by SHERlocked93** [comment]
我想参与这个项目，开项目大家一起提pr吧

**Comment by ACERY1** [comment]
搞小程序吧  很方便

**Comment by JohnsonSmile** [comment]
我也想参与，要不要搞个996的区块链😆

**Comment by NaJiPeng** [comment]
是不是还要植入广告啊？😂😂😂

**Comment by y1814419111** [comment]
我也想参与！加我加我~

**Comment by Brandon-li** [comment]
APP 放着我来开发~

**Comment by G-dc** [comment]
牛逼  加我一个呗

**Comment by KGSpring** [comment]
给秀儿赐座

**Comment by 1923982924** [comment]
6666

**Comment by willianfu** [comment]
大佬，求拉入群！

**Comment by codingwa** [comment]
牛逼啊 大佬 整个微信群吧

**Comment by okobboko** [comment]
提供.NET JAVA 小程序版本支持

**Comment by licongyu95** [comment]
搞个996加班打卡功能更好。。。。按公司维度，加班打卡。

**Comment by Corvey** [comment]
怎么保证做大做强以后不会出现公关给钱删名单，是不是得搞一手去中心化？

**Comment by RyanIPO** [comment]
为什么不做一个白名单呢？！🐣

**Comment by coller2003** [comment]
网站后端我可以，前端可以使用现成的框架

**Comment by jasonwang1991** [comment]
哎。。。不让加班的公司  让我好痛苦

**Comment by aweeesome** [comment]
建议：需要用GitHub账号authenticate。此产品的最高priority应该是防刷结果。UI/UX是次要的priority…

**Comment by westgoto** [comment]
666.

**Comment by stevenkang** [comment]
做一个小程序吧，大家都能看利于传播

**Comment by SiberiaWolfP** [comment]
这个好这个好，支持

**Comment by kingofwhales** [comment]
哈哈哈哈  看了楼主头像那么熟悉 原来是follow的公众号之一  加油！

**Comment by gyp03** [comment]
几个页面就搞定了，抓紧搞吧   1、先把数据采集上来；2、展现出来   先让大家用起来

**Comment by huangyuanlove** [comment]
Android端我来

**Comment by fotock** [comment]
https://github.com/fotock/996Board
提交企业，举手制止

**Comment by Yangyi0011** [comment]
群满了啊，怎么进去

**Comment by Sopage** [comment]
搞小程序腾讯有权利封杀！搞h5就可以了…

**Comment by wuzaofeng** [comment]
@jason5ng32 麻烦啦我进群

**Comment by JiangtianPan** [comment]
空谈误国，实干兴邦，大佬牛皮

**Comment by SloanSJ** [comment]
顶一个

**Comment by laizhihuan** [comment]
空谈误国，实干兴邦，大佬牛皮

**Comment by RoganZheng** [comment]
空谈误国，实干兴邦，大佬牛皮

**Comment by Feahter** [comment]
为什么不贴项目地址跟讨论组地址呢？
产品们可以开始整理需求 脑图、优化原型
设计们可以出稿 （蓝湖、zplin）
前端们可以搭脚手架
后端们可以写接口
运维们可以配置服务器
测试们可以先观望
技术们可以跟着初稿做数据结构设计沟通 贴各自的技术栈跟架构规划
大家伙项目管理工具用起来了（tower、Teambition）
ps.最好是开发前后分离 restful接口 swagger文档 数据库RDS  前台 后台 服务器 数据库 拉多个项目负责 各自主控一个项目然后github开源 供同行coder协作开发 前台要考虑多端 后台要考虑并发 服务器要考虑墙外

**Comment by OverrideSkywalker** [comment]
虽然我是965，但是还是莫名来围观（不要打死我- -）

**Comment by codingwa** [comment]
擦 这个这么牛逼的⭕️

**Comment by OverrideSkywalker** [comment]
既然匿名如何防止有人恶意刷榜？

**Comment by jason5ng32** [comment]
> 为什么不贴项目地址跟讨论组地址呢？
> 产品们可以开始整理需求 脑图、优化原型
> 设计们可以出稿 （蓝湖、zplin）
> 前端们可以搭脚手架
> 后端们可以写接口
> 运维们可以配置服务器
> 测试们可以先观望
> 技术们可以跟着初稿做数据结构设计沟通 贴各自的技术栈跟架构规划
> 大家伙项目管理工具用起来了（tower、Teambition）
> ps.最好是开发前后分离 restful接口 swagger文档 数据库RDS 前台 后台 服务器 数据库 拉多个项目负责 各自主控一个项目然后github开源 供同行coder协作开发 前台要考虑多端 后台要考虑并发 服务器要考虑墙外

目前在初始化阶段，考虑到参与者的隐私，项目先 private 了，上线了再看看怎样保护参与者。

**Comment by magicLaLa** [comment]
这个需求完全ok

**Comment by muse90673** [comment]
> 怎么保证做大做强以后不会出现公关给钱删名单，是不是得搞一手去中心化？

如果有人恶意提交996公司呢？比如一些企业给竞争对手不停提交996，去中心化虽然能解决恶意删名单的问题，但是解决不了恶意提交的问题。

**Comment by Feahter** [comment]
> > 为什么不贴项目地址跟讨论组地址呢？
> > 产品们可以开始整理需求 脑图、优化原型
> > 设计们可以出稿 （蓝湖、zplin）
> > 前端们可以搭脚手架
> > 后端们可以写接口
> > 运维们可以配置服务器
> > 测试们可以先观望
> > 技术们可以跟着初稿做数据结构设计沟通 贴各自的技术栈跟架构规划
> > 大家伙项目管理工具用起来了（tower、Teambition）
> > ps.最好是开发前后分离 restful接口 swagger文档 数据库RDS 前台 后台 服务器 数据库 拉多个项目负责 各自主控一个项目然后github开源 供同行coder协作开发 前台要考虑多端 后台要考虑并发 服务器要考虑墙外
> 
> 目前在初始化阶段，考虑到参与者的隐私，项目先 private 了，上线了再看看怎样保护参与者。

可以先把大家按职能分流到一些自己擅长领域的协作工具上去，也方便你们主力开发项目的人采纳建议，优化调整之类的 让大家这些自来水流动起来，愿意动手贡献的人 肯定不会瞎说 大家也是守法爱国的人 只是发起一些开源协作项目 发起人把控好代码内容 不触碰法律 不干扰社会工作秩序 不用担心保护的问题 只要后面上线考虑访问被被不被墙就行 coder是讲效率的群体 我看好几个群都堆满人在观望了

**Comment by qq22424** [comment]
有咩有群，ionic前端跨平台开发，web iOS android  webApp 小程序，一套代码搞定

**Comment by dy-GitHub** [comment]
h5开发前来报名，是否能尽一点绵薄之力

**Comment by KennethChiuT** [comment]
我想参与哈哈哈哈哈

**Comment by Inahara-Shen** [comment]
php开发前来报名

**Comment by WWWangkx** [comment]
有没有群噻 ，让我这种java小弟也来参与一下

**Comment by yalunwang** [comment]
请问什么时候开发好，需要帮忙参与吗

**Comment by sunxiaoda** [comment]
ios开发前来报名

**Comment by ANGULAR-X** [comment]
要做angular和vue兼职的没，来QQ群：467557563

**Comment by Inahara-Shen** [comment]
> 996.company

微信求拉，群进不去了

**Comment by jsonpeter** [comment]
API接口地址 http://122.112.218.148:15666/v_answer

**Comment by AresHappy** [comment]
这个可以。帮助了不少的同僚少走弯路。被鸡汤灌得五迷三道的。最后熬坏了身体。

**Comment by AresHappy** [comment]
建议接入芝麻信用。以免有的人进来乱攻击其他公司。

**Comment by dzding** [comment]
做成APP或小程序或H5需要访问位置信息，早上9点之前公司位置打卡，晚上9点之后同位置打卡；打卡位置在某公司附近1KM内且早晚都打卡就获得一次为该公司的投票的权力。这样可以大大避免刷票和保证投票的真实性

**Comment by willowHai** [comment]
可以跟996.icu所有者联系一下

**Comment by XieB** [comment]
逻辑一定要严谨性

**Comment by Enigma-Guo** [comment]
作为一个app开发，很想参与，但估计明儿一早项目就上线了，我就等着好消息了

**Comment by jony4** [comment]
支持一个

**Comment by allposs** [comment]
支持一个

**Comment by XieB** [comment]
想想严谨的逻辑，让人无从下手

**Comment by bellingxu** [comment]
ui前来报名

**Comment by liampayne94** [comment]
求拉进群

**Comment by stevenkang** [comment]
> 这个需求完全ok

下班之前要

**Comment by kongshanxuelin** [comment]
开源的微信小程序问卷调查，微信扫一扫即可填写：

![微信小程序问卷调查](https://camo.githubusercontent.com/a82a477e86605875ac2eccd4d483930e3eb256c2/687474703a2f2f68352e73756d736c61636b2e636f6d2f313231322e6a7067)

**Comment by dianshendianshen** [comment]
坐等后端大佬出接口

**Comment by swuecho** [comment]
[投票](https://cloudqa.iego.cn/sr/icu996)

[添加](https://cloudqa.iego.cn/sr/icu996)


<img width="514" alt="Screen Shot 2019-03-28 at 12 43 36 AM" src="https://user-images.githubusercontent.com/666683/55138002-60dea580-516d-11e9-9b67-4d92ba72903c.png">

[公司名单](http://blog.meihao.us/icu996_poll_result/)

<img width="798" alt="Screen Shot 2019-03-28 at 4 55 01 PM" src="https://user-images.githubusercontent.com/666683/55143726-4a8b1680-517a-11e9-9264-191c902497df.png">


[JSON数据](http://122.112.218.148:15666/v_answer)

可以用来做二次开发

**Comment by zhaotai** [comment]
> [投票](https://cloudqa.iego.cn/sr/icu996)
> 
> [添加](https://cloudqa.iego.cn/sr/icu996)
> 
> <img alt="Screen Shot 2019-03-28 at 12 43 36 AM" width="514" src="https://user-images.githubusercontent.com/666683/55138002-60dea580-516d-11e9-9b67-4d92ba72903c.png">
> 
> [公司名单](http://blog.meihao.us/icu996_poll_result/)
> 
> <img alt="Screen Shot 2019-03-28 at 4 55 01 PM" width="798" src="https://user-images.githubusercontent.com/666683/55143726-4a8b1680-517a-11e9-9264-191c902497df.png">
> 
> [JSON数据](http://122.112.218.148:15666/v_answer)
> 
> 可以用来做二次开发

哥们，你提pull request啊

**Comment by swuecho** [comment]
昨天提交了 被close了

**Comment by swuecho** [comment]
@jason5ng32 你们搞的如何了？

**Comment by lizhaojie001** [comment]
给个json数据接口啊

**Comment by swuecho** [comment]
@lizhaojie001  http://122.112.218.148:15666/v_answer  get all result

**Comment by reinit** [comment]
@jason5ng32 我想到一个办法来提高信息的准确性，就是在提交这些信息的同时，需要附带提供一张向当地劳动稽查部门进行举报后得到的回执。

**Comment by karepbq** [comment]
来 iOS 报道了，我时间自由 可以搞个iOS 客户端哟。

**Comment by lxyzai** [comment]
有成果了吗

**Comment by swuecho** [comment]
[投票](https://cloudqa.iego.cn/sr/icu996)

[添加](https://cloudqa.iego.cn/sr/icu996)


<img width="419" alt="Screen Shot 2019-03-29 at 10 45 05 AM" src="https://user-images.githubusercontent.com/666683/55205939-c5ead780-520f-11e9-9f58-769caaf36bb4.png">

[公司名单](http://blog.meihao.us/icu996_poll_result/)

Qx 中的x 对应于上图中的题目，行中数字是选项。

<img width="798" alt="Screen Shot 2019-03-28 at 4 55 01 PM" src="https://user-images.githubusercontent.com/666683/55143726-4a8b1680-517a-11e9-9264-191c902497df.png">

[参与开发](https://github.com/swuecho/icu996_poll_result)

可以基于调查结果做可视化，分析等


[JSON数据](http://122.112.218.148:15666/v_answer)

可以用来做二次开发，比如 @zlx362211854 开发的[ICU charts](https://github.com/zlx362211854/ICU-charts)

**Comment by jason5ng32** [comment]
赞楼上手速

**Comment by swuecho** [comment]
> 赞楼上手速

idea 归你所有，你是个好PM。不要难为程序员。
