### ISSUE TITLE
王侯将相宁有种乎

### ISSUE THREAD

**Issue by JiangtianPan** [996icu/996.ICU#6660]
起初，纳粹抓了共产党人的时候，
我沉默了；
因为我不是共产党人。

当他们关了犹太人的时候，
我沉默了；
因为我不是犹太人。

当他们抓工会成员的时候，
我没有抗议；
因为我不是工会成员。

当他们抓天主教徒的时候，
我沉默了；
因为我不是天主教徒。

最后当他们奔向我而来，
再也没有人站起来为我说话了。

**Comment by zlzong** [comment]
我是996，我痛恨996，但是我不敢辞职，我怕找不到工作
