### ISSUE TITLE
是否可以做一个子页面，收集一下过劳死的程序员名单

### ISSUE THREAD

**Issue by KarsusNeko** [996icu/996.ICU#6701]
名单上可以简要描述一下大致事情，如果有新闻或者微博源链接最好

**Comment by ziran258** [comment]
过劳死是一件很难界定的事情，轻易列出很容易落人口实

**Comment by KarsusNeko** [comment]
> 
> 
> 过劳死是一件很难界定的事情，轻易列出很容易落人口实

那我觉得可以改一个称呼，在工作岗位上去世的
