### ISSUE TITLE
996员工私人生活是啥样的？

### ISSUE THREAD

**Issue by Star-Fall** [996icu/996.ICU#685]
有对象吗？
会被分手吗？
有家人吗？
家人还认识不？
。。。

能活多久？

**Comment by Leroy920815** [comment]
私人生活是什么

**Comment by zhaohl1993** [comment]
眼睛一闭一睁就在公司，周末一觉就到中午了。但是朋友聚会大多在周六。

**Comment by xwcsgo** [comment]
我现在发烧39度左右还在上班你说呢

**Comment by zhaohl1993** [comment]
> 我现在发烧39度左右还在上班你说呢

我前段时间肺炎要住院，结果连续一个多星期扛着发烧去上班

**Comment by andyluna** [comment]
本人编出的程序永不过切，从未撞刀，不走空刀，一个人能同时操作6台电脑编10台机床的程序。
会修机，调机，分模，拆电极，报价，搬运，扫铁屑，擦机床，可以不休息，不迟到，不早退，晚上可以加班到凌晨3点，任何品牌和任何系统机器都会，能同时操作8台龙门铣和10台加工中心不停机，手法犀利，走位风骚，意识超前，体力恐怖，上机下模绝不间断。
操作加工中心能在3分钟内对完24把刀，操作龙门铣放活能摆在0.05毫米以内，几乎不用拉直。
任何图纸都能在1分钟内看懂并列出加工方案和算出加工时间及评估成本消耗。
可以接受任何一款方言指挥,怕语言不通可直接接受哑语手势指挥，接到指令后0.1秒内付诸行动。
**身强体壮能连续工作两天两夜不休息，12小时不喝水，24小时不吃饭、堪称操机中的战斗机。
全职业认识深刻，熟练操机大师战斗理论。
深山苦练30年，一天只睡4小时，脾气好不操人，操作虎，
意识强，下刀准,移动快，会套路，听指挥，操机如杀鸡。
曾经单人连续上料八十块打表分中不休息，
八点上班从不迟到，半分钟搞定上机，数控专业操机，泡面矿泉水已是主粮。
父母不支持操机已断绝关系，女朋友不支编程机已分手，望知心老板收留。**

**Comment by manchiang** [comment]
> 我现在发烧39度左右还在上班你说呢

太猛了...

**Comment by nilly** [comment]
no life  no sexy 

only  keyboad !!

**Comment by andyluna** [comment]
本人学识渊博、经验丰富，代码风骚、效率恐怖，c/c++、java、php无不精通，熟练掌握各种框架，深山苦练20余年，一天只睡4小时，千里之外定位问题，瞬息之间修复上线。身体强壮、健步如飞，可连续编程100小时不休息，讨论技术方案5小时不喝水，上至带项目、出方案，下至盗账号、威胁pm，啥都能干。泡面矿泉水已备好，学校不支持编程已辍学，家人不支持编程已断绝关系，老婆不支持编程已离婚，小孩不支持编程已送孤儿院，备用电源万兆光纤永不断电断网，门口已埋雷无人打扰。

**Comment by qintian95** [comment]
> 本人编出的程序永不过切，从未撞刀，不走空刀，一个人能同时操作6台电脑编10台机床的程序。
> 会修机，调机，分模，拆电极，报价，搬运，扫铁屑，擦机床，可以不休息，不迟到，不早退，晚上可以加班到凌晨3点，任何品牌和任何系统机器都会，能同时操作8台龙门铣和10台加工中心不停机，手法犀利，走位风骚，意识超前，体力恐怖，上机下模绝不间断。
> 操作加工中心能在3分钟内对完24把刀，操作龙门铣放活能摆在0.05毫米以内，几乎不用拉直。
> 任何图纸都能在1分钟内看懂并列出加工方案和算出加工时间及评估成本消耗。
> 可以接受任何一款方言指挥,怕语言不通可直接接受哑语手势指挥，接到指令后0.1秒内付诸行动。
> **身强体壮能连续工作两天两夜不休息，12小时不喝水，24小时不吃饭、堪称操机中的战斗机。 全职业认识深刻，熟练操机大师战斗理论。 深山苦练30年，一天只睡4小时，脾气好不操人，操作虎， 意识强，下刀准,移动快，会套路，听指挥，操机如杀鸡。 曾经单人连续上料八十块打表分中不休息， 八点上班从不迟到，半分钟搞定上机，数控专业操机，泡面矿泉水已是主粮。 父母不支持操机已断绝关系，女朋友不支编程机已分手，望知心老板收留。**

我不信不给面试机会了

**Comment by xwcsgo** [comment]
> > 我现在发烧39度左右还在上班你说呢
> 
> 我前段时间肺炎要住院，结果连续一个多星期扛着发烧去上班

我是今天早上突然就感冒了然后强打着精神去上班的，现在整个人看四周都有点晕乎乎的感觉了
