### ISSUE TITLE
珠海996.ICU

### ISSUE THREAD

**Issue by eric4048** [996icu/996.ICU#6926]
![image](https://user-images.githubusercontent.com/7628273/55133213-d774a680-515f-11e9-8263-1b01ef312745.png)
![image](https://user-images.githubusercontent.com/7628273/55133275-199de800-5160-11e9-8c2a-e09f90f2fa4f.png)

**Comment by EzioJacken** [comment]
珠海市杰理科技股份有限公司啊，刚开始，计划奋斗一百天呢
