### ISSUE TITLE
统计一下上下班的路程花费时间吧

### ISSUE THREAD

**Issue by shanelau** [996icu/996.ICU#711]
早上堵车 50分钟，晚上不堵车 40分钟，最快 30分钟

**Comment by ahkjxy** [comment]
来回120公里

**Comment by xxllp** [comment]
2-3小时

**Comment by Kennytian** [comment]
上班：
>要看出发时小区楼下的共享单车有没有被其它人骑走，如果全没有，那就是完蛋，要走15分钟到地铁站。然后出地铁，要看地铁门口的单车还有没有剩下几辆，如果也没有，又得走好一会儿，最后妥妥的1.5小时。

下班：
> 反向同理可推

**Comment by wsz122567642** [comment]
高峰逆向通勤，穿梭五环内外，上班打车出城20min，下班公交进城40min。

**Comment by wuzhjian** [comment]
六点四十出门，八点四十到，妥妥的两个小时
