### ISSUE TITLE
搞死那个发广告办卡的服务器 

### ISSUE THREAD

**Issue by JohnHuahuaZhan** [996icu/996.ICU#7820]
搞死那个发广告办卡的服务器准备压一波

**Comment by riskgod** [comment]
那我也来个 压测走一波

**Comment by Hatcat123** [comment]
![](https://raw.githubusercontent.com/Hatcat123/GraphicBed/master/Img/20190328144304.jpg)

**Comment by rsun-thoughtworks** [comment]
这个服务器已经打不开了。
