### ISSUE TITLE
无聊看看网  ： 我是好人，只是求star https://github.com/tangjinjinwx/Public.WeChat.CRM.SDK

### ISSUE THREAD

**Issue by tangjinjinwx** [996icu/996.ICU#7968]
无聊看看网  ： 我是好人，只是求star https://github.com/tangjinjinwx/Public.WeChat.CRM.SDK

**Comment by litblank** [comment]
虽然你这项目不错，也能发这么多次吧，已star，这是我的 https://github.com/litblank/hammer

**Comment by tangjinjinwx** [comment]
已star
