### ISSUE TITLE
欢迎扫码加入Android ICU 大家庭 三群

### ISSUE THREAD

**Issue by cuidaye** [996icu/996.ICU#7978]
欢迎大家加入 Android  ICU 病房

想进Android ICU 大群的加我好友 拉你入群

**Comment by lenvon2012** [comment]
![avatar](https://raw.githubusercontent.com/lenvon2012/trace-demo/master/20190328112642.jpg)

欢迎添加微信，输入：  拉我进996群  

欢迎大家加入 交流、吐槽
