### ISSUE TITLE
996工作制度这个没法管理的

### ISSUE THREAD

**Issue by univeryinli** [996icu/996.ICU#8155]
很多公司都是打着为了劳动者的旗号，而且在天朝的这个法律环境下不好管理，天朝法律写得都太过于笼统，比如说，需要工会参与，在众多互联网公司，工会就是一个形同虚设的存在，反正工会的领导都不用加班，跟他们的关系确实不大。

**Comment by MeteoriteMan** [comment]
主要天朝法律故意写的这样.就比如累计工作时间(年假)吧.正常理解是每家公司的时间都能累加进去.然而就只有深圳劳动局写到了官网上(北京的HR直接告诉你,你在北京工作,按照北京的来.PS:北京的也没说非要是同一家公司呆的时间加起来才算累计工作时间啊).反正各种恶心了.劳动法感觉就是专门为难打工的
