### ISSUE TITLE
都是996，普遍的就是对的吗

### ISSUE THREAD

**Issue by cuifan1995** [996icu/996.ICU#82]

**Comment by cenkai88** [comment]
啥叫对？

**Comment by cuifan1995** [comment]
> 啥叫对？

曾听到过一句话 如果工作影响生活，你就换个工作，我们是为了生活才工作的
生活和工作能平衡平衡，起码不能牺牲身体健康吧

**Comment by smoothwind** [comment]
懒得怼

**Comment by cenkai88** [comment]
@cuifan1995 但也有人是为了生存才工作。我是10 5.5 5，但我也不支持996变成常态，但是这个现象之所以存在原因非常复杂。如果完全禁止996中国现在这些996的小公司恐怕都活不下去。。一批码农要下岗

你直接说对还是不对太浅了。。

**Comment by cuifan1995** [comment]
@cenkai88  是我想的少了
