### ISSUE TITLE
【上海内推】965 在招人，Java、C# 、高级DBA、系统测试、系统运维等等，考虑的来撩，

### ISSUE THREAD

**Issue by zmh7057** [996icu/996.ICU#8279]
Java、C# 、高级DBA、系统测试、系统运维等等

地点：上海，宝山，7号线上大路地铁站出来就是

公司：[票易通](https://www.zhipin.com/gongsir/fe3d250b05c715cd1XJ809m5.html?ka=company-jobs)

直接内推，欢迎各位来撩 或者直接邮件简历

邮箱: menghan.zhu@outlook.com
微信：menghan7057

**Comment by zmh7057** [comment]
灌水太狠了吧

**Comment by lovemybabyxuan** [comment]
宝山还是有点远啊~~~
