### ISSUE TITLE
北京程序员工会群

### ISSUE THREAD

**Issue by chenlian2015** [996icu/996.ICU#8310]
![xx](https://user-images.githubusercontent.com/9668538/55135150-c4fd6b80-5165-11e9-8594-640cfd5f65df.jpg)

**Comment by lenvon2012** [comment]
![avatar](https://raw.githubusercontent.com/lenvon2012/trace-demo/master/20190328112642.jpg)

欢迎添加微信，输入、发送：  拉我进996群  

欢迎大家加入 交流、吐槽
