### ISSUE TITLE
杭州IT者联盟（1群） 微信群 ################### 见证历史性一刻！！杭州打卡，拒绝996

### ISSUE THREAD

**Issue by lamplife** [996icu/996.ICU#8360]
![WechatIMG3599](https://user-images.githubusercontent.com/12744359/55135235-0c83f780-5166-11e9-80ff-c0b3a83c78dc.jpeg)

**Comment by lenvon2012** [comment]
![avatar](https://raw.githubusercontent.com/lenvon2012/trace-demo/master/20190328112642.jpg)

欢迎添加微信，输入、发送：  拉我进996群  

欢迎大家加入 交流、吐槽
