### ISSUE TITLE
学过hello world并失败的非程序员前来支持，并求一枚程序员小哥哥做男朋友~~~~~~~~~~

### ISSUE THREAD

**Issue by Doris66666** [996icu/996.ICU#839]

**Comment by xbchome** [comment]
信你个鬼

**Comment by coolpo** [comment]
插个眼，滔天怨愤中一股清流。目测能火

**Comment by littlemo** [comment]
震惊！github竟然真的可以用来相亲！

**Comment by mzxdream** [comment]
现在猎头的套路真多

**Comment by guomaoqiu** [comment]
信你个鬼，你这个糟老头子~

**Comment by ZhenningLang** [comment]
大...大diao萌妹？

**Comment by wenyejie** [comment]
不, 我要coding, 没时间恋爱

**Comment by coolpo** [comment]
> 震惊！github竟然真的可以用来相亲！

同性交友网站，开玩笑呢！？同性才是真爱！

**Comment by a906551354** [comment]
吊吊吊

**Comment by lx815** [comment]
66666

**Comment by kxjqj** [comment]
信你个鬼

**Comment by Doris66666** [comment]
> 信你个鬼

实话告诉你我是币圈的、币圈更惨无人道啊啊啊啊

**Comment by a7505553** [comment]
我要继续写BUG，女朋友是什么鬼

**Comment by ArtSword** [comment]
说吧,啥要求,要几年工作经验?

**Comment by xxh332211** [comment]
一看就是hr

**Comment by Doris66666** [comment]
> 现在猎头的套路真多

竟然没人信我、我擦、看来上天真的要让我孤独一生

**Comment by zhouscd** [comment]
信你个鬼，你这个糟老头子~ 坏的很！

**Comment by yuqiao11278** [comment]
信你个鬼

**Comment by zakuAndStars** [comment]
mark, 等待后续

**Comment by littlemo** [comment]
> > 信你个鬼
> 
> 实话告诉你我是币圈的、币圈更惨无人道啊啊啊啊

我去年3月从一个币圈的诈骗公司离职的，去年底听前同事说老板拖欠了三个多月工资，外面还欠了一屁股债😂

**Comment by Tianyazz** [comment]
我差点就信了

**Comment by adyliu** [comment]
糟老猎头坏滴很

**Comment by Doris66666** [comment]
> > > 信你个鬼
> > 
> > 
> > 实话告诉你我是币圈的，币圈更惨无人道啊啊啊啊
> 
> 我去年3月从一个币圈的诈骗公司离职的，去年底听前同事说老板拖欠了三个多月工资，外面还欠了一屁股债😂

嗯，币圈到处都是骗子、程序员宝宝们不要轻易相信他们画的饼

**Comment by Doris66666** [comment]
> 说吧，啥要求，要几年工作经验？

你是问恋爱经验吗？

**Comment by aeris-ming** [comment]
我看了下这个所谓妹子的项目，大家小心

**Comment by Adolphsa** [comment]
我要喝手磨咖啡

**Comment by linuxwind** [comment]
单身狗快commit.

**Comment by fandongbo** [comment]
妹子，他们不信你，我信。

**Comment by littlemo** [comment]
> > > > 信你个鬼
> > > 
> > > 
> > > 实话告诉你我是币圈的，币圈更惨无人道啊啊啊啊
> > 
> > 
> > 我去年3月从一个币圈的诈骗公司离职的，去年底听前同事说老板拖欠了三个多月工资，外面还欠了一屁股债😂
> 
> 嗯，币圈到处都是骗子、程序员宝宝们不要轻易相信他们画的饼

不过我是领完了年终奖和开工利市后溜得，哈哈哈，心疼前同事

**Comment by Doris66666** [comment]
> 现在猎头的套路真多

我是做运营的、呜呜~~~

**Comment by welpher** [comment]
大diao萌妹，你好

**Comment by Doris66666** [comment]
> 我要喝手磨咖啡

大强乖哦，让丽丽帮你冲

**Comment by Doris66666** [comment]
> 信你个鬼
等我给你发喜糖

**Comment by kxjqj** [comment]
我在南山后海

**Comment by Doris66666** [comment]
> 大diao萌妹，你好

噗

**Comment by Doris66666** [comment]
> 我在南山后海

我在南山大冲

**Comment by AbelZh** [comment]
yes

**Comment by kxjqj** [comment]
约一下？

**Comment by Doris66666** [comment]
> 妹子，他们不信你，我信。

小哥哥你有眼光

**Comment by Doris66666** [comment]
> 约一下？

我看你代码库提交的代码好少、你是不是刚毕业没多少0.0

**Comment by wenyejie** [comment]
> > 约一下？
> 
> 我看你代码库提交的代码好少、你是不是刚毕业没多少0.0

你还说你不是招聘! 你个骗子

**Comment by kxjqj** [comment]
之前的账号不用了

**Comment by Doris66666** [comment]
> > > 约一下？
> > 
> > 
> > 我看你代码库提交的代码好少、你是不是刚毕业没多少0.0
> 
> 你还说你不是招聘! 你个骗子

找对象就是找投资标的呀、你经验少肯定工资低、工资低还想谈恋爱、哈哈哈

**Comment by Doris66666** [comment]
> _No description provided._

竟然没人相信我、这一切的背后到底是道德的沦丧，还是人性的扭曲0.0

**Comment by Doris66666** [comment]
> 我要继续写BUG，女朋友是什么鬼

不是debug么、你写bug干啥0.0

**Comment by Doris66666** [comment]
> 一看就是hr

眼见不一定为真

**Comment by Doris66666** [comment]
> 我看了下这个所谓妹子的项目，大家小心

额、你从哪里看的、我的Github上的代码是我学编程的时候复制粘贴用来学习的

**Comment by ArtSword** [comment]
> > 说吧，啥要求，要几年工作经验？
> 
> 你是问恋爱经验吗？

是的呀,必要的话可以提交恋爱简历

**Comment by Doris66666** [comment]
> 之前的账号不用了

你说啥、什么账号

**Comment by WangSiTu** [comment]
币圈+1，也在大冲。。

**Comment by xuxiang9608** [comment]
性感不辞冰雪在线相亲

**Comment by Hanggi** [comment]
请先表明你的性别，再提找男朋友的事。

**Comment by ZhaoriGame** [comment]
在线相亲

**Comment by c0wry** [comment]
嘤嘤嘤

**Comment by Doris66666** [comment]
> 币圈+1，也在大冲..

昨晚抢到top了么

**Comment by Doris66666** [comment]
> 请先表明你的性别，再提找男朋友的事。

性别女、95年

**Comment by ArtSword** [comment]
> > > > 说吧，啥要求，要几年工作经验？
> > > 
> > > 
> > > 你是问恋爱经验吗？
> > 
> > 
> > 是的呀,必要的话可以提交恋爱简历
> 
> 来呀、互相提交
> 
> > > > 说吧，啥要求，要几年工作经验？
> > > 
> > > 
> > > 你是问恋爱经验吗？
> > 
> > 
> > 是的呀,必要的话可以提交恋爱简历
> 
> 那互相提交

int getInLoveCount(boolean isLove) {
    if(isLove){
        return 1;
    }else{
        return 0;
    }
}

我好了,你呢

**Comment by lai3d** [comment]
我长得不够帅，要不然就应征了 :)

**Comment by Doris66666** [comment]
> _没有提供说明。_



> > > > > 说吧，啥要求，要几年工作经验？
> > > > 
> > > > 
> > > > 你是问恋爱经验吗？
> > > 
> > > 
> > > 是的呀，必要的话可以提交恋爱简历
> > 
> > 
> > 来呀，互相提交
> > > > > 说吧，啥要求，要几年工作经验？
> > > > 
> > > > 
> > > > 你是问恋爱经验吗？
> > > 
> > > 
> > > 是的呀，必要的话可以提交恋爱简历
> > 
> > 
> > 那互相提交
> 
> int getInLoveCount（boolean isLove）{ 
> if（isLove）{ 
> return 1; 
> } else { 
> return 0; 
> } 
> }
> 
> 我好了，你呢

我不会0.0 大神教我好不好、哈哈

**Comment by leizelong** [comment]
山有木兮木有枝，心悦君兮君不知

**Comment by Byron4j** [comment]
:ber:  girl?

**Comment by xbhuang1994** [comment]
舆论压力排山倒海,却又波澜不惊、从容不迫，想必是经历过风餐露宿，体验过人生冷暖。还对恋爱充满憧憬，对未来报有希望。这么可爱的软妹子，我收了！顶我上去！

**Comment by Doris66666** [comment]
> _No description provided._

我95年、性别女、性取向男、非HR、base深圳南山，无房无车、月薪1万、平时喜欢看美剧，上下班路上喜欢听得到APP，目前在学习英语，今年的目标是将英语提升到能作为工作语言，然后找个男朋友恢复正常人的生活，我觉得找一只呆萌程序员会很好玩，哈哈。我们公司也是996制，过着每天两点一线的生活、生活已经这么艰难了，为什么不找个人开开心心的一起往前走呢。我的微信YL13510195455，不喜勿喷，非诚勿扰。

**Comment by HenryYong** [comment]
大冲-福田 的飘过

**Comment by seven7goddess** [comment]
我信你个鬼，糟老太婆

**Comment by Doris66666** [comment]
> 舆论压力排山倒海,却又波澜不惊、从容不迫，想必是经历过风餐露宿，体验过人生冷暖。还对恋爱充满憧憬，对未来报有希望。这么可爱的软妹子，我收了！顶我上去！

怕自己轻易认输后、就错过了、能争取的要努力争取呀、毕竟等了这么久也没等到有人说喜欢我

**Comment by Doris66666** [comment]
> 我信你个鬼，糟老太婆

这位大神请留下你的姓名，我坐等哪个鬼真信了我了，我撒糖给你吃

**Comment by likecreep** [comment]
瞎凑热闹的就别专门开个issue了吧。issue用来正经讨论。

**Comment by ceehkn** [comment]
小姐姐，茶叶多少钱

**Comment by ArtSword** [comment]
> > _No description provided._
> 
> 我95年、性别女、性取向男、非HR、base深圳南山，无房无车、月薪1万、平时喜欢看美剧，上下班路上喜欢听得到APP，目前在学习英语，今年的目标是将英语提升到能作为工作语言，然后找个男朋友恢复正常人的生活，我觉得找一只呆萌程序员会很好玩，哈哈。我们公司也是996制，过着每天两点一线的生活、生活已经这么艰难了，为什么不找个人开开心心的一起往前走呢。我的微信YL13510195455，不喜勿喷，非诚勿扰。

同95

**Comment by adyliu** [comment]
荆州? 区块链投资分析师? 小姐姐可以啊

**Comment by Doris66666** [comment]
> > > _No description provided._
> > 
> > 
> > 我95年、性别女、性取向男、非HR、base深圳南山，无房无车、月薪1万、平时喜欢看美剧，上下班路上喜欢听得到APP，目前在学习英语，今年的目标是将英语提升到能作为工作语言，然后找个男朋友恢复正常人的生活，我觉得找一只呆萌程序员会很好玩，哈哈。我们公司也是996制，过着每天两点一线的生活、生活已经这么艰难了，为什么不找个人开开心心的一起往前走呢。我的微信YL13510195455，不喜勿喷，非诚勿扰。
> 
> 同95

厉害了，膜拜大佬！

**Comment by Doris66666** [comment]
> 荆州? 区块链投资分析师? 小姐姐可以啊

这个资料是在哪里看的0.0  我在深圳南山

**Comment by Doris66666** [comment]
> _No description provided._

我觉得这种抵制能起到一定的效果，但实施还是需要时间的，生活还得继续，但如果你在这次抗议中找到一个努力又逗逼的女朋友，这不就是这次抗议最好的收获么。

**Comment by denjay** [comment]
逛个gayhub都能遇到想结束我单身的人，世间险恶啊

**Comment by eeeeeeeason** [comment]
差点信了你的鞋

**Comment by Zz1204** [comment]
mark

**Comment by dinglittle** [comment]
我信你个鬼，你个糟老头子

**Comment by dinglittle** [comment]
我信你个鬼，你个糟老头子

**Comment by dinglittle** [comment]
我信你个鬼，你个糟老头子

**Comment by army8735** [comment]
我勒个去，看热闹

**Comment by whenk7** [comment]
一股清流，我不信

**Comment by Doris66666** [comment]
在全球最大同性交友网站出现了异性并说说这种话、却是让人难以相信

**Comment by Doris66666** [comment]
确实

**Comment by liweiDiao** [comment]
猎头，绝对是

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bigbigliu** [comment]
不要，我要加班，我要搬砖

**Comment by T-mans** [comment]
快来私信我😄，我就是小哥哥。天天面向对象编程的那个。

**Comment by wangwindlong** [comment]
Hello world 不是 hello word,一字之差，谬以千里

**Comment by zhangqi-net** [comment]
哈哈哈哈哈哈，小姐姐看过来，你看我行不？

**Comment by Robinsir** [comment]
搬好板凳看热闹:)

**Comment by zaxguo** [comment]
要求至少985 你有🐴？

**Comment by ositowang** [comment]
买茶叶

**Comment by JamesGu14** [comment]
来错地方了，github是最大的同性交友网站！

**Comment by ChoviWu** [comment]
我来观光一下

**Comment by gxsaccount** [comment]
指望程序员会手把手教你代码吗？我们只会叫你Google，就算单身一辈子。(ˇ╮ˇ)

**Comment by light0x00** [comment]
在知乎上看到 这个画风清奇的issue 笑死我了

**Comment by luyixin** [comment]
老哥，你来错地方了，这里是全球最大的同性交友社区，当然，说的是男性。信你个鬼…😂😂😂

**Comment by Lewic1201** [comment]
吹吧就

**Comment by ccwumao** [comment]
小姐姐，你想找女朋友吗～我很想认识你☺️

**Comment by WenHaiGo** [comment]
我信了   我要找女朋友   微信号是 wwh_tec

**Comment by ahojcn** [comment]
信你个龟龟🐢

**Comment by lmikoto** [comment]
不会hello world，会github提issue？

**Comment by xbchome** [comment]
> > _No description provided._
> 
> 我觉得这种抵制能起到一定的效果，但实施还是需要时间的，生活还得继续，但如果你在这次抗议中找到一个努力又逗逼的女朋友，这不就是这次抗议最好的收获么。

你说的好有道理啊

**Comment by synckey** [comment]
学Hello world失败还能有github 账号？信你个鬼😒

**Comment by magicTraveller** [comment]
ah h h震惊!!来github相亲 表面面无表情，内心颇为期待

**Comment by Ghwolfzx** [comment]
祝你成功！记得回来撒糖

**Comment by jorhelp** [comment]
如果你也考研，我们或许可以做基友

**Comment by cchslt** [comment]
信你个鬼哟，hello world 都写错，肯定失败了

**Comment by yizhuzi** [comment]
Hello world写错了.....

**Comment by 15207108156** [comment]
同九年汝优秀

**Comment by weiluck** [comment]
正好快走了,有什么坑,要几年经验

**Comment by gzdzss** [comment]
hr 鉴定完毕

**Comment by RicoLiu** [comment]
猎头呗

**Comment by Doris66666** [comment]
> 快来私信我😄，我就是小哥哥。天天面向对象编程的那个。

求问私下怎么发、哈哈哈

**Comment by Doris66666** [comment]
> 你好世界写错了.....

由此可见我的编程真的没学好、以及英语也没学好

**Comment by Doris66666** [comment]
> 信你个鬼哟，你好世界都写错，肯定失败了

哈哈哈、所以我说自己编程学失败了、是真话呀

**Comment by Doris66666** [comment]
> 如果你也考研，我们或许可以做基友

我在为考研做准备、不过我水平很烂、是坑队友的那种

**Comment by Doris66666** [comment]
> 啊......震惊!!来github相亲表面面无表情，内心颇为期待

给你的内心戏打100分

**Comment by Codekiller-Li** [comment]
现在hr套路都这么深了吗，打入我们内部了

**Comment by Doris66666** [comment]
> 你好世界失败还能有github账号？信你个鬼😒

很讨厌英语错一个字母就成了另一个单词、不像中文忘记笔画了还可以写成草书~~~
github是2017年跟着李笑来学编程的时候开的、虽然代码没学会、但还是会用几个功能、哈哈

**Comment by Doris66666** [comment]
> 指望程序员会手把手教你代码吗？我们只会叫你谷歌，就算单身一辈子。（╮）

让我想起了我学编程的时候学会的一个技能、叫拒绝做伸手党。这是正宗的程序员、哈哈

**Comment by Doris66666** [comment]
> 你好世界不是你好的话，一字之差，谬以千里

所以我编程学失败了嘛

**Comment by Doris66666** [comment]
> 在知乎上看到这个画风清奇的问题笑死我了

知乎哪里?

**Comment by Doris66666** [comment]
> 正好快走了，有什么坑，要几年经验

你还是别走吧、去年底裁员太多人了、今年找工作竞争压力很大

**Comment by Doris66666** [comment]
> > > _没有提供说明。_
> > 
> > 
> > 我觉得这种抵制能起到一定的效果，但实施还是需要时间的，生活还得继续，但如果你在这次抗议中找到一个努力又逗逼的女朋友，这不就是这次抗议最好的收获么。
> 
> 你说的好有道理啊

这叫看清现实、哈哈哈

**Comment by xuCesar** [comment]
![WechatIMG1490](https://user-images.githubusercontent.com/13073787/55125351-683d8900-5144-11e9-9e88-45acb86c598e.jpeg)

**Comment by lovewenzi** [comment]
广告都打到GitHub来了么

**Comment by synckey** [comment]
看了下楼主第一门语言学的是 ruby， 难怪会失败了。

**Comment by CoderKontar** [comment]
学个helloworld就想钓程序员！

**Comment by Co2333** [comment]
你够自律吗？

**Comment by yuyufeng1994** [comment]
3年恋爱经验，熟练掌握技术，资源加班开小会（手动狗头）

**Comment by 21cm** [comment]
wechat : czy1518025518
location ：jiangxi ganzhou
age ：22

**Comment by OneVicetone** [comment]
有点意思

**Comment by RyanIPO** [comment]
糟老头子🙊

**Comment by Lingqinyu** [comment]
get out! bitch!

**Comment by Doris66666** [comment]
> 看了下楼主第一门语言学的是ruby，难怪会失败了。

是李笑来开的编程班、编程没学好、被拐去买比特币了

**Comment by MendesChen** [comment]
https://github.com/996icu/996.ICU/issues/839#issuecomment-477416045
为考研准备加一

**Comment by xbchome** [comment]
> > 看了下楼主第一门语言学的是ruby，难怪会失败了。
> 
> 是李笑来开的编程班、编程没学好、被拐去买比特币了

哇喔  比特币 好厉害的样子

**Comment by Doris66666** [comment]
> 学个的HelloWorld就想钓程序员！

你错了，我是以女生的身份钓程序员~~~

**Comment by xbchome** [comment]
> > 学个的HelloWorld就想钓程序员！
> 
> 你错了，我是以女生的身份钓程序员~~~

我不信还没人加你

**Comment by Doris66666** [comment]
> [＃839（评论）](https://github.com/996icu/996.ICU/issues/839#issuecomment-477416045)
> 为考研准备加一

加油！!

**Comment by MendesChen** [comment]
https://github.com/996icu/996.ICU/issues/839#issuecomment-477434981
嗯嗯

**Comment by juneqiu** [comment]
坚哥，你在吗？

**Comment by pofycn** [comment]
小姐姐约吗

**Comment by juneqiu** [comment]
坚哥，崇哥，你们都在看吗？

**Comment by canyie** [comment]
信你个鬼.java

**Comment by vslofty** [comment]
对象，new一个就有了

**Comment by zxpFreesky** [comment]
就会hello world，别的不会了……

**Comment by liangzhanncu** [comment]
各位老实人不要信她😂

**Comment by Doris66666** [comment]
> 各位老实人不要信她😂

我欺骗你什么了~~~

**Comment by Doris66666** [comment]
> 就会hello world，别的不会了……

我还会看代码库里的代码量~~~

**Comment by kiritosaigao** [comment]
coding and encoding，so busy

**Comment by Doris66666** [comment]
> 小姐姐约吗

约*一时爽，染病火葬场

**Comment by yulele166** [comment]
留下微信

**Comment by st2008303338** [comment]
你倒是留个联系方式

**Comment by hhxx2015** [comment]
> 3年恋爱经验，熟练掌握技术，自愿加班开小会，可否（手动狗头）

你个工贼

**Comment by WeaponA** [comment]
糟老头子，坏滴很

**Comment by isFire** [comment]
> > 说吧，啥要求，要几年工作经验？
> 
> 你是问恋爱经验吗？
小姐姐周末约吗

**Comment by isFire** [comment]
@Doris66666 福田的小姐姐,留下你的联系方式 #

**Comment by nvshenaa** [comment]
你倒是放个微信啊

**Comment by kerraway** [comment]
各位不要信~她~他！！！

**Comment by xbchome** [comment]
> 你倒是放个微信啊

加完了 你们没机会了

**Comment by Doris66666** [comment]
> @Doris66666 福田的小姐姐,留下你的联系方式 #

我在南山、微信你往前面翻有的

**Comment by Doris66666** [comment]
> 留下微信

YL13510195455

**Comment by Doris66666** [comment]
> 各位不要信她他！！！

如果大家相信了你的话、你就会减少很多竞争者、聪明~~~

**Comment by qq22424** [comment]
惊了，我在福田上班，住在南山

**Comment by qq22424** [comment]
> > 小姐姐约吗
> 
> 约*一时爽，染病火葬场

一直约*一直爽

**Comment by xbchome** [comment]
> > > 小姐姐约吗
> > 
> > 
> > 约*一时爽，染病火葬场
> 
> 一直约*一直爽

一直都在火葬场

**Comment by pofycn** [comment]
> > > > 小姐姐约吗
> > > 
> > > 
> > > 约*一时爽，染病火葬场
> > 
> > 
> > 一直约*一直爽
> 
> 一直都在火葬场

我想化作骨灰

**Comment by Mamong** [comment]
这个repo能抗住这波美色侵蚀么？/哭笑

**Comment by wodis** [comment]
猎头现在套路太深了。。。。

**Comment by ieewbbwe** [comment]
说吧要几年经验做过啥项目的

**Comment by os7blue** [comment]
说吧，哪家公司在哪投简历。

**Comment by Loyy** [comment]
回复这一条，我就是参加过9000+star的了！
