### ISSUE TITLE
技术猎头，我来试着帮大家脱离苦海，欢迎加我WX：bendypan001

### ISSUE THREAD

**Issue by bendypan** [996icu/996.ICU#84]
努力帮大家找work life balance的工作！

**Comment by wzhongyuan** [comment]
先post 下职位看看，靠谱可以考虑加一下

**Comment by bendypan** [comment]
> 先post 下职位看看，靠谱可以考虑加一下， 朋友圈猎头实在太多了

大数据，机器学习，JAVA/Go/C++后台研发，devops，数据分析/挖掘，信息安全各种中高端职位，应有尽有，欢迎来撩

**Comment by bendypan** [comment]
目前主要关注/招聘的是  华东   地区的技术岗位

**Comment by pandyer** [comment]
.net群
![wz](https://user-images.githubusercontent.com/12846899/55131272-dbe99100-5158-11e9-945c-4f040fd1b5b4.jpg)
