### ISSUE TITLE
杭州IT者联盟（1群） 微信群 ################### 见证历史性一刻！！杭州打卡，拒绝996

### ISSUE THREAD

**Issue by guojing73** [996icu/996.ICU#8401]
![image](https://user-images.githubusercontent.com/49015467/55135327-4ead3900-5166-11e9-847e-fc92b8c2c020.png)

**Comment by shawlang** [comment]
欢迎把群二维码或者群号，都发到这个 issue 下面，这是一个汇总list，提前去抢位置：https://github.com/996icu/996.ICU/issues/8193

**Comment by songzhongleijavascript** [comment]
国家在支持有啥用
