### ISSUE TITLE
github会不会因此被堵住？

### ISSUE THREAD

**Issue by hakil** [996icu/996.ICU#8654]

**Comment by Ansion** [comment]
这才哪到哪呀。早得很！

【超低价爆品服务器、数据库秒杀】每日5场秒杀，分别于 9:00 / 11:00 / 14:00 / 16:00 / 19:00 开抢 ，错过再等半年。
[https://cloud.tencent.com](https://cloud.tencent.com/redirect.php?redirect=1036&cps_key=30f9b02705218180658b0439da8a6ba7&from=console)

**Comment by hakil** [comment]
@Ansion 你这样发广告不好吧？
