### ISSUE TITLE
杭州IT者联盟（1群） 微信群 ################################ 为自己而战，抵制996

### ISSUE THREAD

**Issue by lamplife** [996icu/996.ICU#8827]
![WechatIMG3599](https://user-images.githubusercontent.com/12744359/55136122-7e5d4080-5168-11e9-9e96-a93fce9db6fd.jpeg)

**Comment by lenvon2012** [comment]
![avatar](https://raw.githubusercontent.com/lenvon2012/trace-demo/master/20190328112642.jpg)

欢迎添加微信，输入、发送：  拉我进996群  

欢迎大家加入 交流、吐槽
