### ISSUE TITLE
如此脱节的世界啊，居然是为了纠正他而生。我们的敌人是996吗？不是，是我们自己，我们新一代的世界需要我们自己去抗争争取！

### ISSUE THREAD

**Issue by niboge** [996icu/996.ICU#8998]
996只是资本压榨我们的一种手段，为什么那么多人接受996？不是因为钱吗？有钱可以买更贵的房子，扶养孩子支付高昂的学费。

**Comment by niboge** [comment]
![image](https://user-images.githubusercontent.com/10307030/55136590-cfb9ff80-5169-11e9-9c86-031107ae5949.png)
ben'qun

**Comment by niboge** [comment]
新纪元运动主旨-新版
背景
在这个资本高度竞争的大环境下，人与人之间谈论的无非是房子股票娱乐，而且这些娱乐很大程度是无意识的经过资本加工过的、容易的、低端的，毕竟资本压力下，普通人觉得没时间研究那些没用的、复杂的、有深度内涵的，还不自知，妥协的，没骨气的觉得已经这样了啊，有什么办法。学学日本青年，佛系，不刻意讨好，不出家门，不买房子Orz。

危机
人类认知边界拓展任务的学习周期越来越长, 专业越来越内卷化
因各种各样的原因，那些认知水平更高的智人，似乎反而倾向于留下更少的后代
人类越来越倾向于不重视认知边界拓展，而是热衷于围绕存量进行再分配，甚至是与再分配不直接相关的“情绪“撕逼
强人造智能/主动硅基进化，遥遥无期
通过聪明努力提高生产效率的人越来越少，通过报团哭闹提高分配份额的人越来越多。
能量等级利用效率增长长期停滞，最后丧失掉进入星海的时间窗口，最后憋死在摇篮里。
拆开手机看看，其他零件精密的不得了，感觉已经像是下一个世代的科技了，就一块傻大黑粗的电池占了绝大多数重量和体积
外星高等生命飞船速度越来越逼近光速，我们地球危在旦夕，几个世纪之后如果还没有高速飞船，我们可能要被外星人虐待了
总结
下一个革命，会是灵魂革命，由所有年轻人中最有灵魂的一批人推动，这个新的革命是象征着人类精神高度自由的去中心化社会，不再围绕那些粗鄙无趣的东西为中心，也不会慵懒在家中坐吃船空，我们的理想大部分是围绕地球人都会面对的危机，我们不要facebook，目标是星辰大海。

新纪元运动
围绕物理最新的已证实理论(量子的平行宇宙理论)，追求真实的角度出发，探索意识、精神、高维世界的存在，或是发现生活本来的美，让城市更加环保，人与人之间更加和谐。不再浪费一点时间在无趣的事物上。

**Comment by niboge** [comment]
### **新纪元运动旧版**

新纪元运动并没有正式的定义。一些人认为只要把主流与传统的元素融入自己的个人化信念的都算是新纪元。
新纪元思想与行动涉及的范围很广，次文化的成员 自由选择某一种思想加以认同。至于到底哪一种当代的文化元素能够被称作“新纪元”则是很有争议的。
事实上，新纪元运动和各种心灵运动有诸多相同之处。许多心灵运动，例如新异教主义与超个人心理学就和新纪元运动有很大的重叠.
新纪元运动并没有特定确实的发起人或是团体，不过都不约而同的提出共同的概念。主要的概念有：
万物归一（All is one）；
一切都有神性（All is God）；
人即是神（Humanity is God）；
世界与人均会产生一种意识的大改变（A change in consciousness）；
一切宗教最终会归于一统（All religious are One）；
相信宇宙的进化，包括意识人性的进化，进化使世界最终是乐观的（Cosmic evolutionary optimism）；
你创造你自己的实相（You are creating your own reality）。
其实其他宗教也有提到这些概念，只是改用现代人的用语来说。

**Comment by nanusl** [comment]
前排瓜子小板凳

**Comment by ckex** [comment]
前排瓜子小板凳

**Comment by niboge** [comment]
我们也不是一定需要革命，毕竟都有各自的生活，但最起码要对外界有一个基本的反应吧？群里的人一定要先多起来吧？

我们白天码代码上线，晚上回家稍微思考下，我们年轻一代人就应该这么无趣的生活吗？

**Comment by niboge** [comment]
ice cream

**Comment by niboge** [comment]
愿中国程序员都摆脱冷气,只是向上走,不必听自暴自弃者流的话.能做事的做事 , 能发声的发声 , 不必等候炬火,若此后没有炬火 ,我便是唯一的光 , 我们可以卑微入尘土 不可扭曲如蛆虫 .
