### ISSUE TITLE
Spring boot 微服务组件集 mica 发来贺电，㊗️早日过十万！！！

### ISSUE THREAD

**Issue by ChunMengLu** [996icu/996.ICU#9039]
Spring boot 微服务组件集 mica，基于 Spring boot 2.x，支持 web 和 webflux：https://github.com/lets-mica/mica

**Comment by crazy2323** [comment]
![image](https://user-images.githubusercontent.com/8650896/55136633-ebbda100-5169-11e9-8a91-3412dc257c03.png)
