### ISSUE TITLE
InfoQ前来支持，没有买卖就没有杀害

### ISSUE THREAD

**Issue by ryantang1991** [996icu/996.ICU#9200]
发现这个项目的时候才几百个star，没想到一夜之间就已经4万+了。

作为一家技术媒体，很欣喜能看到广大程序员们勇于发声对996说不的行动。

希望这个GitHub项目能持续下去，有越来越多的人参与，改变整个行业！

最后做个分享，关注InfoQ公众号，回复关键词：福利，获取我们为程序员们准备的2019学习大礼包，内含架构师电子书全年合集、技能图谱全集等资料。

![qrcode_for_gh_b443474846ae_258](https://user-images.githubusercontent.com/35788620/55136718-2293b700-516a-11e9-96ab-7b4d68c4204e.jpg)

**Comment by noname2001** [comment]
【20w群容量 附群二维码】996ICU Telegram 欢迎你的加入 https://t.me/joinchat/JqKoNxaPcUJlQth5CKJ0Cw
