### ISSUE TITLE
ApacheCN社区福利群724187166欢迎各大公司HR进入，有海量求职者资源，996免谈！

### ISSUE THREAD

**Issue by wizardforcel** [996icu/996.ICU#9379]
ApacheCN社区福利群724187166欢迎各大公司HR进入，有海量求职者资源，996免谈！

ApacheCN社区福利群724187166欢迎各大公司HR进入，有海量求职者资源，996免谈！

ApacheCN社区福利群724187166欢迎各大公司HR进入，有海量求职者资源，996免谈！

**Comment by JokerChengY** [comment]
皮皮片刻？
