### ISSUE TITLE
有没有iOS 或者Java的组织，拉我一下，需要小姐姐关怀

### ISSUE THREAD

**Issue by Xcode123456** [996icu/996.ICU#9486]

**Comment by pangrongxian** [comment]
![image](https://user-images.githubusercontent.com/14255970/55137599-612a7100-516c-11e9-91ce-75c5f7fc46d7.png)

**Comment by phqvince** [comment]
SELECT COUNT(ID) FROM OUT_201902 WHERE STATUS IS NULL

**Comment by phqvince** [comment]
![image](https://user-images.githubusercontent.com/15265777/55137676-8cad5b80-516c-11e9-8d28-9b176e396de8.png)
