### ISSUE TITLE
996 投票地址

### ISSUE THREAD

**Issue by swuecho** [996icu/996.ICU#9496]
[投票地址](https://cloudqa.iego.cn/sr/icu996)

问卷结果，JSON 格式，直接从这里拿数据

用Vue 或者 React 搞个前端，然后放着github page 就可以了

[实时数据](http://122.112.218.148:15666/v_answer)

**Comment by bincute** [comment]
能不能写个页面呀？

**Comment by swuecho** [comment]
@bincute  可以啊，在筹备中，由多个项目在做这个工作了。目前先采集到数据，然后在考虑可视化，分析等。
