### ISSUE TITLE
996 ICU 测试吐槽微信群

### ISSUE THREAD

**Issue by Bugpcheng** [996icu/996.ICU#9540]
![image](https://user-images.githubusercontent.com/24777134/55137636-769f9b00-516c-11e9-83b6-16e5e2a2bda8.png)

**Comment by lenvon2012** [comment]
![avatar](https://raw.githubusercontent.com/lenvon2012/trace-demo/master/20190328112642.jpg)

欢迎添加微信，输入、发送：  拉我进996群  

欢迎大家加入 交流、吐槽
