### ISSUE TITLE
请问关闭这个东西的按键在哪里！！！

### ISSUE THREAD

**Issue by Doris66666** [996icu/996.ICU#961]

**Comment by AnLink** [comment]
小姐姐还可以啊，没结婚的深圳单身狗可以考虑啊～～

**Comment by ChokWah** [comment]
只有HR会上来找程序员。。。妹子是不会来这里的，别欺负我不懂。

**Comment by Doris66666** [comment]
> 只有HR会上来找程序员......妹子是不会来这里的，别欺负我不懂。

算了，我还是乖乖做单生狗吧、好累

**Comment by biekanwonicheng** [comment]
##### 挂一个女的头像，就是女的了<_<，欢迎来到最大**同性**交友平台

**Comment by licongyu95** [comment]
或许只是委婉拒绝你把，大家的真爱不是妹子。

**Comment by yangjianbing6** [comment]
hey guys

**Comment by librarysong** [comment]
**__**

**Comment by charlesld** [comment]
你写你的ruby，我写我的java，为什么要来相亲呢？

**Comment by kc910521** [comment]
你不是HR


但我想问下给你推荐男朋友转正后有奖金吗？

**Comment by Doris66666** [comment]
> 你写你的红宝石，我写我的java的，为什么要来相亲呢？

说的很对、请问下大神关闭帖子的按键在什么地方，我找不着了

**Comment by Doris66666** [comment]
> 你不是HR
> 
> 但我想问下给你推荐男朋友转正后有奖金吗？

不找了、没心情了

**Comment by zhengzhihust** [comment]
蓝蓝的天空~~~~

**Comment by VenXXX** [comment]
白云飘～～～

**Comment by DennisMao** [comment]
翟欣欣？

**Comment by MichelleWang616** [comment]
为啥找程序员？加班多，赚得多，死得早？

**Comment by Doris66666** [comment]
> 为啥找程序员？加班多，赚得多，死得早？

我错了、我走还不行么

**Comment by Amber125208** [comment]
刀瑞斯，你好(*´▽｀)ノノ

**Comment by dekai-wang** [comment]
妹子的关闭按钮找不到了，大家帮忙找一下啊

**Comment by MichelleWang616** [comment]
> > 为啥找程序员？加班多，赚得多，死得早？
> 
> 我错了、我走还不行么

最下面的comment的左侧有个close issue

**Comment by Doris66666** [comment]
> _没有提供说明。_




> > > 为啥找程序员？加班多，赚得多，死得早？
> > 
> > 
> > 我错了，我走还不行么
> 
> 最下面的评论的左侧有个关闭问题

谢谢小哥哥

**Comment by wikiios** [comment]
1

**Comment by iceytea** [comment]
😂

**Comment by ahojcn** [comment]
加油加油，遇见对滴人

**Comment by k53247l2** [comment]
我能理解你找程序员男朋友，因为大家都天天加班，这样就不会互相埋怨对方不顾家了（笑哭~~）

**Comment by 21cm** [comment]
wechat : czy1518025518
location ：jiangxi ganzhou
age ：22

**Comment by vexetron** [comment]
Issues are supposed to be related to the project.

**Comment by zhaomeiru66** [comment]
@Doris66666 加油，终究可以的
