### ISSUE TITLE
阿里拍卖面向2020届毕业生招聘啦，拒绝996！！！！

### ISSUE THREAD

**Issue by Nealyang** [996icu/996.ICU#9658]
### 🔥《阿里巴巴集团春季校园招聘》已经启动。
  
- 团队获取此消息后第一时间，赶紧通知，各位刚走出校园的千里马，走进阿里的机会来了！！！
 
 基本要求如下：
 
 - 招收 2019年11月-2020年10月 毕业的同学
 - 本次校招行动共执行四周，到 4月12日结束

#### 🔔强调一下这次是校招哦！！！如果你有意向，又符合 2019年11月-2020年10月 的应届毕业生条件;

- 不符合，也没关系，可以推荐优秀的学弟，学妹；增进一下“纯洁”的同学感情 👫😎。

#### 请移步往下,关注我们《阿里拍卖团队》 的招聘信息。

<img src="https://img.alicdn.com/tfs/TB1mJ5tL7PoK1RjSZKbXXX1IXXa-748-879.png" width=500>

<img src="https://img.alicdn.com/tfs/TB1PhOrLYrpK1RjSZTEXXcWAVXa-748-794.png" width=500>

<img src="https://img.alicdn.com/tfs/TB1FXOlLYPpK1RjSZFFXXa5PpXa-748-440.png" width=500>

#### 最重要的部分来了，手机扫描下面二维码，即可进入简历投递系统

<img src="https://img.alicdn.com/tfs/TB1wO8CM3HqK1RjSZJnXXbNLpXa-176-163.png" width=200>

**Comment by NeverBefore** [comment]
阿里加班不也是很严重？

**Comment by Nealyang** [comment]
> 阿里加班不也是很严重？

不不不，我们不推崇加班的

**Comment by xllove-moon** [comment]
果然HR也吸引来了吗！！

**Comment by Nealyang** [comment]
> 果然HR也吸引来了吗！！

我不是 hr，hr 说的拒接996能信嘛~~

**Comment by z15918320** [comment]
HR的话靠得住  母猪也能上树

**Comment by Nealyang** [comment]
> HR的话靠得住 母猪也能上树

货真的前端哇~~

**Comment by minghe** [comment]
真没 996 ，欢迎来投。

**Comment by NeverBefore** [comment]
> > 阿里加班不也是很严重？
> 
> 不不不，我们不推崇加班的

阿里我死在了三面，现在想想还心痛~~~

**Comment by xuyuan923** [comment]
我们团队有3个妹子😝

**Comment by ryan730** [comment]
试问，有一个地方, 晚饭免费，夜宵免费，打车报销，健身免费，晚饭后，还可以和妹子在园区压压马路，
下班着急回到6，7平不到出租屋，还有什么意义 ？？？！！！

**Comment by ryan730** [comment]
试问，有一个地方, 晚饭免费，夜宵免费，打车报销，健身免费，晚饭后，还可以和妹子在园区压压马路，
下班着急回到6，7平不到出租屋，除了打两局坑爹的《王者荣耀》，还有什么意义 ？？？！！！
