### ISSUE TITLE
不要再报有什么中产阶级的幻想，全世界的无阶级联合起来。

### ISSUE THREAD

**Issue by fuyb** [996icu/996.ICU#9830]
不要再报有什么中产阶级的幻想，全世界的无阶级联合起来。
《共产党宣言》：[共产党宣言](https://www.marxists.org/chinese/marx/01.htm)

**Comment by ecmagod** [comment]
锋利的golang，纯粹的go语言交流群，一起从go小白，到年薪百万工程师，QQ群：10930775
